package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CpCondicaoPagamento generated by hbm2java
 */
public class CpCondicaoPagamento  implements java.io.Serializable {


     private int condicaoPagamentoId;
     private String descricao;
     private long srRecno;
     private Set cpRequisis = new HashSet(0);
     private Set cpSolicitacaos = new HashSet(0);

    public CpCondicaoPagamento() {
    }

	
    public CpCondicaoPagamento(int condicaoPagamentoId, String descricao, long srRecno) {
        this.condicaoPagamentoId = condicaoPagamentoId;
        this.descricao = descricao;
        this.srRecno = srRecno;
    }
    public CpCondicaoPagamento(int condicaoPagamentoId, String descricao, long srRecno, Set cpRequisis, Set cpSolicitacaos) {
       this.condicaoPagamentoId = condicaoPagamentoId;
       this.descricao = descricao;
       this.srRecno = srRecno;
       this.cpRequisis = cpRequisis;
       this.cpSolicitacaos = cpSolicitacaos;
    }
   
    public int getCondicaoPagamentoId() {
        return this.condicaoPagamentoId;
    }
    
    public void setCondicaoPagamentoId(int condicaoPagamentoId) {
        this.condicaoPagamentoId = condicaoPagamentoId;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }
    public Set getCpRequisis() {
        return this.cpRequisis;
    }
    
    public void setCpRequisis(Set cpRequisis) {
        this.cpRequisis = cpRequisis;
    }
    public Set getCpSolicitacaos() {
        return this.cpSolicitacaos;
    }
    
    public void setCpSolicitacaos(Set cpSolicitacaos) {
        this.cpSolicitacaos = cpSolicitacaos;
    }




}


