package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CpCompra generated by hbm2java
 */
public class CpCompra  implements java.io.Serializable {


     private CpCompraId id;
     private CpTipoCompra cpTipoCompra;
     private Gano gano;
     private Character tceTipoCompra;
     private char classifica;
     private Character modiCond;
     private Character situacao;
     private String seqPubl;
     private String horas;
     private String doe;
     private String edital;
     private String ata;
     private String validade;
     private String observacao;
     private String tpPrazo;
     private String prazoDesc;
     private String dotacao;
     private String arqText;
     private String advogado;
     private String jornal;
     private String condicao;
     private String prazo;
     private String convenio;
     private String assunto;
     private BigDecimal vlPrevi;
     private Integer codUni;
     private Date dataAta;
     private Date dtAber;
     private Date dtLimite;
     private Date dtPubl;
     private Date dtPbDoe;
     private int encerrado;
     private String parecer;
     private char cancelada;
     private Date dtCancela;
     private String condParticipacao;
     private String motCancela;
     private String veiCancela;
     private long srRecno;
     private Date gacesso;
     private int tipoPessoa;
     private String numProcesso;
     private Character desertar;
     private Date dtParecerJur;
     private Date dtParecerCpl;
     private String usaSrp;
     private String excluirRel;
     private String regimeExec;
     private String chkAplic;
     private Character liberarProposta;
     private String plicNomearqpdf;
     private String utilizaLeiCompl;
     private String plicParamicroempresa;
     private Integer tipoValor;
     private Integer tpMaterialTce;
     private Character remume;
     private Set cpSelecaos = new HashSet(0);
     private Set cpSolMats = new HashSet(0);
     private Set esRecebimentos = new HashSet(0);
     private Set cpProtocolos = new HashSet(0);
     private Set cpItems = new HashSet(0);
     private Set cpRequisis = new HashSet(0);
     private Set cpSolicitacaos = new HashSet(0);
     private Set esAplicacaoDiretas = new HashSet(0);

    public CpCompra() {
    }

	
    public CpCompra(CpCompraId id, CpTipoCompra cpTipoCompra, Gano gano, char classifica, int encerrado, char cancelada, long srRecno, int tipoPessoa, String usaSrp, String excluirRel, String chkAplic, String utilizaLeiCompl, String plicParamicroempresa) {
        this.id = id;
        this.cpTipoCompra = cpTipoCompra;
        this.gano = gano;
        this.classifica = classifica;
        this.encerrado = encerrado;
        this.cancelada = cancelada;
        this.srRecno = srRecno;
        this.tipoPessoa = tipoPessoa;
        this.usaSrp = usaSrp;
        this.excluirRel = excluirRel;
        this.chkAplic = chkAplic;
        this.utilizaLeiCompl = utilizaLeiCompl;
        this.plicParamicroempresa = plicParamicroempresa;
    }
    public CpCompra(CpCompraId id, CpTipoCompra cpTipoCompra, Gano gano, Character tceTipoCompra, char classifica, Character modiCond, Character situacao, String seqPubl, String horas, String doe, String edital, String ata, String validade, String observacao, String tpPrazo, String prazoDesc, String dotacao, String arqText, String advogado, String jornal, String condicao, String prazo, String convenio, String assunto, BigDecimal vlPrevi, Integer codUni, Date dataAta, Date dtAber, Date dtLimite, Date dtPubl, Date dtPbDoe, int encerrado, String parecer, char cancelada, Date dtCancela, String condParticipacao, String motCancela, String veiCancela, long srRecno, Date gacesso, int tipoPessoa, String numProcesso, Character desertar, Date dtParecerJur, Date dtParecerCpl, String usaSrp, String excluirRel, String regimeExec, String chkAplic, Character liberarProposta, String plicNomearqpdf, String utilizaLeiCompl, String plicParamicroempresa, Integer tipoValor, Integer tpMaterialTce, Character remume, Set cpSelecaos, Set cpSolMats, Set esRecebimentos, Set cpProtocolos, Set cpItems, Set cpRequisis, Set cpSolicitacaos, Set esAplicacaoDiretas) {
       this.id = id;
       this.cpTipoCompra = cpTipoCompra;
       this.gano = gano;
       this.tceTipoCompra = tceTipoCompra;
       this.classifica = classifica;
       this.modiCond = modiCond;
       this.situacao = situacao;
       this.seqPubl = seqPubl;
       this.horas = horas;
       this.doe = doe;
       this.edital = edital;
       this.ata = ata;
       this.validade = validade;
       this.observacao = observacao;
       this.tpPrazo = tpPrazo;
       this.prazoDesc = prazoDesc;
       this.dotacao = dotacao;
       this.arqText = arqText;
       this.advogado = advogado;
       this.jornal = jornal;
       this.condicao = condicao;
       this.prazo = prazo;
       this.convenio = convenio;
       this.assunto = assunto;
       this.vlPrevi = vlPrevi;
       this.codUni = codUni;
       this.dataAta = dataAta;
       this.dtAber = dtAber;
       this.dtLimite = dtLimite;
       this.dtPubl = dtPubl;
       this.dtPbDoe = dtPbDoe;
       this.encerrado = encerrado;
       this.parecer = parecer;
       this.cancelada = cancelada;
       this.dtCancela = dtCancela;
       this.condParticipacao = condParticipacao;
       this.motCancela = motCancela;
       this.veiCancela = veiCancela;
       this.srRecno = srRecno;
       this.gacesso = gacesso;
       this.tipoPessoa = tipoPessoa;
       this.numProcesso = numProcesso;
       this.desertar = desertar;
       this.dtParecerJur = dtParecerJur;
       this.dtParecerCpl = dtParecerCpl;
       this.usaSrp = usaSrp;
       this.excluirRel = excluirRel;
       this.regimeExec = regimeExec;
       this.chkAplic = chkAplic;
       this.liberarProposta = liberarProposta;
       this.plicNomearqpdf = plicNomearqpdf;
       this.utilizaLeiCompl = utilizaLeiCompl;
       this.plicParamicroempresa = plicParamicroempresa;
       this.tipoValor = tipoValor;
       this.tpMaterialTce = tpMaterialTce;
       this.remume = remume;
       this.cpSelecaos = cpSelecaos;
       this.cpSolMats = cpSolMats;
       this.esRecebimentos = esRecebimentos;
       this.cpProtocolos = cpProtocolos;
       this.cpItems = cpItems;
       this.cpRequisis = cpRequisis;
       this.cpSolicitacaos = cpSolicitacaos;
       this.esAplicacaoDiretas = esAplicacaoDiretas;
    }
   
    public CpCompraId getId() {
        return this.id;
    }
    
    public void setId(CpCompraId id) {
        this.id = id;
    }
    public CpTipoCompra getCpTipoCompra() {
        return this.cpTipoCompra;
    }
    
    public void setCpTipoCompra(CpTipoCompra cpTipoCompra) {
        this.cpTipoCompra = cpTipoCompra;
    }
    public Gano getGano() {
        return this.gano;
    }
    
    public void setGano(Gano gano) {
        this.gano = gano;
    }
    public Character getTceTipoCompra() {
        return this.tceTipoCompra;
    }
    
    public void setTceTipoCompra(Character tceTipoCompra) {
        this.tceTipoCompra = tceTipoCompra;
    }
    public char getClassifica() {
        return this.classifica;
    }
    
    public void setClassifica(char classifica) {
        this.classifica = classifica;
    }
    public Character getModiCond() {
        return this.modiCond;
    }
    
    public void setModiCond(Character modiCond) {
        this.modiCond = modiCond;
    }
    public Character getSituacao() {
        return this.situacao;
    }
    
    public void setSituacao(Character situacao) {
        this.situacao = situacao;
    }
    public String getSeqPubl() {
        return this.seqPubl;
    }
    
    public void setSeqPubl(String seqPubl) {
        this.seqPubl = seqPubl;
    }
    public String getHoras() {
        return this.horas;
    }
    
    public void setHoras(String horas) {
        this.horas = horas;
    }
    public String getDoe() {
        return this.doe;
    }
    
    public void setDoe(String doe) {
        this.doe = doe;
    }
    public String getEdital() {
        return this.edital;
    }
    
    public void setEdital(String edital) {
        this.edital = edital;
    }
    public String getAta() {
        return this.ata;
    }
    
    public void setAta(String ata) {
        this.ata = ata;
    }
    public String getValidade() {
        return this.validade;
    }
    
    public void setValidade(String validade) {
        this.validade = validade;
    }
    public String getObservacao() {
        return this.observacao;
    }
    
    public void setObservacao(String observacao) {
        this.observacao = observacao;
    }
    public String getTpPrazo() {
        return this.tpPrazo;
    }
    
    public void setTpPrazo(String tpPrazo) {
        this.tpPrazo = tpPrazo;
    }
    public String getPrazoDesc() {
        return this.prazoDesc;
    }
    
    public void setPrazoDesc(String prazoDesc) {
        this.prazoDesc = prazoDesc;
    }
    public String getDotacao() {
        return this.dotacao;
    }
    
    public void setDotacao(String dotacao) {
        this.dotacao = dotacao;
    }
    public String getArqText() {
        return this.arqText;
    }
    
    public void setArqText(String arqText) {
        this.arqText = arqText;
    }
    public String getAdvogado() {
        return this.advogado;
    }
    
    public void setAdvogado(String advogado) {
        this.advogado = advogado;
    }
    public String getJornal() {
        return this.jornal;
    }
    
    public void setJornal(String jornal) {
        this.jornal = jornal;
    }
    public String getCondicao() {
        return this.condicao;
    }
    
    public void setCondicao(String condicao) {
        this.condicao = condicao;
    }
    public String getPrazo() {
        return this.prazo;
    }
    
    public void setPrazo(String prazo) {
        this.prazo = prazo;
    }
    public String getConvenio() {
        return this.convenio;
    }
    
    public void setConvenio(String convenio) {
        this.convenio = convenio;
    }
    public String getAssunto() {
        return this.assunto;
    }
    
    public void setAssunto(String assunto) {
        this.assunto = assunto;
    }
    public BigDecimal getVlPrevi() {
        return this.vlPrevi;
    }
    
    public void setVlPrevi(BigDecimal vlPrevi) {
        this.vlPrevi = vlPrevi;
    }
    public Integer getCodUni() {
        return this.codUni;
    }
    
    public void setCodUni(Integer codUni) {
        this.codUni = codUni;
    }
    public Date getDataAta() {
        return this.dataAta;
    }
    
    public void setDataAta(Date dataAta) {
        this.dataAta = dataAta;
    }
    public Date getDtAber() {
        return this.dtAber;
    }
    
    public void setDtAber(Date dtAber) {
        this.dtAber = dtAber;
    }
    public Date getDtLimite() {
        return this.dtLimite;
    }
    
    public void setDtLimite(Date dtLimite) {
        this.dtLimite = dtLimite;
    }
    public Date getDtPubl() {
        return this.dtPubl;
    }
    
    public void setDtPubl(Date dtPubl) {
        this.dtPubl = dtPubl;
    }
    public Date getDtPbDoe() {
        return this.dtPbDoe;
    }
    
    public void setDtPbDoe(Date dtPbDoe) {
        this.dtPbDoe = dtPbDoe;
    }
    public int getEncerrado() {
        return this.encerrado;
    }
    
    public void setEncerrado(int encerrado) {
        this.encerrado = encerrado;
    }
    public String getParecer() {
        return this.parecer;
    }
    
    public void setParecer(String parecer) {
        this.parecer = parecer;
    }
    public char getCancelada() {
        return this.cancelada;
    }
    
    public void setCancelada(char cancelada) {
        this.cancelada = cancelada;
    }
    public Date getDtCancela() {
        return this.dtCancela;
    }
    
    public void setDtCancela(Date dtCancela) {
        this.dtCancela = dtCancela;
    }
    public String getCondParticipacao() {
        return this.condParticipacao;
    }
    
    public void setCondParticipacao(String condParticipacao) {
        this.condParticipacao = condParticipacao;
    }
    public String getMotCancela() {
        return this.motCancela;
    }
    
    public void setMotCancela(String motCancela) {
        this.motCancela = motCancela;
    }
    public String getVeiCancela() {
        return this.veiCancela;
    }
    
    public void setVeiCancela(String veiCancela) {
        this.veiCancela = veiCancela;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }
    public Date getGacesso() {
        return this.gacesso;
    }
    
    public void setGacesso(Date gacesso) {
        this.gacesso = gacesso;
    }
    public int getTipoPessoa() {
        return this.tipoPessoa;
    }
    
    public void setTipoPessoa(int tipoPessoa) {
        this.tipoPessoa = tipoPessoa;
    }
    public String getNumProcesso() {
        return this.numProcesso;
    }
    
    public void setNumProcesso(String numProcesso) {
        this.numProcesso = numProcesso;
    }
    public Character getDesertar() {
        return this.desertar;
    }
    
    public void setDesertar(Character desertar) {
        this.desertar = desertar;
    }
    public Date getDtParecerJur() {
        return this.dtParecerJur;
    }
    
    public void setDtParecerJur(Date dtParecerJur) {
        this.dtParecerJur = dtParecerJur;
    }
    public Date getDtParecerCpl() {
        return this.dtParecerCpl;
    }
    
    public void setDtParecerCpl(Date dtParecerCpl) {
        this.dtParecerCpl = dtParecerCpl;
    }
    public String getUsaSrp() {
        return this.usaSrp;
    }
    
    public void setUsaSrp(String usaSrp) {
        this.usaSrp = usaSrp;
    }
    public String getExcluirRel() {
        return this.excluirRel;
    }
    
    public void setExcluirRel(String excluirRel) {
        this.excluirRel = excluirRel;
    }
    public String getRegimeExec() {
        return this.regimeExec;
    }
    
    public void setRegimeExec(String regimeExec) {
        this.regimeExec = regimeExec;
    }
    public String getChkAplic() {
        return this.chkAplic;
    }
    
    public void setChkAplic(String chkAplic) {
        this.chkAplic = chkAplic;
    }
    public Character getLiberarProposta() {
        return this.liberarProposta;
    }
    
    public void setLiberarProposta(Character liberarProposta) {
        this.liberarProposta = liberarProposta;
    }
    public String getPlicNomearqpdf() {
        return this.plicNomearqpdf;
    }
    
    public void setPlicNomearqpdf(String plicNomearqpdf) {
        this.plicNomearqpdf = plicNomearqpdf;
    }
    public String getUtilizaLeiCompl() {
        return this.utilizaLeiCompl;
    }
    
    public void setUtilizaLeiCompl(String utilizaLeiCompl) {
        this.utilizaLeiCompl = utilizaLeiCompl;
    }
    public String getPlicParamicroempresa() {
        return this.plicParamicroempresa;
    }
    
    public void setPlicParamicroempresa(String plicParamicroempresa) {
        this.plicParamicroempresa = plicParamicroempresa;
    }
    public Integer getTipoValor() {
        return this.tipoValor;
    }
    
    public void setTipoValor(Integer tipoValor) {
        this.tipoValor = tipoValor;
    }
    public Integer getTpMaterialTce() {
        return this.tpMaterialTce;
    }
    
    public void setTpMaterialTce(Integer tpMaterialTce) {
        this.tpMaterialTce = tpMaterialTce;
    }
    public Character getRemume() {
        return this.remume;
    }
    
    public void setRemume(Character remume) {
        this.remume = remume;
    }
    public Set getCpSelecaos() {
        return this.cpSelecaos;
    }
    
    public void setCpSelecaos(Set cpSelecaos) {
        this.cpSelecaos = cpSelecaos;
    }
    public Set getCpSolMats() {
        return this.cpSolMats;
    }
    
    public void setCpSolMats(Set cpSolMats) {
        this.cpSolMats = cpSolMats;
    }
    public Set getEsRecebimentos() {
        return this.esRecebimentos;
    }
    
    public void setEsRecebimentos(Set esRecebimentos) {
        this.esRecebimentos = esRecebimentos;
    }
    public Set getCpProtocolos() {
        return this.cpProtocolos;
    }
    
    public void setCpProtocolos(Set cpProtocolos) {
        this.cpProtocolos = cpProtocolos;
    }
    public Set getCpItems() {
        return this.cpItems;
    }
    
    public void setCpItems(Set cpItems) {
        this.cpItems = cpItems;
    }
    public Set getCpRequisis() {
        return this.cpRequisis;
    }
    
    public void setCpRequisis(Set cpRequisis) {
        this.cpRequisis = cpRequisis;
    }
    public Set getCpSolicitacaos() {
        return this.cpSolicitacaos;
    }
    
    public void setCpSolicitacaos(Set cpSolicitacaos) {
        this.cpSolicitacaos = cpSolicitacaos;
    }
    public Set getEsAplicacaoDiretas() {
        return this.esAplicacaoDiretas;
    }
    
    public void setEsAplicacaoDiretas(Set esAplicacaoDiretas) {
        this.esAplicacaoDiretas = esAplicacaoDiretas;
    }




}


