package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CpDepartamento generated by hbm2java
 */
public class CpDepartamento  implements java.io.Serializable {


     private CpDepartamentoId id;
     private String departamento;
     private Integer departamentoExt;
     private long srRecno;
     private Date gacesso;
     private Set cpSolicitacaos = new HashSet(0);

    public CpDepartamento() {
    }

	
    public CpDepartamento(CpDepartamentoId id, String departamento, long srRecno) {
        this.id = id;
        this.departamento = departamento;
        this.srRecno = srRecno;
    }
    public CpDepartamento(CpDepartamentoId id, String departamento, Integer departamentoExt, long srRecno, Date gacesso, Set cpSolicitacaos) {
       this.id = id;
       this.departamento = departamento;
       this.departamentoExt = departamentoExt;
       this.srRecno = srRecno;
       this.gacesso = gacesso;
       this.cpSolicitacaos = cpSolicitacaos;
    }
   
    public CpDepartamentoId getId() {
        return this.id;
    }
    
    public void setId(CpDepartamentoId id) {
        this.id = id;
    }
    public String getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(String departamento) {
        this.departamento = departamento;
    }
    public Integer getDepartamentoExt() {
        return this.departamentoExt;
    }
    
    public void setDepartamentoExt(Integer departamentoExt) {
        this.departamentoExt = departamentoExt;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }
    public Date getGacesso() {
        return this.gacesso;
    }
    
    public void setGacesso(Date gacesso) {
        this.gacesso = gacesso;
    }
    public Set getCpSolicitacaos() {
        return this.cpSolicitacaos;
    }
    
    public void setCpSolicitacaos(Set cpSolicitacaos) {
        this.cpSolicitacaos = cpSolicitacaos;
    }




}


