package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CpItem generated by hbm2java
 */
public class CpItem  implements java.io.Serializable {


     private CpItemId id;
     private CpCompra cpCompra;
     private CpDespesa cpDespesa;
     private CpMaterial cpMaterial;
     private CpMaterialNatDesp cpMaterialNatDesp;
     private CpMedida cpMedida;
     private CpSolicitacaoItem cpSolicitacaoItem;
     private OrNatDesp orNatDesp;
     private Character situacao;
     private String codigos;
     private String codigod;
     private String codigoe;
     private String unid;
     private String vencedor;
     private String material;
     private BigDecimal valEsti;
     private BigDecimal ultlinesp;
     private BigDecimal quant;
     private BigDecimal quantPed;
     private BigDecimal prTotal;
     private BigDecimal prUnit;
     private BigDecimal limTotal;
     private BigDecimal limUnit;
     private String atividade;
     private long srRecno;
     private Date gacesso;
     private char verSldQtd;
     private Integer itemGrp;
     private Date dtCancelado;
     private String receitaId;
     private String projAtivId;
     private String desertoSn;
     private String fracassadoSn;
     private String motFracasso;
     private Integer codigoTec;
     private byte[] descricaoTec;
     private String secretariaId;
     private Integer solicitacaoId;
     private Set cpConcorrencias = new HashSet(0);

    public CpItem() {
    }

	
    public CpItem(CpItemId id, CpCompra cpCompra, CpDespesa cpDespesa, BigDecimal quant, BigDecimal quantPed, BigDecimal prTotal, BigDecimal prUnit, BigDecimal limTotal, BigDecimal limUnit, long srRecno, char verSldQtd, String desertoSn, String fracassadoSn) {
        this.id = id;
        this.cpCompra = cpCompra;
        this.cpDespesa = cpDespesa;
        this.quant = quant;
        this.quantPed = quantPed;
        this.prTotal = prTotal;
        this.prUnit = prUnit;
        this.limTotal = limTotal;
        this.limUnit = limUnit;
        this.srRecno = srRecno;
        this.verSldQtd = verSldQtd;
        this.desertoSn = desertoSn;
        this.fracassadoSn = fracassadoSn;
    }
    public CpItem(CpItemId id, CpCompra cpCompra, CpDespesa cpDespesa, CpMaterial cpMaterial, CpMaterialNatDesp cpMaterialNatDesp, CpMedida cpMedida, CpSolicitacaoItem cpSolicitacaoItem, OrNatDesp orNatDesp, Character situacao, String codigos, String codigod, String codigoe, String unid, String vencedor, String material, BigDecimal valEsti, BigDecimal ultlinesp, BigDecimal quant, BigDecimal quantPed, BigDecimal prTotal, BigDecimal prUnit, BigDecimal limTotal, BigDecimal limUnit, String atividade, long srRecno, Date gacesso, char verSldQtd, Integer itemGrp, Date dtCancelado, String receitaId, String projAtivId, String desertoSn, String fracassadoSn, String motFracasso, Integer codigoTec, byte[] descricaoTec, String secretariaId, Integer solicitacaoId, Set cpConcorrencias) {
       this.id = id;
       this.cpCompra = cpCompra;
       this.cpDespesa = cpDespesa;
       this.cpMaterial = cpMaterial;
       this.cpMaterialNatDesp = cpMaterialNatDesp;
       this.cpMedida = cpMedida;
       this.cpSolicitacaoItem = cpSolicitacaoItem;
       this.orNatDesp = orNatDesp;
       this.situacao = situacao;
       this.codigos = codigos;
       this.codigod = codigod;
       this.codigoe = codigoe;
       this.unid = unid;
       this.vencedor = vencedor;
       this.material = material;
       this.valEsti = valEsti;
       this.ultlinesp = ultlinesp;
       this.quant = quant;
       this.quantPed = quantPed;
       this.prTotal = prTotal;
       this.prUnit = prUnit;
       this.limTotal = limTotal;
       this.limUnit = limUnit;
       this.atividade = atividade;
       this.srRecno = srRecno;
       this.gacesso = gacesso;
       this.verSldQtd = verSldQtd;
       this.itemGrp = itemGrp;
       this.dtCancelado = dtCancelado;
       this.receitaId = receitaId;
       this.projAtivId = projAtivId;
       this.desertoSn = desertoSn;
       this.fracassadoSn = fracassadoSn;
       this.motFracasso = motFracasso;
       this.codigoTec = codigoTec;
       this.descricaoTec = descricaoTec;
       this.secretariaId = secretariaId;
       this.solicitacaoId = solicitacaoId;
       this.cpConcorrencias = cpConcorrencias;
    }
   
    public CpItemId getId() {
        return this.id;
    }
    
    public void setId(CpItemId id) {
        this.id = id;
    }
    public CpCompra getCpCompra() {
        return this.cpCompra;
    }
    
    public void setCpCompra(CpCompra cpCompra) {
        this.cpCompra = cpCompra;
    }
    public CpDespesa getCpDespesa() {
        return this.cpDespesa;
    }
    
    public void setCpDespesa(CpDespesa cpDespesa) {
        this.cpDespesa = cpDespesa;
    }
    public CpMaterial getCpMaterial() {
        return this.cpMaterial;
    }
    
    public void setCpMaterial(CpMaterial cpMaterial) {
        this.cpMaterial = cpMaterial;
    }
    public CpMaterialNatDesp getCpMaterialNatDesp() {
        return this.cpMaterialNatDesp;
    }
    
    public void setCpMaterialNatDesp(CpMaterialNatDesp cpMaterialNatDesp) {
        this.cpMaterialNatDesp = cpMaterialNatDesp;
    }
    public CpMedida getCpMedida() {
        return this.cpMedida;
    }
    
    public void setCpMedida(CpMedida cpMedida) {
        this.cpMedida = cpMedida;
    }
    public CpSolicitacaoItem getCpSolicitacaoItem() {
        return this.cpSolicitacaoItem;
    }
    
    public void setCpSolicitacaoItem(CpSolicitacaoItem cpSolicitacaoItem) {
        this.cpSolicitacaoItem = cpSolicitacaoItem;
    }
    public OrNatDesp getOrNatDesp() {
        return this.orNatDesp;
    }
    
    public void setOrNatDesp(OrNatDesp orNatDesp) {
        this.orNatDesp = orNatDesp;
    }
    public Character getSituacao() {
        return this.situacao;
    }
    
    public void setSituacao(Character situacao) {
        this.situacao = situacao;
    }
    public String getCodigos() {
        return this.codigos;
    }
    
    public void setCodigos(String codigos) {
        this.codigos = codigos;
    }
    public String getCodigod() {
        return this.codigod;
    }
    
    public void setCodigod(String codigod) {
        this.codigod = codigod;
    }
    public String getCodigoe() {
        return this.codigoe;
    }
    
    public void setCodigoe(String codigoe) {
        this.codigoe = codigoe;
    }
    public String getUnid() {
        return this.unid;
    }
    
    public void setUnid(String unid) {
        this.unid = unid;
    }
    public String getVencedor() {
        return this.vencedor;
    }
    
    public void setVencedor(String vencedor) {
        this.vencedor = vencedor;
    }
    public String getMaterial() {
        return this.material;
    }
    
    public void setMaterial(String material) {
        this.material = material;
    }
    public BigDecimal getValEsti() {
        return this.valEsti;
    }
    
    public void setValEsti(BigDecimal valEsti) {
        this.valEsti = valEsti;
    }
    public BigDecimal getUltlinesp() {
        return this.ultlinesp;
    }
    
    public void setUltlinesp(BigDecimal ultlinesp) {
        this.ultlinesp = ultlinesp;
    }
    public BigDecimal getQuant() {
        return this.quant;
    }
    
    public void setQuant(BigDecimal quant) {
        this.quant = quant;
    }
    public BigDecimal getQuantPed() {
        return this.quantPed;
    }
    
    public void setQuantPed(BigDecimal quantPed) {
        this.quantPed = quantPed;
    }
    public BigDecimal getPrTotal() {
        return this.prTotal;
    }
    
    public void setPrTotal(BigDecimal prTotal) {
        this.prTotal = prTotal;
    }
    public BigDecimal getPrUnit() {
        return this.prUnit;
    }
    
    public void setPrUnit(BigDecimal prUnit) {
        this.prUnit = prUnit;
    }
    public BigDecimal getLimTotal() {
        return this.limTotal;
    }
    
    public void setLimTotal(BigDecimal limTotal) {
        this.limTotal = limTotal;
    }
    public BigDecimal getLimUnit() {
        return this.limUnit;
    }
    
    public void setLimUnit(BigDecimal limUnit) {
        this.limUnit = limUnit;
    }
    public String getAtividade() {
        return this.atividade;
    }
    
    public void setAtividade(String atividade) {
        this.atividade = atividade;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }
    public Date getGacesso() {
        return this.gacesso;
    }
    
    public void setGacesso(Date gacesso) {
        this.gacesso = gacesso;
    }
    public char getVerSldQtd() {
        return this.verSldQtd;
    }
    
    public void setVerSldQtd(char verSldQtd) {
        this.verSldQtd = verSldQtd;
    }
    public Integer getItemGrp() {
        return this.itemGrp;
    }
    
    public void setItemGrp(Integer itemGrp) {
        this.itemGrp = itemGrp;
    }
    public Date getDtCancelado() {
        return this.dtCancelado;
    }
    
    public void setDtCancelado(Date dtCancelado) {
        this.dtCancelado = dtCancelado;
    }
    public String getReceitaId() {
        return this.receitaId;
    }
    
    public void setReceitaId(String receitaId) {
        this.receitaId = receitaId;
    }
    public String getProjAtivId() {
        return this.projAtivId;
    }
    
    public void setProjAtivId(String projAtivId) {
        this.projAtivId = projAtivId;
    }
    public String getDesertoSn() {
        return this.desertoSn;
    }
    
    public void setDesertoSn(String desertoSn) {
        this.desertoSn = desertoSn;
    }
    public String getFracassadoSn() {
        return this.fracassadoSn;
    }
    
    public void setFracassadoSn(String fracassadoSn) {
        this.fracassadoSn = fracassadoSn;
    }
    public String getMotFracasso() {
        return this.motFracasso;
    }
    
    public void setMotFracasso(String motFracasso) {
        this.motFracasso = motFracasso;
    }
    public Integer getCodigoTec() {
        return this.codigoTec;
    }
    
    public void setCodigoTec(Integer codigoTec) {
        this.codigoTec = codigoTec;
    }
    public byte[] getDescricaoTec() {
        return this.descricaoTec;
    }
    
    public void setDescricaoTec(byte[] descricaoTec) {
        this.descricaoTec = descricaoTec;
    }
    public String getSecretariaId() {
        return this.secretariaId;
    }
    
    public void setSecretariaId(String secretariaId) {
        this.secretariaId = secretariaId;
    }
    public Integer getSolicitacaoId() {
        return this.solicitacaoId;
    }
    
    public void setSolicitacaoId(Integer solicitacaoId) {
        this.solicitacaoId = solicitacaoId;
    }
    public Set getCpConcorrencias() {
        return this.cpConcorrencias;
    }
    
    public void setCpConcorrencias(Set cpConcorrencias) {
        this.cpConcorrencias = cpConcorrencias;
    }




}


