package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CpLocalEntrega generated by hbm2java
 */
public class CpLocalEntrega  implements java.io.Serializable {


     private int localEntregaId;
     private String descricao;
     private long srRecno;
     private Set cpRequisis = new HashSet(0);
     private Set cpSolicitacaos = new HashSet(0);

    public CpLocalEntrega() {
    }

	
    public CpLocalEntrega(int localEntregaId, String descricao, long srRecno) {
        this.localEntregaId = localEntregaId;
        this.descricao = descricao;
        this.srRecno = srRecno;
    }
    public CpLocalEntrega(int localEntregaId, String descricao, long srRecno, Set cpRequisis, Set cpSolicitacaos) {
       this.localEntregaId = localEntregaId;
       this.descricao = descricao;
       this.srRecno = srRecno;
       this.cpRequisis = cpRequisis;
       this.cpSolicitacaos = cpSolicitacaos;
    }
   
    public int getLocalEntregaId() {
        return this.localEntregaId;
    }
    
    public void setLocalEntregaId(int localEntregaId) {
        this.localEntregaId = localEntregaId;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }
    public Set getCpRequisis() {
        return this.cpRequisis;
    }
    
    public void setCpRequisis(Set cpRequisis) {
        this.cpRequisis = cpRequisis;
    }
    public Set getCpSolicitacaos() {
        return this.cpSolicitacaos;
    }
    
    public void setCpSolicitacaos(Set cpSolicitacaos) {
        this.cpSolicitacaos = cpSolicitacaos;
    }




}


