package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CpMaterial generated by hbm2java
 */
public class CpMaterial  implements java.io.Serializable {


     private int codigo;
     private CpCategoria cpCategoria;
     private CpGrupo cpGrupo;
     private CpMedida cpMedida;
     private CpSubgrupo cpSubgrupo;
     private CpTipoProduto cpTipoProduto;
     private EsLocalizacao esLocalizacao;
     private OrNatDesp orNatDesp;
     private TceMtDesdobramento tceMtDesdobramento;
     private TceMtElemento tceMtElemento;
     private TceMtSubelemento tceMtSubelemento;
     private String nome;
     private String nomeAux;
     private char tipo;
     private Integer codigoExt;
     private long srRecno;
     private Date gacesso;
     private String referencia;
     private Date cadastro;
     private String obs;
     private Integer codAuxiliar;
     private String localizacao;
     private String codBarras;
     private String desativado;
     private String gusuarioId;
     private String nomeAnterior;
     private Character controlaLote;
     private String codigoTce;
     private Character importadoTce;
     private Integer tpMaterialTce;
     private Character remume;
     private Set esRetiradaItems = new HashSet(0);
     private Set cpItems = new HashSet(0);
     private Set esAplicacaoDiretaItems = new HashSet(0);
     private Set esRecebimentoItems = new HashSet(0);
     private Set cpSolicitacaoItems = new HashSet(0);
     private Set esRequisicaoItems = new HashSet(0);
     private Set esLoteRemedios = new HashSet(0);
     private Set lcCombDisps = new HashSet(0);
     private Set cpPedidoItems = new HashSet(0);
     private Set esInventarioItems = new HashSet(0);
     private Set esLoteRemedioBxes = new HashSet(0);
     private Set esMaterialEstocados = new HashSet(0);
     private Set cpSoItenses = new HashSet(0);
     private Set cpRqItenses = new HashSet(0);
     private Set cpMaterialNatDesps = new HashSet(0);

    public CpMaterial() {
    }

	
    public CpMaterial(int codigo, String nomeAux, char tipo, long srRecno) {
        this.codigo = codigo;
        this.nomeAux = nomeAux;
        this.tipo = tipo;
        this.srRecno = srRecno;
    }
    public CpMaterial(int codigo, CpCategoria cpCategoria, CpGrupo cpGrupo, CpMedida cpMedida, CpSubgrupo cpSubgrupo, CpTipoProduto cpTipoProduto, EsLocalizacao esLocalizacao, OrNatDesp orNatDesp, TceMtDesdobramento tceMtDesdobramento, TceMtElemento tceMtElemento, TceMtSubelemento tceMtSubelemento, String nome, String nomeAux, char tipo, Integer codigoExt, long srRecno, Date gacesso, String referencia, Date cadastro, String obs, Integer codAuxiliar, String localizacao, String codBarras, String desativado, String gusuarioId, String nomeAnterior, Character controlaLote, String codigoTce, Character importadoTce, Integer tpMaterialTce, Character remume, Set esRetiradaItems, Set cpItems, Set esAplicacaoDiretaItems, Set esRecebimentoItems, Set cpSolicitacaoItems, Set esRequisicaoItems, Set esLoteRemedios, Set lcCombDisps, Set cpPedidoItems, Set esInventarioItems, Set esLoteRemedioBxes, Set esMaterialEstocados, Set cpSoItenses, Set cpRqItenses, Set cpMaterialNatDesps) {
       this.codigo = codigo;
       this.cpCategoria = cpCategoria;
       this.cpGrupo = cpGrupo;
       this.cpMedida = cpMedida;
       this.cpSubgrupo = cpSubgrupo;
       this.cpTipoProduto = cpTipoProduto;
       this.esLocalizacao = esLocalizacao;
       this.orNatDesp = orNatDesp;
       this.tceMtDesdobramento = tceMtDesdobramento;
       this.tceMtElemento = tceMtElemento;
       this.tceMtSubelemento = tceMtSubelemento;
       this.nome = nome;
       this.nomeAux = nomeAux;
       this.tipo = tipo;
       this.codigoExt = codigoExt;
       this.srRecno = srRecno;
       this.gacesso = gacesso;
       this.referencia = referencia;
       this.cadastro = cadastro;
       this.obs = obs;
       this.codAuxiliar = codAuxiliar;
       this.localizacao = localizacao;
       this.codBarras = codBarras;
       this.desativado = desativado;
       this.gusuarioId = gusuarioId;
       this.nomeAnterior = nomeAnterior;
       this.controlaLote = controlaLote;
       this.codigoTce = codigoTce;
       this.importadoTce = importadoTce;
       this.tpMaterialTce = tpMaterialTce;
       this.remume = remume;
       this.esRetiradaItems = esRetiradaItems;
       this.cpItems = cpItems;
       this.esAplicacaoDiretaItems = esAplicacaoDiretaItems;
       this.esRecebimentoItems = esRecebimentoItems;
       this.cpSolicitacaoItems = cpSolicitacaoItems;
       this.esRequisicaoItems = esRequisicaoItems;
       this.esLoteRemedios = esLoteRemedios;
       this.lcCombDisps = lcCombDisps;
       this.cpPedidoItems = cpPedidoItems;
       this.esInventarioItems = esInventarioItems;
       this.esLoteRemedioBxes = esLoteRemedioBxes;
       this.esMaterialEstocados = esMaterialEstocados;
       this.cpSoItenses = cpSoItenses;
       this.cpRqItenses = cpRqItenses;
       this.cpMaterialNatDesps = cpMaterialNatDesps;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public CpCategoria getCpCategoria() {
        return this.cpCategoria;
    }
    
    public void setCpCategoria(CpCategoria cpCategoria) {
        this.cpCategoria = cpCategoria;
    }
    public CpGrupo getCpGrupo() {
        return this.cpGrupo;
    }
    
    public void setCpGrupo(CpGrupo cpGrupo) {
        this.cpGrupo = cpGrupo;
    }
    public CpMedida getCpMedida() {
        return this.cpMedida;
    }
    
    public void setCpMedida(CpMedida cpMedida) {
        this.cpMedida = cpMedida;
    }
    public CpSubgrupo getCpSubgrupo() {
        return this.cpSubgrupo;
    }
    
    public void setCpSubgrupo(CpSubgrupo cpSubgrupo) {
        this.cpSubgrupo = cpSubgrupo;
    }
    public CpTipoProduto getCpTipoProduto() {
        return this.cpTipoProduto;
    }
    
    public void setCpTipoProduto(CpTipoProduto cpTipoProduto) {
        this.cpTipoProduto = cpTipoProduto;
    }
    public EsLocalizacao getEsLocalizacao() {
        return this.esLocalizacao;
    }
    
    public void setEsLocalizacao(EsLocalizacao esLocalizacao) {
        this.esLocalizacao = esLocalizacao;
    }
    public OrNatDesp getOrNatDesp() {
        return this.orNatDesp;
    }
    
    public void setOrNatDesp(OrNatDesp orNatDesp) {
        this.orNatDesp = orNatDesp;
    }
    public TceMtDesdobramento getTceMtDesdobramento() {
        return this.tceMtDesdobramento;
    }
    
    public void setTceMtDesdobramento(TceMtDesdobramento tceMtDesdobramento) {
        this.tceMtDesdobramento = tceMtDesdobramento;
    }
    public TceMtElemento getTceMtElemento() {
        return this.tceMtElemento;
    }
    
    public void setTceMtElemento(TceMtElemento tceMtElemento) {
        this.tceMtElemento = tceMtElemento;
    }
    public TceMtSubelemento getTceMtSubelemento() {
        return this.tceMtSubelemento;
    }
    
    public void setTceMtSubelemento(TceMtSubelemento tceMtSubelemento) {
        this.tceMtSubelemento = tceMtSubelemento;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getNomeAux() {
        return this.nomeAux;
    }
    
    public void setNomeAux(String nomeAux) {
        this.nomeAux = nomeAux;
    }
    public char getTipo() {
        return this.tipo;
    }
    
    public void setTipo(char tipo) {
        this.tipo = tipo;
    }
    public Integer getCodigoExt() {
        return this.codigoExt;
    }
    
    public void setCodigoExt(Integer codigoExt) {
        this.codigoExt = codigoExt;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }
    public Date getGacesso() {
        return this.gacesso;
    }
    
    public void setGacesso(Date gacesso) {
        this.gacesso = gacesso;
    }
    public String getReferencia() {
        return this.referencia;
    }
    
    public void setReferencia(String referencia) {
        this.referencia = referencia;
    }
    public Date getCadastro() {
        return this.cadastro;
    }
    
    public void setCadastro(Date cadastro) {
        this.cadastro = cadastro;
    }
    public String getObs() {
        return this.obs;
    }
    
    public void setObs(String obs) {
        this.obs = obs;
    }
    public Integer getCodAuxiliar() {
        return this.codAuxiliar;
    }
    
    public void setCodAuxiliar(Integer codAuxiliar) {
        this.codAuxiliar = codAuxiliar;
    }
    public String getLocalizacao() {
        return this.localizacao;
    }
    
    public void setLocalizacao(String localizacao) {
        this.localizacao = localizacao;
    }
    public String getCodBarras() {
        return this.codBarras;
    }
    
    public void setCodBarras(String codBarras) {
        this.codBarras = codBarras;
    }
    public String getDesativado() {
        return this.desativado;
    }
    
    public void setDesativado(String desativado) {
        this.desativado = desativado;
    }
    public String getGusuarioId() {
        return this.gusuarioId;
    }
    
    public void setGusuarioId(String gusuarioId) {
        this.gusuarioId = gusuarioId;
    }
    public String getNomeAnterior() {
        return this.nomeAnterior;
    }
    
    public void setNomeAnterior(String nomeAnterior) {
        this.nomeAnterior = nomeAnterior;
    }
    public Character getControlaLote() {
        return this.controlaLote;
    }
    
    public void setControlaLote(Character controlaLote) {
        this.controlaLote = controlaLote;
    }
    public String getCodigoTce() {
        return this.codigoTce;
    }
    
    public void setCodigoTce(String codigoTce) {
        this.codigoTce = codigoTce;
    }
    public Character getImportadoTce() {
        return this.importadoTce;
    }
    
    public void setImportadoTce(Character importadoTce) {
        this.importadoTce = importadoTce;
    }
    public Integer getTpMaterialTce() {
        return this.tpMaterialTce;
    }
    
    public void setTpMaterialTce(Integer tpMaterialTce) {
        this.tpMaterialTce = tpMaterialTce;
    }
    public Character getRemume() {
        return this.remume;
    }
    
    public void setRemume(Character remume) {
        this.remume = remume;
    }
    public Set getEsRetiradaItems() {
        return this.esRetiradaItems;
    }
    
    public void setEsRetiradaItems(Set esRetiradaItems) {
        this.esRetiradaItems = esRetiradaItems;
    }
    public Set getCpItems() {
        return this.cpItems;
    }
    
    public void setCpItems(Set cpItems) {
        this.cpItems = cpItems;
    }
    public Set getEsAplicacaoDiretaItems() {
        return this.esAplicacaoDiretaItems;
    }
    
    public void setEsAplicacaoDiretaItems(Set esAplicacaoDiretaItems) {
        this.esAplicacaoDiretaItems = esAplicacaoDiretaItems;
    }
    public Set getEsRecebimentoItems() {
        return this.esRecebimentoItems;
    }
    
    public void setEsRecebimentoItems(Set esRecebimentoItems) {
        this.esRecebimentoItems = esRecebimentoItems;
    }
    public Set getCpSolicitacaoItems() {
        return this.cpSolicitacaoItems;
    }
    
    public void setCpSolicitacaoItems(Set cpSolicitacaoItems) {
        this.cpSolicitacaoItems = cpSolicitacaoItems;
    }
    public Set getEsRequisicaoItems() {
        return this.esRequisicaoItems;
    }
    
    public void setEsRequisicaoItems(Set esRequisicaoItems) {
        this.esRequisicaoItems = esRequisicaoItems;
    }
    public Set getEsLoteRemedios() {
        return this.esLoteRemedios;
    }
    
    public void setEsLoteRemedios(Set esLoteRemedios) {
        this.esLoteRemedios = esLoteRemedios;
    }
    public Set getLcCombDisps() {
        return this.lcCombDisps;
    }
    
    public void setLcCombDisps(Set lcCombDisps) {
        this.lcCombDisps = lcCombDisps;
    }
    public Set getCpPedidoItems() {
        return this.cpPedidoItems;
    }
    
    public void setCpPedidoItems(Set cpPedidoItems) {
        this.cpPedidoItems = cpPedidoItems;
    }
    public Set getEsInventarioItems() {
        return this.esInventarioItems;
    }
    
    public void setEsInventarioItems(Set esInventarioItems) {
        this.esInventarioItems = esInventarioItems;
    }
    public Set getEsLoteRemedioBxes() {
        return this.esLoteRemedioBxes;
    }
    
    public void setEsLoteRemedioBxes(Set esLoteRemedioBxes) {
        this.esLoteRemedioBxes = esLoteRemedioBxes;
    }
    public Set getEsMaterialEstocados() {
        return this.esMaterialEstocados;
    }
    
    public void setEsMaterialEstocados(Set esMaterialEstocados) {
        this.esMaterialEstocados = esMaterialEstocados;
    }
    public Set getCpSoItenses() {
        return this.cpSoItenses;
    }
    
    public void setCpSoItenses(Set cpSoItenses) {
        this.cpSoItenses = cpSoItenses;
    }
    public Set getCpRqItenses() {
        return this.cpRqItenses;
    }
    
    public void setCpRqItenses(Set cpRqItenses) {
        this.cpRqItenses = cpRqItenses;
    }
    public Set getCpMaterialNatDesps() {
        return this.cpMaterialNatDesps;
    }
    
    public void setCpMaterialNatDesps(Set cpMaterialNatDesps) {
        this.cpMaterialNatDesps = cpMaterialNatDesps;
    }




}


