package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CpMaterialNatDesp generated by hbm2java
 */
public class CpMaterialNatDesp  implements java.io.Serializable {


     private int materialNatDespId;
     private CpMaterial cpMaterial;
     private OrNatDesp orNatDesp;
     private TceMtDesdobramento tceMtDesdobramento;
     private TceMtElemento tceMtElemento;
     private TceMtSubelemento tceMtSubelemento;
     private long srRecno;
     private Set cpItems = new HashSet(0);
     private Set esRecebimentoItems = new HashSet(0);
     private Set cpSoItenses = new HashSet(0);
     private Set cpRqItenses = new HashSet(0);
     private Set esAplicacaoDiretaItems = new HashSet(0);
     private Set cpSolicitacaoItems = new HashSet(0);

    public CpMaterialNatDesp() {
    }

	
    public CpMaterialNatDesp(int materialNatDespId, CpMaterial cpMaterial, OrNatDesp orNatDesp, TceMtDesdobramento tceMtDesdobramento, TceMtElemento tceMtElemento, TceMtSubelemento tceMtSubelemento, long srRecno) {
        this.materialNatDespId = materialNatDespId;
        this.cpMaterial = cpMaterial;
        this.orNatDesp = orNatDesp;
        this.tceMtDesdobramento = tceMtDesdobramento;
        this.tceMtElemento = tceMtElemento;
        this.tceMtSubelemento = tceMtSubelemento;
        this.srRecno = srRecno;
    }
    public CpMaterialNatDesp(int materialNatDespId, CpMaterial cpMaterial, OrNatDesp orNatDesp, TceMtDesdobramento tceMtDesdobramento, TceMtElemento tceMtElemento, TceMtSubelemento tceMtSubelemento, long srRecno, Set cpItems, Set esRecebimentoItems, Set cpSoItenses, Set cpRqItenses, Set esAplicacaoDiretaItems, Set cpSolicitacaoItems) {
       this.materialNatDespId = materialNatDespId;
       this.cpMaterial = cpMaterial;
       this.orNatDesp = orNatDesp;
       this.tceMtDesdobramento = tceMtDesdobramento;
       this.tceMtElemento = tceMtElemento;
       this.tceMtSubelemento = tceMtSubelemento;
       this.srRecno = srRecno;
       this.cpItems = cpItems;
       this.esRecebimentoItems = esRecebimentoItems;
       this.cpSoItenses = cpSoItenses;
       this.cpRqItenses = cpRqItenses;
       this.esAplicacaoDiretaItems = esAplicacaoDiretaItems;
       this.cpSolicitacaoItems = cpSolicitacaoItems;
    }
   
    public int getMaterialNatDespId() {
        return this.materialNatDespId;
    }
    
    public void setMaterialNatDespId(int materialNatDespId) {
        this.materialNatDespId = materialNatDespId;
    }
    public CpMaterial getCpMaterial() {
        return this.cpMaterial;
    }
    
    public void setCpMaterial(CpMaterial cpMaterial) {
        this.cpMaterial = cpMaterial;
    }
    public OrNatDesp getOrNatDesp() {
        return this.orNatDesp;
    }
    
    public void setOrNatDesp(OrNatDesp orNatDesp) {
        this.orNatDesp = orNatDesp;
    }
    public TceMtDesdobramento getTceMtDesdobramento() {
        return this.tceMtDesdobramento;
    }
    
    public void setTceMtDesdobramento(TceMtDesdobramento tceMtDesdobramento) {
        this.tceMtDesdobramento = tceMtDesdobramento;
    }
    public TceMtElemento getTceMtElemento() {
        return this.tceMtElemento;
    }
    
    public void setTceMtElemento(TceMtElemento tceMtElemento) {
        this.tceMtElemento = tceMtElemento;
    }
    public TceMtSubelemento getTceMtSubelemento() {
        return this.tceMtSubelemento;
    }
    
    public void setTceMtSubelemento(TceMtSubelemento tceMtSubelemento) {
        this.tceMtSubelemento = tceMtSubelemento;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }
    public Set getCpItems() {
        return this.cpItems;
    }
    
    public void setCpItems(Set cpItems) {
        this.cpItems = cpItems;
    }
    public Set getEsRecebimentoItems() {
        return this.esRecebimentoItems;
    }
    
    public void setEsRecebimentoItems(Set esRecebimentoItems) {
        this.esRecebimentoItems = esRecebimentoItems;
    }
    public Set getCpSoItenses() {
        return this.cpSoItenses;
    }
    
    public void setCpSoItenses(Set cpSoItenses) {
        this.cpSoItenses = cpSoItenses;
    }
    public Set getCpRqItenses() {
        return this.cpRqItenses;
    }
    
    public void setCpRqItenses(Set cpRqItenses) {
        this.cpRqItenses = cpRqItenses;
    }
    public Set getEsAplicacaoDiretaItems() {
        return this.esAplicacaoDiretaItems;
    }
    
    public void setEsAplicacaoDiretaItems(Set esAplicacaoDiretaItems) {
        this.esAplicacaoDiretaItems = esAplicacaoDiretaItems;
    }
    public Set getCpSolicitacaoItems() {
        return this.cpSolicitacaoItems;
    }
    
    public void setCpSolicitacaoItems(Set cpSolicitacaoItems) {
        this.cpSolicitacaoItems = cpSolicitacaoItems;
    }




}


