package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CpMedidaCidComp generated by hbm2java
 */
public class CpMedidaCidComp  implements java.io.Serializable {


     private int cpMedidaCidCompId;
     private String sigla;
     private String descricao;
     private long srRecno;
     private Set cpMedidas = new HashSet(0);

    public CpMedidaCidComp() {
    }

	
    public CpMedidaCidComp(int cpMedidaCidCompId, String sigla, String descricao, long srRecno) {
        this.cpMedidaCidCompId = cpMedidaCidCompId;
        this.sigla = sigla;
        this.descricao = descricao;
        this.srRecno = srRecno;
    }
    public CpMedidaCidComp(int cpMedidaCidCompId, String sigla, String descricao, long srRecno, Set cpMedidas) {
       this.cpMedidaCidCompId = cpMedidaCidCompId;
       this.sigla = sigla;
       this.descricao = descricao;
       this.srRecno = srRecno;
       this.cpMedidas = cpMedidas;
    }
   
    public int getCpMedidaCidCompId() {
        return this.cpMedidaCidCompId;
    }
    
    public void setCpMedidaCidCompId(int cpMedidaCidCompId) {
        this.cpMedidaCidCompId = cpMedidaCidCompId;
    }
    public String getSigla() {
        return this.sigla;
    }
    
    public void setSigla(String sigla) {
        this.sigla = sigla;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }
    public Set getCpMedidas() {
        return this.cpMedidas;
    }
    
    public void setCpMedidas(Set cpMedidas) {
        this.cpMedidas = cpMedidas;
    }




}


