package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CpMedida generated by hbm2java
 */
public class CpMedida  implements java.io.Serializable {


     private int medidaId;
     private CpMedidaCidComp cpMedidaCidComp;
     private TceMtMedida tceMtMedida;
     private String medida;
     private String reduzido;
     private long srRecno;
     private Character inteiro;
     private Set cpPedidoItems = new HashSet(0);
     private Set esRetiradaItems = new HashSet(0);
     private Set cpMaterials = new HashSet(0);
     private Set esRecebimentoItems = new HashSet(0);
     private Set cpRqItenses = new HashSet(0);
     private Set esAplicacaoDiretaItems = new HashSet(0);
     private Set cpSolicitacaoItems = new HashSet(0);
     private Set cpSoItenses = new HashSet(0);
     private Set esRequisicaoItems = new HashSet(0);
     private Set cpItems = new HashSet(0);

    public CpMedida() {
    }

	
    public CpMedida(int medidaId, TceMtMedida tceMtMedida, String medida, String reduzido, long srRecno) {
        this.medidaId = medidaId;
        this.tceMtMedida = tceMtMedida;
        this.medida = medida;
        this.reduzido = reduzido;
        this.srRecno = srRecno;
    }
    public CpMedida(int medidaId, CpMedidaCidComp cpMedidaCidComp, TceMtMedida tceMtMedida, String medida, String reduzido, long srRecno, Character inteiro, Set cpPedidoItems, Set esRetiradaItems, Set cpMaterials, Set esRecebimentoItems, Set cpRqItenses, Set esAplicacaoDiretaItems, Set cpSolicitacaoItems, Set cpSoItenses, Set esRequisicaoItems, Set cpItems) {
       this.medidaId = medidaId;
       this.cpMedidaCidComp = cpMedidaCidComp;
       this.tceMtMedida = tceMtMedida;
       this.medida = medida;
       this.reduzido = reduzido;
       this.srRecno = srRecno;
       this.inteiro = inteiro;
       this.cpPedidoItems = cpPedidoItems;
       this.esRetiradaItems = esRetiradaItems;
       this.cpMaterials = cpMaterials;
       this.esRecebimentoItems = esRecebimentoItems;
       this.cpRqItenses = cpRqItenses;
       this.esAplicacaoDiretaItems = esAplicacaoDiretaItems;
       this.cpSolicitacaoItems = cpSolicitacaoItems;
       this.cpSoItenses = cpSoItenses;
       this.esRequisicaoItems = esRequisicaoItems;
       this.cpItems = cpItems;
    }
   
    public int getMedidaId() {
        return this.medidaId;
    }
    
    public void setMedidaId(int medidaId) {
        this.medidaId = medidaId;
    }
    public CpMedidaCidComp getCpMedidaCidComp() {
        return this.cpMedidaCidComp;
    }
    
    public void setCpMedidaCidComp(CpMedidaCidComp cpMedidaCidComp) {
        this.cpMedidaCidComp = cpMedidaCidComp;
    }
    public TceMtMedida getTceMtMedida() {
        return this.tceMtMedida;
    }
    
    public void setTceMtMedida(TceMtMedida tceMtMedida) {
        this.tceMtMedida = tceMtMedida;
    }
    public String getMedida() {
        return this.medida;
    }
    
    public void setMedida(String medida) {
        this.medida = medida;
    }
    public String getReduzido() {
        return this.reduzido;
    }
    
    public void setReduzido(String reduzido) {
        this.reduzido = reduzido;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }
    public Character getInteiro() {
        return this.inteiro;
    }
    
    public void setInteiro(Character inteiro) {
        this.inteiro = inteiro;
    }
    public Set getCpPedidoItems() {
        return this.cpPedidoItems;
    }
    
    public void setCpPedidoItems(Set cpPedidoItems) {
        this.cpPedidoItems = cpPedidoItems;
    }
    public Set getEsRetiradaItems() {
        return this.esRetiradaItems;
    }
    
    public void setEsRetiradaItems(Set esRetiradaItems) {
        this.esRetiradaItems = esRetiradaItems;
    }
    public Set getCpMaterials() {
        return this.cpMaterials;
    }
    
    public void setCpMaterials(Set cpMaterials) {
        this.cpMaterials = cpMaterials;
    }
    public Set getEsRecebimentoItems() {
        return this.esRecebimentoItems;
    }
    
    public void setEsRecebimentoItems(Set esRecebimentoItems) {
        this.esRecebimentoItems = esRecebimentoItems;
    }
    public Set getCpRqItenses() {
        return this.cpRqItenses;
    }
    
    public void setCpRqItenses(Set cpRqItenses) {
        this.cpRqItenses = cpRqItenses;
    }
    public Set getEsAplicacaoDiretaItems() {
        return this.esAplicacaoDiretaItems;
    }
    
    public void setEsAplicacaoDiretaItems(Set esAplicacaoDiretaItems) {
        this.esAplicacaoDiretaItems = esAplicacaoDiretaItems;
    }
    public Set getCpSolicitacaoItems() {
        return this.cpSolicitacaoItems;
    }
    
    public void setCpSolicitacaoItems(Set cpSolicitacaoItems) {
        this.cpSolicitacaoItems = cpSolicitacaoItems;
    }
    public Set getCpSoItenses() {
        return this.cpSoItenses;
    }
    
    public void setCpSoItenses(Set cpSoItenses) {
        this.cpSoItenses = cpSoItenses;
    }
    public Set getEsRequisicaoItems() {
        return this.esRequisicaoItems;
    }
    
    public void setEsRequisicaoItems(Set esRequisicaoItems) {
        this.esRequisicaoItems = esRequisicaoItems;
    }
    public Set getCpItems() {
        return this.cpItems;
    }
    
    public void setCpItems(Set cpItems) {
        this.cpItems = cpItems;
    }




}


