package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CpModLicitacao generated by hbm2java
 */
public class CpModLicitacao  implements java.io.Serializable {


     private int modLicitacaoId;
     private String descricao;
     private long srRecno;
     private Date gacesso;
     private Set cpTipoCompras = new HashSet(0);

    public CpModLicitacao() {
    }

	
    public CpModLicitacao(int modLicitacaoId, String descricao, long srRecno) {
        this.modLicitacaoId = modLicitacaoId;
        this.descricao = descricao;
        this.srRecno = srRecno;
    }
    public CpModLicitacao(int modLicitacaoId, String descricao, long srRecno, Date gacesso, Set cpTipoCompras) {
       this.modLicitacaoId = modLicitacaoId;
       this.descricao = descricao;
       this.srRecno = srRecno;
       this.gacesso = gacesso;
       this.cpTipoCompras = cpTipoCompras;
    }
   
    public int getModLicitacaoId() {
        return this.modLicitacaoId;
    }
    
    public void setModLicitacaoId(int modLicitacaoId) {
        this.modLicitacaoId = modLicitacaoId;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }
    public Date getGacesso() {
        return this.gacesso;
    }
    
    public void setGacesso(Date gacesso) {
        this.gacesso = gacesso;
    }
    public Set getCpTipoCompras() {
        return this.cpTipoCompras;
    }
    
    public void setCpTipoCompras(Set cpTipoCompras) {
        this.cpTipoCompras = cpTipoCompras;
    }




}


