package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CpPedido generated by hbm2java
 */
public class CpPedido  implements java.io.Serializable {


     private int pedidoId;
     private CpSecretaria cpSecretaria;
     private Date data;
     private String complemento;
     private BigDecimal valor;
     private int status;
     private long srRecno;
     private Date gacesso;
     private Date datCancel;
     private String motCancel;
     private String usuCancel;
     private Set cpSolicitacaos = new HashSet(0);
     private Set cpPedidoItems = new HashSet(0);

    public CpPedido() {
    }

	
    public CpPedido(int pedidoId, CpSecretaria cpSecretaria, Date data, String complemento, BigDecimal valor, int status, long srRecno) {
        this.pedidoId = pedidoId;
        this.cpSecretaria = cpSecretaria;
        this.data = data;
        this.complemento = complemento;
        this.valor = valor;
        this.status = status;
        this.srRecno = srRecno;
    }
    public CpPedido(int pedidoId, CpSecretaria cpSecretaria, Date data, String complemento, BigDecimal valor, int status, long srRecno, Date gacesso, Date datCancel, String motCancel, String usuCancel, Set cpSolicitacaos, Set cpPedidoItems) {
       this.pedidoId = pedidoId;
       this.cpSecretaria = cpSecretaria;
       this.data = data;
       this.complemento = complemento;
       this.valor = valor;
       this.status = status;
       this.srRecno = srRecno;
       this.gacesso = gacesso;
       this.datCancel = datCancel;
       this.motCancel = motCancel;
       this.usuCancel = usuCancel;
       this.cpSolicitacaos = cpSolicitacaos;
       this.cpPedidoItems = cpPedidoItems;
    }
   
    public int getPedidoId() {
        return this.pedidoId;
    }
    
    public void setPedidoId(int pedidoId) {
        this.pedidoId = pedidoId;
    }
    public CpSecretaria getCpSecretaria() {
        return this.cpSecretaria;
    }
    
    public void setCpSecretaria(CpSecretaria cpSecretaria) {
        this.cpSecretaria = cpSecretaria;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public String getComplemento() {
        return this.complemento;
    }
    
    public void setComplemento(String complemento) {
        this.complemento = complemento;
    }
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }
    public Date getGacesso() {
        return this.gacesso;
    }
    
    public void setGacesso(Date gacesso) {
        this.gacesso = gacesso;
    }
    public Date getDatCancel() {
        return this.datCancel;
    }
    
    public void setDatCancel(Date datCancel) {
        this.datCancel = datCancel;
    }
    public String getMotCancel() {
        return this.motCancel;
    }
    
    public void setMotCancel(String motCancel) {
        this.motCancel = motCancel;
    }
    public String getUsuCancel() {
        return this.usuCancel;
    }
    
    public void setUsuCancel(String usuCancel) {
        this.usuCancel = usuCancel;
    }
    public Set getCpSolicitacaos() {
        return this.cpSolicitacaos;
    }
    
    public void setCpSolicitacaos(Set cpSolicitacaos) {
        this.cpSolicitacaos = cpSolicitacaos;
    }
    public Set getCpPedidoItems() {
        return this.cpPedidoItems;
    }
    
    public void setCpPedidoItems(Set cpPedidoItems) {
        this.cpPedidoItems = cpPedidoItems;
    }




}


