package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CpProtocolo generated by hbm2java
 */
public class CpProtocolo  implements java.io.Serializable {


     private CpProtocoloId id;
     private CpCompra cpCompra;
     private CpTipoCompra cpTipoCompra;
     private char tpProto;
     private int credor;
     private Date data;
     private Date vencto;
     private String compl;
     private BigDecimal valor;
     private String empenho;
     private BigDecimal empenhado;
     private Character situacao;
     private long srRecno;
     private Date gacesso;
     private Set cpSolMatsForFkCpSolMatCpProtocolo2 = new HashSet(0);
     private Set cpSolMatsForFkCpSolMatCpProtocolo1 = new HashSet(0);

    public CpProtocolo() {
    }

	
    public CpProtocolo(CpProtocoloId id, CpTipoCompra cpTipoCompra, char tpProto, int credor, Date data, BigDecimal valor, BigDecimal empenhado, long srRecno) {
        this.id = id;
        this.cpTipoCompra = cpTipoCompra;
        this.tpProto = tpProto;
        this.credor = credor;
        this.data = data;
        this.valor = valor;
        this.empenhado = empenhado;
        this.srRecno = srRecno;
    }
    public CpProtocolo(CpProtocoloId id, CpCompra cpCompra, CpTipoCompra cpTipoCompra, char tpProto, int credor, Date data, Date vencto, String compl, BigDecimal valor, String empenho, BigDecimal empenhado, Character situacao, long srRecno, Date gacesso, Set cpSolMatsForFkCpSolMatCpProtocolo2, Set cpSolMatsForFkCpSolMatCpProtocolo1) {
       this.id = id;
       this.cpCompra = cpCompra;
       this.cpTipoCompra = cpTipoCompra;
       this.tpProto = tpProto;
       this.credor = credor;
       this.data = data;
       this.vencto = vencto;
       this.compl = compl;
       this.valor = valor;
       this.empenho = empenho;
       this.empenhado = empenhado;
       this.situacao = situacao;
       this.srRecno = srRecno;
       this.gacesso = gacesso;
       this.cpSolMatsForFkCpSolMatCpProtocolo2 = cpSolMatsForFkCpSolMatCpProtocolo2;
       this.cpSolMatsForFkCpSolMatCpProtocolo1 = cpSolMatsForFkCpSolMatCpProtocolo1;
    }
   
    public CpProtocoloId getId() {
        return this.id;
    }
    
    public void setId(CpProtocoloId id) {
        this.id = id;
    }
    public CpCompra getCpCompra() {
        return this.cpCompra;
    }
    
    public void setCpCompra(CpCompra cpCompra) {
        this.cpCompra = cpCompra;
    }
    public CpTipoCompra getCpTipoCompra() {
        return this.cpTipoCompra;
    }
    
    public void setCpTipoCompra(CpTipoCompra cpTipoCompra) {
        this.cpTipoCompra = cpTipoCompra;
    }
    public char getTpProto() {
        return this.tpProto;
    }
    
    public void setTpProto(char tpProto) {
        this.tpProto = tpProto;
    }
    public int getCredor() {
        return this.credor;
    }
    
    public void setCredor(int credor) {
        this.credor = credor;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public Date getVencto() {
        return this.vencto;
    }
    
    public void setVencto(Date vencto) {
        this.vencto = vencto;
    }
    public String getCompl() {
        return this.compl;
    }
    
    public void setCompl(String compl) {
        this.compl = compl;
    }
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }
    public String getEmpenho() {
        return this.empenho;
    }
    
    public void setEmpenho(String empenho) {
        this.empenho = empenho;
    }
    public BigDecimal getEmpenhado() {
        return this.empenhado;
    }
    
    public void setEmpenhado(BigDecimal empenhado) {
        this.empenhado = empenhado;
    }
    public Character getSituacao() {
        return this.situacao;
    }
    
    public void setSituacao(Character situacao) {
        this.situacao = situacao;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }
    public Date getGacesso() {
        return this.gacesso;
    }
    
    public void setGacesso(Date gacesso) {
        this.gacesso = gacesso;
    }
    public Set getCpSolMatsForFkCpSolMatCpProtocolo2() {
        return this.cpSolMatsForFkCpSolMatCpProtocolo2;
    }
    
    public void setCpSolMatsForFkCpSolMatCpProtocolo2(Set cpSolMatsForFkCpSolMatCpProtocolo2) {
        this.cpSolMatsForFkCpSolMatCpProtocolo2 = cpSolMatsForFkCpSolMatCpProtocolo2;
    }
    public Set getCpSolMatsForFkCpSolMatCpProtocolo1() {
        return this.cpSolMatsForFkCpSolMatCpProtocolo1;
    }
    
    public void setCpSolMatsForFkCpSolMatCpProtocolo1(Set cpSolMatsForFkCpSolMatCpProtocolo1) {
        this.cpSolMatsForFkCpSolMatCpProtocolo1 = cpSolMatsForFkCpSolMatCpProtocolo1;
    }




}


