package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1



/**
 * CpRequisiId generated by hbm2java
 */
public class CpRequisiId  implements java.io.Serializable {


     private int anoRequisi;
     private int numero;

    public CpRequisiId() {
    }

    public CpRequisiId(int anoRequisi, int numero) {
       this.anoRequisi = anoRequisi;
       this.numero = numero;
    }
   
    public int getAnoRequisi() {
        return this.anoRequisi;
    }
    
    public void setAnoRequisi(int anoRequisi) {
        this.anoRequisi = anoRequisi;
    }
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CpRequisiId) ) return false;
		 CpRequisiId castOther = ( CpRequisiId ) other; 
         
		 return (this.getAnoRequisi()==castOther.getAnoRequisi())
 && (this.getNumero()==castOther.getNumero());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getAnoRequisi();
         result = 37 * result + this.getNumero();
         return result;
   }   


}


