package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1



/**
 * CpRqItensId generated by hbm2java
 */
public class CpRqItensId  implements java.io.Serializable {


     private int anoRequisi;
     private int numero;
     private int item;

    public CpRqItensId() {
    }

    public CpRqItensId(int anoRequisi, int numero, int item) {
       this.anoRequisi = anoRequisi;
       this.numero = numero;
       this.item = item;
    }
   
    public int getAnoRequisi() {
        return this.anoRequisi;
    }
    
    public void setAnoRequisi(int anoRequisi) {
        this.anoRequisi = anoRequisi;
    }
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }
    public int getItem() {
        return this.item;
    }
    
    public void setItem(int item) {
        this.item = item;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CpRqItensId) ) return false;
		 CpRqItensId castOther = ( CpRqItensId ) other; 
         
		 return (this.getAnoRequisi()==castOther.getAnoRequisi())
 && (this.getNumero()==castOther.getNumero())
 && (this.getItem()==castOther.getItem());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getAnoRequisi();
         result = 37 * result + this.getNumero();
         result = 37 * result + this.getItem();
         return result;
   }   


}


