package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CpRqItens generated by hbm2java
 */
public class CpRqItens  implements java.io.Serializable {


     private CpRqItensId id;
     private CpMaterial cpMaterial;
     private CpMaterialNatDesp cpMaterialNatDesp;
     private CpMedida cpMedida;
     private CpRequisi cpRequisi;
     private CpSolicitacaoItem cpSolicitacaoItem;
     private CpSoItens cpSoItens;
     private BigDecimal quant;
     private String unid;
     private String compl;
     private BigDecimal unitEst;
     private BigDecimal totaEst;
     private Character situacao;
     private Integer ganoId;
     private Integer tipoCompraId;
     private Integer compraId;
     private Integer credorId;
     private Integer itemId;
     private Integer termoItemId;
     private long srRecno;
     private Date gacesso;
     private String marca;
     private BigDecimal desconto;
     private Integer caronaItemId;
     private Set esRecebimentoItems = new HashSet(0);

    public CpRqItens() {
    }

	
    public CpRqItens(CpRqItensId id, CpRequisi cpRequisi, BigDecimal quant, BigDecimal unitEst, BigDecimal totaEst, long srRecno) {
        this.id = id;
        this.cpRequisi = cpRequisi;
        this.quant = quant;
        this.unitEst = unitEst;
        this.totaEst = totaEst;
        this.srRecno = srRecno;
    }
    public CpRqItens(CpRqItensId id, CpMaterial cpMaterial, CpMaterialNatDesp cpMaterialNatDesp, CpMedida cpMedida, CpRequisi cpRequisi, CpSolicitacaoItem cpSolicitacaoItem, CpSoItens cpSoItens, BigDecimal quant, String unid, String compl, BigDecimal unitEst, BigDecimal totaEst, Character situacao, Integer ganoId, Integer tipoCompraId, Integer compraId, Integer credorId, Integer itemId, Integer termoItemId, long srRecno, Date gacesso, String marca, BigDecimal desconto, Integer caronaItemId, Set esRecebimentoItems) {
       this.id = id;
       this.cpMaterial = cpMaterial;
       this.cpMaterialNatDesp = cpMaterialNatDesp;
       this.cpMedida = cpMedida;
       this.cpRequisi = cpRequisi;
       this.cpSolicitacaoItem = cpSolicitacaoItem;
       this.cpSoItens = cpSoItens;
       this.quant = quant;
       this.unid = unid;
       this.compl = compl;
       this.unitEst = unitEst;
       this.totaEst = totaEst;
       this.situacao = situacao;
       this.ganoId = ganoId;
       this.tipoCompraId = tipoCompraId;
       this.compraId = compraId;
       this.credorId = credorId;
       this.itemId = itemId;
       this.termoItemId = termoItemId;
       this.srRecno = srRecno;
       this.gacesso = gacesso;
       this.marca = marca;
       this.desconto = desconto;
       this.caronaItemId = caronaItemId;
       this.esRecebimentoItems = esRecebimentoItems;
    }
   
    public CpRqItensId getId() {
        return this.id;
    }
    
    public void setId(CpRqItensId id) {
        this.id = id;
    }
    public CpMaterial getCpMaterial() {
        return this.cpMaterial;
    }
    
    public void setCpMaterial(CpMaterial cpMaterial) {
        this.cpMaterial = cpMaterial;
    }
    public CpMaterialNatDesp getCpMaterialNatDesp() {
        return this.cpMaterialNatDesp;
    }
    
    public void setCpMaterialNatDesp(CpMaterialNatDesp cpMaterialNatDesp) {
        this.cpMaterialNatDesp = cpMaterialNatDesp;
    }
    public CpMedida getCpMedida() {
        return this.cpMedida;
    }
    
    public void setCpMedida(CpMedida cpMedida) {
        this.cpMedida = cpMedida;
    }
    public CpRequisi getCpRequisi() {
        return this.cpRequisi;
    }
    
    public void setCpRequisi(CpRequisi cpRequisi) {
        this.cpRequisi = cpRequisi;
    }
    public CpSolicitacaoItem getCpSolicitacaoItem() {
        return this.cpSolicitacaoItem;
    }
    
    public void setCpSolicitacaoItem(CpSolicitacaoItem cpSolicitacaoItem) {
        this.cpSolicitacaoItem = cpSolicitacaoItem;
    }
    public CpSoItens getCpSoItens() {
        return this.cpSoItens;
    }
    
    public void setCpSoItens(CpSoItens cpSoItens) {
        this.cpSoItens = cpSoItens;
    }
    public BigDecimal getQuant() {
        return this.quant;
    }
    
    public void setQuant(BigDecimal quant) {
        this.quant = quant;
    }
    public String getUnid() {
        return this.unid;
    }
    
    public void setUnid(String unid) {
        this.unid = unid;
    }
    public String getCompl() {
        return this.compl;
    }
    
    public void setCompl(String compl) {
        this.compl = compl;
    }
    public BigDecimal getUnitEst() {
        return this.unitEst;
    }
    
    public void setUnitEst(BigDecimal unitEst) {
        this.unitEst = unitEst;
    }
    public BigDecimal getTotaEst() {
        return this.totaEst;
    }
    
    public void setTotaEst(BigDecimal totaEst) {
        this.totaEst = totaEst;
    }
    public Character getSituacao() {
        return this.situacao;
    }
    
    public void setSituacao(Character situacao) {
        this.situacao = situacao;
    }
    public Integer getGanoId() {
        return this.ganoId;
    }
    
    public void setGanoId(Integer ganoId) {
        this.ganoId = ganoId;
    }
    public Integer getTipoCompraId() {
        return this.tipoCompraId;
    }
    
    public void setTipoCompraId(Integer tipoCompraId) {
        this.tipoCompraId = tipoCompraId;
    }
    public Integer getCompraId() {
        return this.compraId;
    }
    
    public void setCompraId(Integer compraId) {
        this.compraId = compraId;
    }
    public Integer getCredorId() {
        return this.credorId;
    }
    
    public void setCredorId(Integer credorId) {
        this.credorId = credorId;
    }
    public Integer getItemId() {
        return this.itemId;
    }
    
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }
    public Integer getTermoItemId() {
        return this.termoItemId;
    }
    
    public void setTermoItemId(Integer termoItemId) {
        this.termoItemId = termoItemId;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }
    public Date getGacesso() {
        return this.gacesso;
    }
    
    public void setGacesso(Date gacesso) {
        this.gacesso = gacesso;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public BigDecimal getDesconto() {
        return this.desconto;
    }
    
    public void setDesconto(BigDecimal desconto) {
        this.desconto = desconto;
    }
    public Integer getCaronaItemId() {
        return this.caronaItemId;
    }
    
    public void setCaronaItemId(Integer caronaItemId) {
        this.caronaItemId = caronaItemId;
    }
    public Set getEsRecebimentoItems() {
        return this.esRecebimentoItems;
    }
    
    public void setEsRecebimentoItems(Set esRecebimentoItems) {
        this.esRecebimentoItems = esRecebimentoItems;
    }




}


