package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CpSelecao generated by hbm2java
 */
public class CpSelecao  implements java.io.Serializable {


     private CpSelecaoId id;
     private CpCompra cpCompra;
     private CpRepresentante cpRepresentante;
     private char situacao;
     private Character tpPart;
     private String sequencia;
     private String cgcCons;
     private Date data;
     private long srRecno;
     private Date gacesso;
     private String motInabilitar;
     private String representante;
     private Character pcplicHabilitado;
     private String partUtilizaLeiCompl;
     private Set cpConcorrencias = new HashSet(0);

    public CpSelecao() {
    }

	
    public CpSelecao(CpSelecaoId id, CpCompra cpCompra, char situacao, long srRecno, String partUtilizaLeiCompl) {
        this.id = id;
        this.cpCompra = cpCompra;
        this.situacao = situacao;
        this.srRecno = srRecno;
        this.partUtilizaLeiCompl = partUtilizaLeiCompl;
    }
    public CpSelecao(CpSelecaoId id, CpCompra cpCompra, CpRepresentante cpRepresentante, char situacao, Character tpPart, String sequencia, String cgcCons, Date data, long srRecno, Date gacesso, String motInabilitar, String representante, Character pcplicHabilitado, String partUtilizaLeiCompl, Set cpConcorrencias) {
       this.id = id;
       this.cpCompra = cpCompra;
       this.cpRepresentante = cpRepresentante;
       this.situacao = situacao;
       this.tpPart = tpPart;
       this.sequencia = sequencia;
       this.cgcCons = cgcCons;
       this.data = data;
       this.srRecno = srRecno;
       this.gacesso = gacesso;
       this.motInabilitar = motInabilitar;
       this.representante = representante;
       this.pcplicHabilitado = pcplicHabilitado;
       this.partUtilizaLeiCompl = partUtilizaLeiCompl;
       this.cpConcorrencias = cpConcorrencias;
    }
   
    public CpSelecaoId getId() {
        return this.id;
    }
    
    public void setId(CpSelecaoId id) {
        this.id = id;
    }
    public CpCompra getCpCompra() {
        return this.cpCompra;
    }
    
    public void setCpCompra(CpCompra cpCompra) {
        this.cpCompra = cpCompra;
    }
    public CpRepresentante getCpRepresentante() {
        return this.cpRepresentante;
    }
    
    public void setCpRepresentante(CpRepresentante cpRepresentante) {
        this.cpRepresentante = cpRepresentante;
    }
    public char getSituacao() {
        return this.situacao;
    }
    
    public void setSituacao(char situacao) {
        this.situacao = situacao;
    }
    public Character getTpPart() {
        return this.tpPart;
    }
    
    public void setTpPart(Character tpPart) {
        this.tpPart = tpPart;
    }
    public String getSequencia() {
        return this.sequencia;
    }
    
    public void setSequencia(String sequencia) {
        this.sequencia = sequencia;
    }
    public String getCgcCons() {
        return this.cgcCons;
    }
    
    public void setCgcCons(String cgcCons) {
        this.cgcCons = cgcCons;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }
    public Date getGacesso() {
        return this.gacesso;
    }
    
    public void setGacesso(Date gacesso) {
        this.gacesso = gacesso;
    }
    public String getMotInabilitar() {
        return this.motInabilitar;
    }
    
    public void setMotInabilitar(String motInabilitar) {
        this.motInabilitar = motInabilitar;
    }
    public String getRepresentante() {
        return this.representante;
    }
    
    public void setRepresentante(String representante) {
        this.representante = representante;
    }
    public Character getPcplicHabilitado() {
        return this.pcplicHabilitado;
    }
    
    public void setPcplicHabilitado(Character pcplicHabilitado) {
        this.pcplicHabilitado = pcplicHabilitado;
    }
    public String getPartUtilizaLeiCompl() {
        return this.partUtilizaLeiCompl;
    }
    
    public void setPartUtilizaLeiCompl(String partUtilizaLeiCompl) {
        this.partUtilizaLeiCompl = partUtilizaLeiCompl;
    }
    public Set getCpConcorrencias() {
        return this.cpConcorrencias;
    }
    
    public void setCpConcorrencias(Set cpConcorrencias) {
        this.cpConcorrencias = cpConcorrencias;
    }




}


