package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1



/**
 * CpSelecaoId generated by hbm2java
 */
public class CpSelecaoId  implements java.io.Serializable {


     private int ganoId;
     private int tipoCompraId;
     private int compraId;
     private int credorId;

    public CpSelecaoId() {
    }

    public CpSelecaoId(int ganoId, int tipoCompraId, int compraId, int credorId) {
       this.ganoId = ganoId;
       this.tipoCompraId = tipoCompraId;
       this.compraId = compraId;
       this.credorId = credorId;
    }
   
    public int getGanoId() {
        return this.ganoId;
    }
    
    public void setGanoId(int ganoId) {
        this.ganoId = ganoId;
    }
    public int getTipoCompraId() {
        return this.tipoCompraId;
    }
    
    public void setTipoCompraId(int tipoCompraId) {
        this.tipoCompraId = tipoCompraId;
    }
    public int getCompraId() {
        return this.compraId;
    }
    
    public void setCompraId(int compraId) {
        this.compraId = compraId;
    }
    public int getCredorId() {
        return this.credorId;
    }
    
    public void setCredorId(int credorId) {
        this.credorId = credorId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CpSelecaoId) ) return false;
		 CpSelecaoId castOther = ( CpSelecaoId ) other; 
         
		 return (this.getGanoId()==castOther.getGanoId())
 && (this.getTipoCompraId()==castOther.getTipoCompraId())
 && (this.getCompraId()==castOther.getCompraId())
 && (this.getCredorId()==castOther.getCredorId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getGanoId();
         result = 37 * result + this.getTipoCompraId();
         result = 37 * result + this.getCompraId();
         result = 37 * result + this.getCredorId();
         return result;
   }   


}


