package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CpSecretaria generated by hbm2java
 */
public class CpSecretaria  implements java.io.Serializable {


     private String secretariaId;
     private String nome;
     private String localizacao;
     private String endereco;
     private String responsavel;
     private String secretariaExt;
     private long srRecno;
     private String orgaoId;
     private String unidadeId;
     private Date gacesso;
     private String telefone;
     private String secIdExeAnt;
     private Set esLanctosForSecretariaIddestino = new HashSet(0);
     private Set esRetiradas = new HashSet(0);
     private Set cpPedidos = new HashSet(0);
     private Set esInventarioItemDets = new HashSet(0);
     private Set cpSolicitacaos = new HashSet(0);
     private Set esRequisicaos = new HashSet(0);
     private Set frMotoristas = new HashSet(0);
     private Set esMaterialEstocados = new HashSet(0);
     private Set esPlanilhaBordos = new HashSet(0);
     private Set esAvaliacaoItensVeiculos = new HashSet(0);
     private Set cpCconsumos = new HashSet(0);
     private Set esAplicacaoDiretas = new HashSet(0);
     private Set esDepositoSecretarias = new HashSet(0);
     private Set esLanctosForSecretariaIdorigem = new HashSet(0);
     private Set esRecebimentos = new HashSet(0);

    public CpSecretaria() {
    }

	
    public CpSecretaria(String secretariaId, String nome, long srRecno) {
        this.secretariaId = secretariaId;
        this.nome = nome;
        this.srRecno = srRecno;
    }
    public CpSecretaria(String secretariaId, String nome, String localizacao, String endereco, String responsavel, String secretariaExt, long srRecno, String orgaoId, String unidadeId, Date gacesso, String telefone, String secIdExeAnt, Set esLanctosForSecretariaIddestino, Set esRetiradas, Set cpPedidos, Set esInventarioItemDets, Set cpSolicitacaos, Set esRequisicaos, Set frMotoristas, Set esMaterialEstocados, Set esPlanilhaBordos, Set esAvaliacaoItensVeiculos, Set cpCconsumos, Set esAplicacaoDiretas, Set esDepositoSecretarias, Set esLanctosForSecretariaIdorigem, Set esRecebimentos) {
       this.secretariaId = secretariaId;
       this.nome = nome;
       this.localizacao = localizacao;
       this.endereco = endereco;
       this.responsavel = responsavel;
       this.secretariaExt = secretariaExt;
       this.srRecno = srRecno;
       this.orgaoId = orgaoId;
       this.unidadeId = unidadeId;
       this.gacesso = gacesso;
       this.telefone = telefone;
       this.secIdExeAnt = secIdExeAnt;
       this.esLanctosForSecretariaIddestino = esLanctosForSecretariaIddestino;
       this.esRetiradas = esRetiradas;
       this.cpPedidos = cpPedidos;
       this.esInventarioItemDets = esInventarioItemDets;
       this.cpSolicitacaos = cpSolicitacaos;
       this.esRequisicaos = esRequisicaos;
       this.frMotoristas = frMotoristas;
       this.esMaterialEstocados = esMaterialEstocados;
       this.esPlanilhaBordos = esPlanilhaBordos;
       this.esAvaliacaoItensVeiculos = esAvaliacaoItensVeiculos;
       this.cpCconsumos = cpCconsumos;
       this.esAplicacaoDiretas = esAplicacaoDiretas;
       this.esDepositoSecretarias = esDepositoSecretarias;
       this.esLanctosForSecretariaIdorigem = esLanctosForSecretariaIdorigem;
       this.esRecebimentos = esRecebimentos;
    }
   
    public String getSecretariaId() {
        return this.secretariaId;
    }
    
    public void setSecretariaId(String secretariaId) {
        this.secretariaId = secretariaId;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getLocalizacao() {
        return this.localizacao;
    }
    
    public void setLocalizacao(String localizacao) {
        this.localizacao = localizacao;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    public String getResponsavel() {
        return this.responsavel;
    }
    
    public void setResponsavel(String responsavel) {
        this.responsavel = responsavel;
    }
    public String getSecretariaExt() {
        return this.secretariaExt;
    }
    
    public void setSecretariaExt(String secretariaExt) {
        this.secretariaExt = secretariaExt;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }
    public String getOrgaoId() {
        return this.orgaoId;
    }
    
    public void setOrgaoId(String orgaoId) {
        this.orgaoId = orgaoId;
    }
    public String getUnidadeId() {
        return this.unidadeId;
    }
    
    public void setUnidadeId(String unidadeId) {
        this.unidadeId = unidadeId;
    }
    public Date getGacesso() {
        return this.gacesso;
    }
    
    public void setGacesso(Date gacesso) {
        this.gacesso = gacesso;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public String getSecIdExeAnt() {
        return this.secIdExeAnt;
    }
    
    public void setSecIdExeAnt(String secIdExeAnt) {
        this.secIdExeAnt = secIdExeAnt;
    }
    public Set getEsLanctosForSecretariaIddestino() {
        return this.esLanctosForSecretariaIddestino;
    }
    
    public void setEsLanctosForSecretariaIddestino(Set esLanctosForSecretariaIddestino) {
        this.esLanctosForSecretariaIddestino = esLanctosForSecretariaIddestino;
    }
    public Set getEsRetiradas() {
        return this.esRetiradas;
    }
    
    public void setEsRetiradas(Set esRetiradas) {
        this.esRetiradas = esRetiradas;
    }
    public Set getCpPedidos() {
        return this.cpPedidos;
    }
    
    public void setCpPedidos(Set cpPedidos) {
        this.cpPedidos = cpPedidos;
    }
    public Set getEsInventarioItemDets() {
        return this.esInventarioItemDets;
    }
    
    public void setEsInventarioItemDets(Set esInventarioItemDets) {
        this.esInventarioItemDets = esInventarioItemDets;
    }
    public Set getCpSolicitacaos() {
        return this.cpSolicitacaos;
    }
    
    public void setCpSolicitacaos(Set cpSolicitacaos) {
        this.cpSolicitacaos = cpSolicitacaos;
    }
    public Set getEsRequisicaos() {
        return this.esRequisicaos;
    }
    
    public void setEsRequisicaos(Set esRequisicaos) {
        this.esRequisicaos = esRequisicaos;
    }
    public Set getFrMotoristas() {
        return this.frMotoristas;
    }
    
    public void setFrMotoristas(Set frMotoristas) {
        this.frMotoristas = frMotoristas;
    }
    public Set getEsMaterialEstocados() {
        return this.esMaterialEstocados;
    }
    
    public void setEsMaterialEstocados(Set esMaterialEstocados) {
        this.esMaterialEstocados = esMaterialEstocados;
    }
    public Set getEsPlanilhaBordos() {
        return this.esPlanilhaBordos;
    }
    
    public void setEsPlanilhaBordos(Set esPlanilhaBordos) {
        this.esPlanilhaBordos = esPlanilhaBordos;
    }
    public Set getEsAvaliacaoItensVeiculos() {
        return this.esAvaliacaoItensVeiculos;
    }
    
    public void setEsAvaliacaoItensVeiculos(Set esAvaliacaoItensVeiculos) {
        this.esAvaliacaoItensVeiculos = esAvaliacaoItensVeiculos;
    }
    public Set getCpCconsumos() {
        return this.cpCconsumos;
    }
    
    public void setCpCconsumos(Set cpCconsumos) {
        this.cpCconsumos = cpCconsumos;
    }
    public Set getEsAplicacaoDiretas() {
        return this.esAplicacaoDiretas;
    }
    
    public void setEsAplicacaoDiretas(Set esAplicacaoDiretas) {
        this.esAplicacaoDiretas = esAplicacaoDiretas;
    }
    public Set getEsDepositoSecretarias() {
        return this.esDepositoSecretarias;
    }
    
    public void setEsDepositoSecretarias(Set esDepositoSecretarias) {
        this.esDepositoSecretarias = esDepositoSecretarias;
    }
    public Set getEsLanctosForSecretariaIdorigem() {
        return this.esLanctosForSecretariaIdorigem;
    }
    
    public void setEsLanctosForSecretariaIdorigem(Set esLanctosForSecretariaIdorigem) {
        this.esLanctosForSecretariaIdorigem = esLanctosForSecretariaIdorigem;
    }
    public Set getEsRecebimentos() {
        return this.esRecebimentos;
    }
    
    public void setEsRecebimentos(Set esRecebimentos) {
        this.esRecebimentos = esRecebimentos;
    }




}


