package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1



/**
 * CpSolMatId generated by hbm2java
 */
public class CpSolMatId  implements java.io.Serializable {


     private int exercicio;
     private String secretaria;
     private int numero;

    public CpSolMatId() {
    }

    public CpSolMatId(int exercicio, String secretaria, int numero) {
       this.exercicio = exercicio;
       this.secretaria = secretaria;
       this.numero = numero;
    }
   
    public int getExercicio() {
        return this.exercicio;
    }
    
    public void setExercicio(int exercicio) {
        this.exercicio = exercicio;
    }
    public String getSecretaria() {
        return this.secretaria;
    }
    
    public void setSecretaria(String secretaria) {
        this.secretaria = secretaria;
    }
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CpSolMatId) ) return false;
		 CpSolMatId castOther = ( CpSolMatId ) other; 
         
		 return (this.getExercicio()==castOther.getExercicio())
 && ( (this.getSecretaria()==castOther.getSecretaria()) || ( this.getSecretaria()!=null && castOther.getSecretaria()!=null && this.getSecretaria().equals(castOther.getSecretaria()) ) )
 && (this.getNumero()==castOther.getNumero());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getExercicio();
         result = 37 * result + ( getSecretaria() == null ? 0 : this.getSecretaria().hashCode() );
         result = 37 * result + this.getNumero();
         return result;
   }   


}


