package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CpSolicitacaoItem generated by hbm2java
 */
public class CpSolicitacaoItem  implements java.io.Serializable {


     private CpSolicitacaoItemId id;
     private CpConcorrencia cpConcorrencia;
     private CpMaterial cpMaterial;
     private CpMaterialNatDesp cpMaterialNatDesp;
     private CpMedida cpMedida;
     private CpPedidoItem cpPedidoItem;
     private CpSolicitacao cpSolicitacao;
     private BigDecimal quant;
     private BigDecimal quantOk;
     private String unid;
     private String compl;
     private BigDecimal prUnit;
     private BigDecimal prTotal;
     private Character sel;
     private long srRecno;
     private Date gacesso;
     private String marca;
     private BigDecimal desconto;
     private Integer codigoTec;
     private byte[] descricaoTec;
     private Integer concTermoItemId;
     private Integer caronaItemId;
     private Set cpItems = new HashSet(0);
     private Set cpRqItenses = new HashSet(0);

    public CpSolicitacaoItem() {
    }

	
    public CpSolicitacaoItem(CpSolicitacaoItemId id, CpMaterial cpMaterial, CpSolicitacao cpSolicitacao, BigDecimal quant, BigDecimal quantOk, BigDecimal prUnit, BigDecimal prTotal, long srRecno) {
        this.id = id;
        this.cpMaterial = cpMaterial;
        this.cpSolicitacao = cpSolicitacao;
        this.quant = quant;
        this.quantOk = quantOk;
        this.prUnit = prUnit;
        this.prTotal = prTotal;
        this.srRecno = srRecno;
    }
    public CpSolicitacaoItem(CpSolicitacaoItemId id, CpConcorrencia cpConcorrencia, CpMaterial cpMaterial, CpMaterialNatDesp cpMaterialNatDesp, CpMedida cpMedida, CpPedidoItem cpPedidoItem, CpSolicitacao cpSolicitacao, BigDecimal quant, BigDecimal quantOk, String unid, String compl, BigDecimal prUnit, BigDecimal prTotal, Character sel, long srRecno, Date gacesso, String marca, BigDecimal desconto, Integer codigoTec, byte[] descricaoTec, Integer concTermoItemId, Integer caronaItemId, Set cpItems, Set cpRqItenses) {
       this.id = id;
       this.cpConcorrencia = cpConcorrencia;
       this.cpMaterial = cpMaterial;
       this.cpMaterialNatDesp = cpMaterialNatDesp;
       this.cpMedida = cpMedida;
       this.cpPedidoItem = cpPedidoItem;
       this.cpSolicitacao = cpSolicitacao;
       this.quant = quant;
       this.quantOk = quantOk;
       this.unid = unid;
       this.compl = compl;
       this.prUnit = prUnit;
       this.prTotal = prTotal;
       this.sel = sel;
       this.srRecno = srRecno;
       this.gacesso = gacesso;
       this.marca = marca;
       this.desconto = desconto;
       this.codigoTec = codigoTec;
       this.descricaoTec = descricaoTec;
       this.concTermoItemId = concTermoItemId;
       this.caronaItemId = caronaItemId;
       this.cpItems = cpItems;
       this.cpRqItenses = cpRqItenses;
    }
   
    public CpSolicitacaoItemId getId() {
        return this.id;
    }
    
    public void setId(CpSolicitacaoItemId id) {
        this.id = id;
    }
    public CpConcorrencia getCpConcorrencia() {
        return this.cpConcorrencia;
    }
    
    public void setCpConcorrencia(CpConcorrencia cpConcorrencia) {
        this.cpConcorrencia = cpConcorrencia;
    }
    public CpMaterial getCpMaterial() {
        return this.cpMaterial;
    }
    
    public void setCpMaterial(CpMaterial cpMaterial) {
        this.cpMaterial = cpMaterial;
    }
    public CpMaterialNatDesp getCpMaterialNatDesp() {
        return this.cpMaterialNatDesp;
    }
    
    public void setCpMaterialNatDesp(CpMaterialNatDesp cpMaterialNatDesp) {
        this.cpMaterialNatDesp = cpMaterialNatDesp;
    }
    public CpMedida getCpMedida() {
        return this.cpMedida;
    }
    
    public void setCpMedida(CpMedida cpMedida) {
        this.cpMedida = cpMedida;
    }
    public CpPedidoItem getCpPedidoItem() {
        return this.cpPedidoItem;
    }
    
    public void setCpPedidoItem(CpPedidoItem cpPedidoItem) {
        this.cpPedidoItem = cpPedidoItem;
    }
    public CpSolicitacao getCpSolicitacao() {
        return this.cpSolicitacao;
    }
    
    public void setCpSolicitacao(CpSolicitacao cpSolicitacao) {
        this.cpSolicitacao = cpSolicitacao;
    }
    public BigDecimal getQuant() {
        return this.quant;
    }
    
    public void setQuant(BigDecimal quant) {
        this.quant = quant;
    }
    public BigDecimal getQuantOk() {
        return this.quantOk;
    }
    
    public void setQuantOk(BigDecimal quantOk) {
        this.quantOk = quantOk;
    }
    public String getUnid() {
        return this.unid;
    }
    
    public void setUnid(String unid) {
        this.unid = unid;
    }
    public String getCompl() {
        return this.compl;
    }
    
    public void setCompl(String compl) {
        this.compl = compl;
    }
    public BigDecimal getPrUnit() {
        return this.prUnit;
    }
    
    public void setPrUnit(BigDecimal prUnit) {
        this.prUnit = prUnit;
    }
    public BigDecimal getPrTotal() {
        return this.prTotal;
    }
    
    public void setPrTotal(BigDecimal prTotal) {
        this.prTotal = prTotal;
    }
    public Character getSel() {
        return this.sel;
    }
    
    public void setSel(Character sel) {
        this.sel = sel;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }
    public Date getGacesso() {
        return this.gacesso;
    }
    
    public void setGacesso(Date gacesso) {
        this.gacesso = gacesso;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public BigDecimal getDesconto() {
        return this.desconto;
    }
    
    public void setDesconto(BigDecimal desconto) {
        this.desconto = desconto;
    }
    public Integer getCodigoTec() {
        return this.codigoTec;
    }
    
    public void setCodigoTec(Integer codigoTec) {
        this.codigoTec = codigoTec;
    }
    public byte[] getDescricaoTec() {
        return this.descricaoTec;
    }
    
    public void setDescricaoTec(byte[] descricaoTec) {
        this.descricaoTec = descricaoTec;
    }
    public Integer getConcTermoItemId() {
        return this.concTermoItemId;
    }
    
    public void setConcTermoItemId(Integer concTermoItemId) {
        this.concTermoItemId = concTermoItemId;
    }
    public Integer getCaronaItemId() {
        return this.caronaItemId;
    }
    
    public void setCaronaItemId(Integer caronaItemId) {
        this.caronaItemId = caronaItemId;
    }
    public Set getCpItems() {
        return this.cpItems;
    }
    
    public void setCpItems(Set cpItems) {
        this.cpItems = cpItems;
    }
    public Set getCpRqItenses() {
        return this.cpRqItenses;
    }
    
    public void setCpRqItenses(Set cpRqItenses) {
        this.cpRqItenses = cpRqItenses;
    }




}


