package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CpSoItens generated by hbm2java
 */
public class CpSoItens  implements java.io.Serializable {


     private CpSoItensId id;
     private CpConcorrencia cpConcorrencia;
     private CpMaterial cpMaterial;
     private CpMaterialNatDesp cpMaterialNatDesp;
     private CpMedida cpMedida;
     private CpSolMat cpSolMat;
     private BigDecimal quant;
     private String unid;
     private String compl;
     private BigDecimal unitEst;
     private BigDecimal totaEst;
     private BigDecimal prUnit;
     private BigDecimal prTotal;
     private Character situacao;
     private Character tipo;
     private BigDecimal ultlinesp;
     private long srRecno;
     private Date gacesso;
     private Integer caronaItemId;
     private Character adtAgrup;
     private Integer lcBloqueio;
     private Set esAplicacaoDiretaItems = new HashSet(0);
     private Set cpRqItenses = new HashSet(0);
     private Set esRecebimentoItems = new HashSet(0);

    public CpSoItens() {
    }

	
    public CpSoItens(CpSoItensId id, CpSolMat cpSolMat, BigDecimal quant, BigDecimal unitEst, BigDecimal totaEst, BigDecimal prUnit, BigDecimal prTotal, long srRecno) {
        this.id = id;
        this.cpSolMat = cpSolMat;
        this.quant = quant;
        this.unitEst = unitEst;
        this.totaEst = totaEst;
        this.prUnit = prUnit;
        this.prTotal = prTotal;
        this.srRecno = srRecno;
    }
    public CpSoItens(CpSoItensId id, CpConcorrencia cpConcorrencia, CpMaterial cpMaterial, CpMaterialNatDesp cpMaterialNatDesp, CpMedida cpMedida, CpSolMat cpSolMat, BigDecimal quant, String unid, String compl, BigDecimal unitEst, BigDecimal totaEst, BigDecimal prUnit, BigDecimal prTotal, Character situacao, Character tipo, BigDecimal ultlinesp, long srRecno, Date gacesso, Integer caronaItemId, Character adtAgrup, Integer lcBloqueio, Set esAplicacaoDiretaItems, Set cpRqItenses, Set esRecebimentoItems) {
       this.id = id;
       this.cpConcorrencia = cpConcorrencia;
       this.cpMaterial = cpMaterial;
       this.cpMaterialNatDesp = cpMaterialNatDesp;
       this.cpMedida = cpMedida;
       this.cpSolMat = cpSolMat;
       this.quant = quant;
       this.unid = unid;
       this.compl = compl;
       this.unitEst = unitEst;
       this.totaEst = totaEst;
       this.prUnit = prUnit;
       this.prTotal = prTotal;
       this.situacao = situacao;
       this.tipo = tipo;
       this.ultlinesp = ultlinesp;
       this.srRecno = srRecno;
       this.gacesso = gacesso;
       this.caronaItemId = caronaItemId;
       this.adtAgrup = adtAgrup;
       this.lcBloqueio = lcBloqueio;
       this.esAplicacaoDiretaItems = esAplicacaoDiretaItems;
       this.cpRqItenses = cpRqItenses;
       this.esRecebimentoItems = esRecebimentoItems;
    }
   
    public CpSoItensId getId() {
        return this.id;
    }
    
    public void setId(CpSoItensId id) {
        this.id = id;
    }
    public CpConcorrencia getCpConcorrencia() {
        return this.cpConcorrencia;
    }
    
    public void setCpConcorrencia(CpConcorrencia cpConcorrencia) {
        this.cpConcorrencia = cpConcorrencia;
    }
    public CpMaterial getCpMaterial() {
        return this.cpMaterial;
    }
    
    public void setCpMaterial(CpMaterial cpMaterial) {
        this.cpMaterial = cpMaterial;
    }
    public CpMaterialNatDesp getCpMaterialNatDesp() {
        return this.cpMaterialNatDesp;
    }
    
    public void setCpMaterialNatDesp(CpMaterialNatDesp cpMaterialNatDesp) {
        this.cpMaterialNatDesp = cpMaterialNatDesp;
    }
    public CpMedida getCpMedida() {
        return this.cpMedida;
    }
    
    public void setCpMedida(CpMedida cpMedida) {
        this.cpMedida = cpMedida;
    }
    public CpSolMat getCpSolMat() {
        return this.cpSolMat;
    }
    
    public void setCpSolMat(CpSolMat cpSolMat) {
        this.cpSolMat = cpSolMat;
    }
    public BigDecimal getQuant() {
        return this.quant;
    }
    
    public void setQuant(BigDecimal quant) {
        this.quant = quant;
    }
    public String getUnid() {
        return this.unid;
    }
    
    public void setUnid(String unid) {
        this.unid = unid;
    }
    public String getCompl() {
        return this.compl;
    }
    
    public void setCompl(String compl) {
        this.compl = compl;
    }
    public BigDecimal getUnitEst() {
        return this.unitEst;
    }
    
    public void setUnitEst(BigDecimal unitEst) {
        this.unitEst = unitEst;
    }
    public BigDecimal getTotaEst() {
        return this.totaEst;
    }
    
    public void setTotaEst(BigDecimal totaEst) {
        this.totaEst = totaEst;
    }
    public BigDecimal getPrUnit() {
        return this.prUnit;
    }
    
    public void setPrUnit(BigDecimal prUnit) {
        this.prUnit = prUnit;
    }
    public BigDecimal getPrTotal() {
        return this.prTotal;
    }
    
    public void setPrTotal(BigDecimal prTotal) {
        this.prTotal = prTotal;
    }
    public Character getSituacao() {
        return this.situacao;
    }
    
    public void setSituacao(Character situacao) {
        this.situacao = situacao;
    }
    public Character getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Character tipo) {
        this.tipo = tipo;
    }
    public BigDecimal getUltlinesp() {
        return this.ultlinesp;
    }
    
    public void setUltlinesp(BigDecimal ultlinesp) {
        this.ultlinesp = ultlinesp;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }
    public Date getGacesso() {
        return this.gacesso;
    }
    
    public void setGacesso(Date gacesso) {
        this.gacesso = gacesso;
    }
    public Integer getCaronaItemId() {
        return this.caronaItemId;
    }
    
    public void setCaronaItemId(Integer caronaItemId) {
        this.caronaItemId = caronaItemId;
    }
    public Character getAdtAgrup() {
        return this.adtAgrup;
    }
    
    public void setAdtAgrup(Character adtAgrup) {
        this.adtAgrup = adtAgrup;
    }
    public Integer getLcBloqueio() {
        return this.lcBloqueio;
    }
    
    public void setLcBloqueio(Integer lcBloqueio) {
        this.lcBloqueio = lcBloqueio;
    }
    public Set getEsAplicacaoDiretaItems() {
        return this.esAplicacaoDiretaItems;
    }
    
    public void setEsAplicacaoDiretaItems(Set esAplicacaoDiretaItems) {
        this.esAplicacaoDiretaItems = esAplicacaoDiretaItems;
    }
    public Set getCpRqItenses() {
        return this.cpRqItenses;
    }
    
    public void setCpRqItenses(Set cpRqItenses) {
        this.cpRqItenses = cpRqItenses;
    }
    public Set getEsRecebimentoItems() {
        return this.esRecebimentoItems;
    }
    
    public void setEsRecebimentoItems(Set esRecebimentoItems) {
        this.esRecebimentoItems = esRecebimentoItems;
    }




}


