package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CpSolMat generated by hbm2java
 */
public class CpSolMat  implements java.io.Serializable {


     private CpSolMatId id;
     private CpCconsumo cpCconsumo;
     private CpCompra cpCompra;
     private CpProtocolo cpProtocoloByFkCpSolMatCpProtocolo2;
     private CpProtocolo cpProtocoloByFkCpSolMatCpProtocolo1;
     private CpTipoCompra cpTipoCompra;
     private Date data;
     private Integer credor;
     private String complement;
     private BigDecimal matDescon;
     private BigDecimal serDescon;
     private Character situacao;
     private String atividade;
     private String tipoImp;
     private BigDecimal descImp;
     private long srRecno;
     private String atividadeAux;
     private String empenho;
     private String tipResId;
     private String reservaId;
     private String empenhoAut;
     private Date gacesso;
     private Integer empInstrumentocontrato;
     private String contNumero;
     private String gusuarioId;
     private Set esAplicacaoDiretas = new HashSet(0);
     private Set esRecebimentos = new HashSet(0);
     private Set cpRequisis = new HashSet(0);
     private Set cpSoItenses = new HashSet(0);

    public CpSolMat() {
    }

	
    public CpSolMat(CpSolMatId id, CpCconsumo cpCconsumo, BigDecimal descImp, long srRecno) {
        this.id = id;
        this.cpCconsumo = cpCconsumo;
        this.descImp = descImp;
        this.srRecno = srRecno;
    }
    public CpSolMat(CpSolMatId id, CpCconsumo cpCconsumo, CpCompra cpCompra, CpProtocolo cpProtocoloByFkCpSolMatCpProtocolo2, CpProtocolo cpProtocoloByFkCpSolMatCpProtocolo1, CpTipoCompra cpTipoCompra, Date data, Integer credor, String complement, BigDecimal matDescon, BigDecimal serDescon, Character situacao, String atividade, String tipoImp, BigDecimal descImp, long srRecno, String atividadeAux, String empenho, String tipResId, String reservaId, String empenhoAut, Date gacesso, Integer empInstrumentocontrato, String contNumero, String gusuarioId, Set esAplicacaoDiretas, Set esRecebimentos, Set cpRequisis, Set cpSoItenses) {
       this.id = id;
       this.cpCconsumo = cpCconsumo;
       this.cpCompra = cpCompra;
       this.cpProtocoloByFkCpSolMatCpProtocolo2 = cpProtocoloByFkCpSolMatCpProtocolo2;
       this.cpProtocoloByFkCpSolMatCpProtocolo1 = cpProtocoloByFkCpSolMatCpProtocolo1;
       this.cpTipoCompra = cpTipoCompra;
       this.data = data;
       this.credor = credor;
       this.complement = complement;
       this.matDescon = matDescon;
       this.serDescon = serDescon;
       this.situacao = situacao;
       this.atividade = atividade;
       this.tipoImp = tipoImp;
       this.descImp = descImp;
       this.srRecno = srRecno;
       this.atividadeAux = atividadeAux;
       this.empenho = empenho;
       this.tipResId = tipResId;
       this.reservaId = reservaId;
       this.empenhoAut = empenhoAut;
       this.gacesso = gacesso;
       this.empInstrumentocontrato = empInstrumentocontrato;
       this.contNumero = contNumero;
       this.gusuarioId = gusuarioId;
       this.esAplicacaoDiretas = esAplicacaoDiretas;
       this.esRecebimentos = esRecebimentos;
       this.cpRequisis = cpRequisis;
       this.cpSoItenses = cpSoItenses;
    }
   
    public CpSolMatId getId() {
        return this.id;
    }
    
    public void setId(CpSolMatId id) {
        this.id = id;
    }
    public CpCconsumo getCpCconsumo() {
        return this.cpCconsumo;
    }
    
    public void setCpCconsumo(CpCconsumo cpCconsumo) {
        this.cpCconsumo = cpCconsumo;
    }
    public CpCompra getCpCompra() {
        return this.cpCompra;
    }
    
    public void setCpCompra(CpCompra cpCompra) {
        this.cpCompra = cpCompra;
    }
    public CpProtocolo getCpProtocoloByFkCpSolMatCpProtocolo2() {
        return this.cpProtocoloByFkCpSolMatCpProtocolo2;
    }
    
    public void setCpProtocoloByFkCpSolMatCpProtocolo2(CpProtocolo cpProtocoloByFkCpSolMatCpProtocolo2) {
        this.cpProtocoloByFkCpSolMatCpProtocolo2 = cpProtocoloByFkCpSolMatCpProtocolo2;
    }
    public CpProtocolo getCpProtocoloByFkCpSolMatCpProtocolo1() {
        return this.cpProtocoloByFkCpSolMatCpProtocolo1;
    }
    
    public void setCpProtocoloByFkCpSolMatCpProtocolo1(CpProtocolo cpProtocoloByFkCpSolMatCpProtocolo1) {
        this.cpProtocoloByFkCpSolMatCpProtocolo1 = cpProtocoloByFkCpSolMatCpProtocolo1;
    }
    public CpTipoCompra getCpTipoCompra() {
        return this.cpTipoCompra;
    }
    
    public void setCpTipoCompra(CpTipoCompra cpTipoCompra) {
        this.cpTipoCompra = cpTipoCompra;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public Integer getCredor() {
        return this.credor;
    }
    
    public void setCredor(Integer credor) {
        this.credor = credor;
    }
    public String getComplement() {
        return this.complement;
    }
    
    public void setComplement(String complement) {
        this.complement = complement;
    }
    public BigDecimal getMatDescon() {
        return this.matDescon;
    }
    
    public void setMatDescon(BigDecimal matDescon) {
        this.matDescon = matDescon;
    }
    public BigDecimal getSerDescon() {
        return this.serDescon;
    }
    
    public void setSerDescon(BigDecimal serDescon) {
        this.serDescon = serDescon;
    }
    public Character getSituacao() {
        return this.situacao;
    }
    
    public void setSituacao(Character situacao) {
        this.situacao = situacao;
    }
    public String getAtividade() {
        return this.atividade;
    }
    
    public void setAtividade(String atividade) {
        this.atividade = atividade;
    }
    public String getTipoImp() {
        return this.tipoImp;
    }
    
    public void setTipoImp(String tipoImp) {
        this.tipoImp = tipoImp;
    }
    public BigDecimal getDescImp() {
        return this.descImp;
    }
    
    public void setDescImp(BigDecimal descImp) {
        this.descImp = descImp;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }
    public String getAtividadeAux() {
        return this.atividadeAux;
    }
    
    public void setAtividadeAux(String atividadeAux) {
        this.atividadeAux = atividadeAux;
    }
    public String getEmpenho() {
        return this.empenho;
    }
    
    public void setEmpenho(String empenho) {
        this.empenho = empenho;
    }
    public String getTipResId() {
        return this.tipResId;
    }
    
    public void setTipResId(String tipResId) {
        this.tipResId = tipResId;
    }
    public String getReservaId() {
        return this.reservaId;
    }
    
    public void setReservaId(String reservaId) {
        this.reservaId = reservaId;
    }
    public String getEmpenhoAut() {
        return this.empenhoAut;
    }
    
    public void setEmpenhoAut(String empenhoAut) {
        this.empenhoAut = empenhoAut;
    }
    public Date getGacesso() {
        return this.gacesso;
    }
    
    public void setGacesso(Date gacesso) {
        this.gacesso = gacesso;
    }
    public Integer getEmpInstrumentocontrato() {
        return this.empInstrumentocontrato;
    }
    
    public void setEmpInstrumentocontrato(Integer empInstrumentocontrato) {
        this.empInstrumentocontrato = empInstrumentocontrato;
    }
    public String getContNumero() {
        return this.contNumero;
    }
    
    public void setContNumero(String contNumero) {
        this.contNumero = contNumero;
    }
    public String getGusuarioId() {
        return this.gusuarioId;
    }
    
    public void setGusuarioId(String gusuarioId) {
        this.gusuarioId = gusuarioId;
    }
    public Set getEsAplicacaoDiretas() {
        return this.esAplicacaoDiretas;
    }
    
    public void setEsAplicacaoDiretas(Set esAplicacaoDiretas) {
        this.esAplicacaoDiretas = esAplicacaoDiretas;
    }
    public Set getEsRecebimentos() {
        return this.esRecebimentos;
    }
    
    public void setEsRecebimentos(Set esRecebimentos) {
        this.esRecebimentos = esRecebimentos;
    }
    public Set getCpRequisis() {
        return this.cpRequisis;
    }
    
    public void setCpRequisis(Set cpRequisis) {
        this.cpRequisis = cpRequisis;
    }
    public Set getCpSoItenses() {
        return this.cpSoItenses;
    }
    
    public void setCpSoItenses(Set cpSoItenses) {
        this.cpSoItenses = cpSoItenses;
    }




}


