package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1



/**
 * CpSolicitacaoId generated by hbm2java
 */
public class CpSolicitacaoId  implements java.io.Serializable {


     private int ganoId;
     private String secretariaId;
     private int solicitacaoId;

    public CpSolicitacaoId() {
    }

    public CpSolicitacaoId(int ganoId, String secretariaId, int solicitacaoId) {
       this.ganoId = ganoId;
       this.secretariaId = secretariaId;
       this.solicitacaoId = solicitacaoId;
    }
   
    public int getGanoId() {
        return this.ganoId;
    }
    
    public void setGanoId(int ganoId) {
        this.ganoId = ganoId;
    }
    public String getSecretariaId() {
        return this.secretariaId;
    }
    
    public void setSecretariaId(String secretariaId) {
        this.secretariaId = secretariaId;
    }
    public int getSolicitacaoId() {
        return this.solicitacaoId;
    }
    
    public void setSolicitacaoId(int solicitacaoId) {
        this.solicitacaoId = solicitacaoId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CpSolicitacaoId) ) return false;
		 CpSolicitacaoId castOther = ( CpSolicitacaoId ) other; 
         
		 return (this.getGanoId()==castOther.getGanoId())
 && ( (this.getSecretariaId()==castOther.getSecretariaId()) || ( this.getSecretariaId()!=null && castOther.getSecretariaId()!=null && this.getSecretariaId().equals(castOther.getSecretariaId()) ) )
 && (this.getSolicitacaoId()==castOther.getSolicitacaoId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getGanoId();
         result = 37 * result + ( getSecretariaId() == null ? 0 : this.getSecretariaId().hashCode() );
         result = 37 * result + this.getSolicitacaoId();
         return result;
   }   


}


