package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CpSubTipoCompra generated by hbm2java
 */
public class CpSubTipoCompra  implements java.io.Serializable {


     private int subTipoCompraId;
     private String subTipoCompra;
     private long srRecno;
     private Set cpRequisis = new HashSet(0);
     private Set cpSolicitacaos = new HashSet(0);

    public CpSubTipoCompra() {
    }

	
    public CpSubTipoCompra(int subTipoCompraId, String subTipoCompra, long srRecno) {
        this.subTipoCompraId = subTipoCompraId;
        this.subTipoCompra = subTipoCompra;
        this.srRecno = srRecno;
    }
    public CpSubTipoCompra(int subTipoCompraId, String subTipoCompra, long srRecno, Set cpRequisis, Set cpSolicitacaos) {
       this.subTipoCompraId = subTipoCompraId;
       this.subTipoCompra = subTipoCompra;
       this.srRecno = srRecno;
       this.cpRequisis = cpRequisis;
       this.cpSolicitacaos = cpSolicitacaos;
    }
   
    public int getSubTipoCompraId() {
        return this.subTipoCompraId;
    }
    
    public void setSubTipoCompraId(int subTipoCompraId) {
        this.subTipoCompraId = subTipoCompraId;
    }
    public String getSubTipoCompra() {
        return this.subTipoCompra;
    }
    
    public void setSubTipoCompra(String subTipoCompra) {
        this.subTipoCompra = subTipoCompra;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }
    public Set getCpRequisis() {
        return this.cpRequisis;
    }
    
    public void setCpRequisis(Set cpRequisis) {
        this.cpRequisis = cpRequisis;
    }
    public Set getCpSolicitacaos() {
        return this.cpSolicitacaos;
    }
    
    public void setCpSolicitacaos(Set cpSolicitacaos) {
        this.cpSolicitacaos = cpSolicitacaos;
    }




}


