package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CpSubgrupo generated by hbm2java
 */
public class CpSubgrupo  implements java.io.Serializable {


     private int subgrupoId;
     private CpGrupo cpGrupo;
     private int subgrupoSeq;
     private String subgrupo;
     private long srRecno;
     private Set cpMaterials = new HashSet(0);
     private Set cpSolicitacaos = new HashSet(0);

    public CpSubgrupo() {
    }

	
    public CpSubgrupo(int subgrupoId, CpGrupo cpGrupo, int subgrupoSeq, String subgrupo, long srRecno) {
        this.subgrupoId = subgrupoId;
        this.cpGrupo = cpGrupo;
        this.subgrupoSeq = subgrupoSeq;
        this.subgrupo = subgrupo;
        this.srRecno = srRecno;
    }
    public CpSubgrupo(int subgrupoId, CpGrupo cpGrupo, int subgrupoSeq, String subgrupo, long srRecno, Set cpMaterials, Set cpSolicitacaos) {
       this.subgrupoId = subgrupoId;
       this.cpGrupo = cpGrupo;
       this.subgrupoSeq = subgrupoSeq;
       this.subgrupo = subgrupo;
       this.srRecno = srRecno;
       this.cpMaterials = cpMaterials;
       this.cpSolicitacaos = cpSolicitacaos;
    }
   
    public int getSubgrupoId() {
        return this.subgrupoId;
    }
    
    public void setSubgrupoId(int subgrupoId) {
        this.subgrupoId = subgrupoId;
    }
    public CpGrupo getCpGrupo() {
        return this.cpGrupo;
    }
    
    public void setCpGrupo(CpGrupo cpGrupo) {
        this.cpGrupo = cpGrupo;
    }
    public int getSubgrupoSeq() {
        return this.subgrupoSeq;
    }
    
    public void setSubgrupoSeq(int subgrupoSeq) {
        this.subgrupoSeq = subgrupoSeq;
    }
    public String getSubgrupo() {
        return this.subgrupo;
    }
    
    public void setSubgrupo(String subgrupo) {
        this.subgrupo = subgrupo;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }
    public Set getCpMaterials() {
        return this.cpMaterials;
    }
    
    public void setCpMaterials(Set cpMaterials) {
        this.cpMaterials = cpMaterials;
    }
    public Set getCpSolicitacaos() {
        return this.cpSolicitacaos;
    }
    
    public void setCpSolicitacaos(Set cpSolicitacaos) {
        this.cpSolicitacaos = cpSolicitacaos;
    }




}


