package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CpTipoCompra generated by hbm2java
 */
public class CpTipoCompra  implements java.io.Serializable {


     private int tipoCompraId;
     private CpModLicitacao cpModLicitacao;
     private String tceItem;
     private String descricao;
     private int carencia;
     private char artigo;
     private String condicao;
     private long srRecno;
     private Date gacesso;
     private Character tipoParticipacao;
     private String fundamentoLegal;
     private String usaSrp;
     private Set cpProtocolos = new HashSet(0);
     private Set cpCompras = new HashSet(0);
     private Set cpSolMats = new HashSet(0);

    public CpTipoCompra() {
    }

	
    public CpTipoCompra(int tipoCompraId, CpModLicitacao cpModLicitacao, String descricao, int carencia, char artigo, long srRecno) {
        this.tipoCompraId = tipoCompraId;
        this.cpModLicitacao = cpModLicitacao;
        this.descricao = descricao;
        this.carencia = carencia;
        this.artigo = artigo;
        this.srRecno = srRecno;
    }
    public CpTipoCompra(int tipoCompraId, CpModLicitacao cpModLicitacao, String tceItem, String descricao, int carencia, char artigo, String condicao, long srRecno, Date gacesso, Character tipoParticipacao, String fundamentoLegal, String usaSrp, Set cpProtocolos, Set cpCompras, Set cpSolMats) {
       this.tipoCompraId = tipoCompraId;
       this.cpModLicitacao = cpModLicitacao;
       this.tceItem = tceItem;
       this.descricao = descricao;
       this.carencia = carencia;
       this.artigo = artigo;
       this.condicao = condicao;
       this.srRecno = srRecno;
       this.gacesso = gacesso;
       this.tipoParticipacao = tipoParticipacao;
       this.fundamentoLegal = fundamentoLegal;
       this.usaSrp = usaSrp;
       this.cpProtocolos = cpProtocolos;
       this.cpCompras = cpCompras;
       this.cpSolMats = cpSolMats;
    }
   
    public int getTipoCompraId() {
        return this.tipoCompraId;
    }
    
    public void setTipoCompraId(int tipoCompraId) {
        this.tipoCompraId = tipoCompraId;
    }
    public CpModLicitacao getCpModLicitacao() {
        return this.cpModLicitacao;
    }
    
    public void setCpModLicitacao(CpModLicitacao cpModLicitacao) {
        this.cpModLicitacao = cpModLicitacao;
    }
    public String getTceItem() {
        return this.tceItem;
    }
    
    public void setTceItem(String tceItem) {
        this.tceItem = tceItem;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public int getCarencia() {
        return this.carencia;
    }
    
    public void setCarencia(int carencia) {
        this.carencia = carencia;
    }
    public char getArtigo() {
        return this.artigo;
    }
    
    public void setArtigo(char artigo) {
        this.artigo = artigo;
    }
    public String getCondicao() {
        return this.condicao;
    }
    
    public void setCondicao(String condicao) {
        this.condicao = condicao;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }
    public Date getGacesso() {
        return this.gacesso;
    }
    
    public void setGacesso(Date gacesso) {
        this.gacesso = gacesso;
    }
    public Character getTipoParticipacao() {
        return this.tipoParticipacao;
    }
    
    public void setTipoParticipacao(Character tipoParticipacao) {
        this.tipoParticipacao = tipoParticipacao;
    }
    public String getFundamentoLegal() {
        return this.fundamentoLegal;
    }
    
    public void setFundamentoLegal(String fundamentoLegal) {
        this.fundamentoLegal = fundamentoLegal;
    }
    public String getUsaSrp() {
        return this.usaSrp;
    }
    
    public void setUsaSrp(String usaSrp) {
        this.usaSrp = usaSrp;
    }
    public Set getCpProtocolos() {
        return this.cpProtocolos;
    }
    
    public void setCpProtocolos(Set cpProtocolos) {
        this.cpProtocolos = cpProtocolos;
    }
    public Set getCpCompras() {
        return this.cpCompras;
    }
    
    public void setCpCompras(Set cpCompras) {
        this.cpCompras = cpCompras;
    }
    public Set getCpSolMats() {
        return this.cpSolMats;
    }
    
    public void setCpSolMats(Set cpSolMats) {
        this.cpSolMats = cpSolMats;
    }




}


