package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CpTipoProduto generated by hbm2java
 */
public class CpTipoProduto  implements java.io.Serializable {


     private int tipoProdutoId;
     private String descricao;
     private long srRecno;
     private Date gacesso;
     private Set cpMaterials = new HashSet(0);

    public CpTipoProduto() {
    }

	
    public CpTipoProduto(int tipoProdutoId, String descricao, long srRecno) {
        this.tipoProdutoId = tipoProdutoId;
        this.descricao = descricao;
        this.srRecno = srRecno;
    }
    public CpTipoProduto(int tipoProdutoId, String descricao, long srRecno, Date gacesso, Set cpMaterials) {
       this.tipoProdutoId = tipoProdutoId;
       this.descricao = descricao;
       this.srRecno = srRecno;
       this.gacesso = gacesso;
       this.cpMaterials = cpMaterials;
    }
   
    public int getTipoProdutoId() {
        return this.tipoProdutoId;
    }
    
    public void setTipoProdutoId(int tipoProdutoId) {
        this.tipoProdutoId = tipoProdutoId;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }
    public Date getGacesso() {
        return this.gacesso;
    }
    
    public void setGacesso(Date gacesso) {
        this.gacesso = gacesso;
    }
    public Set getCpMaterials() {
        return this.cpMaterials;
    }
    
    public void setCpMaterials(Set cpMaterials) {
        this.cpMaterials = cpMaterials;
    }




}


