package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * EsAplicacaoDiretaItem generated by hbm2java
 */
public class EsAplicacaoDiretaItem  implements java.io.Serializable {


     private int aplicacaoDiretaItemId;
     private CpConcorrencia cpConcorrencia;
     private CpMaterial cpMaterial;
     private CpMaterialNatDesp cpMaterialNatDesp;
     private CpMedida cpMedida;
     private CpSoItens cpSoItens;
     private EsAplicacaoDireta esAplicacaoDireta;
     private int itemId;
     private String unid;
     private String material;
     private BigDecimal quant;
     private BigDecimal vlUnit;
     private BigDecimal vlTotal;
     private Integer reqAnoRequisi;
     private Integer reqNumero;
     private Integer reqItem;
     private long srRecno;
     private Set esAplicDiretaItemCombs = new HashSet(0);

    public EsAplicacaoDiretaItem() {
    }

	
    public EsAplicacaoDiretaItem(int aplicacaoDiretaItemId, CpMaterial cpMaterial, EsAplicacaoDireta esAplicacaoDireta, int itemId, BigDecimal quant, BigDecimal vlUnit, long srRecno) {
        this.aplicacaoDiretaItemId = aplicacaoDiretaItemId;
        this.cpMaterial = cpMaterial;
        this.esAplicacaoDireta = esAplicacaoDireta;
        this.itemId = itemId;
        this.quant = quant;
        this.vlUnit = vlUnit;
        this.srRecno = srRecno;
    }
    public EsAplicacaoDiretaItem(int aplicacaoDiretaItemId, CpConcorrencia cpConcorrencia, CpMaterial cpMaterial, CpMaterialNatDesp cpMaterialNatDesp, CpMedida cpMedida, CpSoItens cpSoItens, EsAplicacaoDireta esAplicacaoDireta, int itemId, String unid, String material, BigDecimal quant, BigDecimal vlUnit, BigDecimal vlTotal, Integer reqAnoRequisi, Integer reqNumero, Integer reqItem, long srRecno, Set esAplicDiretaItemCombs) {
       this.aplicacaoDiretaItemId = aplicacaoDiretaItemId;
       this.cpConcorrencia = cpConcorrencia;
       this.cpMaterial = cpMaterial;
       this.cpMaterialNatDesp = cpMaterialNatDesp;
       this.cpMedida = cpMedida;
       this.cpSoItens = cpSoItens;
       this.esAplicacaoDireta = esAplicacaoDireta;
       this.itemId = itemId;
       this.unid = unid;
       this.material = material;
       this.quant = quant;
       this.vlUnit = vlUnit;
       this.vlTotal = vlTotal;
       this.reqAnoRequisi = reqAnoRequisi;
       this.reqNumero = reqNumero;
       this.reqItem = reqItem;
       this.srRecno = srRecno;
       this.esAplicDiretaItemCombs = esAplicDiretaItemCombs;
    }
   
    public int getAplicacaoDiretaItemId() {
        return this.aplicacaoDiretaItemId;
    }
    
    public void setAplicacaoDiretaItemId(int aplicacaoDiretaItemId) {
        this.aplicacaoDiretaItemId = aplicacaoDiretaItemId;
    }
    public CpConcorrencia getCpConcorrencia() {
        return this.cpConcorrencia;
    }
    
    public void setCpConcorrencia(CpConcorrencia cpConcorrencia) {
        this.cpConcorrencia = cpConcorrencia;
    }
    public CpMaterial getCpMaterial() {
        return this.cpMaterial;
    }
    
    public void setCpMaterial(CpMaterial cpMaterial) {
        this.cpMaterial = cpMaterial;
    }
    public CpMaterialNatDesp getCpMaterialNatDesp() {
        return this.cpMaterialNatDesp;
    }
    
    public void setCpMaterialNatDesp(CpMaterialNatDesp cpMaterialNatDesp) {
        this.cpMaterialNatDesp = cpMaterialNatDesp;
    }
    public CpMedida getCpMedida() {
        return this.cpMedida;
    }
    
    public void setCpMedida(CpMedida cpMedida) {
        this.cpMedida = cpMedida;
    }
    public CpSoItens getCpSoItens() {
        return this.cpSoItens;
    }
    
    public void setCpSoItens(CpSoItens cpSoItens) {
        this.cpSoItens = cpSoItens;
    }
    public EsAplicacaoDireta getEsAplicacaoDireta() {
        return this.esAplicacaoDireta;
    }
    
    public void setEsAplicacaoDireta(EsAplicacaoDireta esAplicacaoDireta) {
        this.esAplicacaoDireta = esAplicacaoDireta;
    }
    public int getItemId() {
        return this.itemId;
    }
    
    public void setItemId(int itemId) {
        this.itemId = itemId;
    }
    public String getUnid() {
        return this.unid;
    }
    
    public void setUnid(String unid) {
        this.unid = unid;
    }
    public String getMaterial() {
        return this.material;
    }
    
    public void setMaterial(String material) {
        this.material = material;
    }
    public BigDecimal getQuant() {
        return this.quant;
    }
    
    public void setQuant(BigDecimal quant) {
        this.quant = quant;
    }
    public BigDecimal getVlUnit() {
        return this.vlUnit;
    }
    
    public void setVlUnit(BigDecimal vlUnit) {
        this.vlUnit = vlUnit;
    }
    public BigDecimal getVlTotal() {
        return this.vlTotal;
    }
    
    public void setVlTotal(BigDecimal vlTotal) {
        this.vlTotal = vlTotal;
    }
    public Integer getReqAnoRequisi() {
        return this.reqAnoRequisi;
    }
    
    public void setReqAnoRequisi(Integer reqAnoRequisi) {
        this.reqAnoRequisi = reqAnoRequisi;
    }
    public Integer getReqNumero() {
        return this.reqNumero;
    }
    
    public void setReqNumero(Integer reqNumero) {
        this.reqNumero = reqNumero;
    }
    public Integer getReqItem() {
        return this.reqItem;
    }
    
    public void setReqItem(Integer reqItem) {
        this.reqItem = reqItem;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }
    public Set getEsAplicDiretaItemCombs() {
        return this.esAplicDiretaItemCombs;
    }
    
    public void setEsAplicDiretaItemCombs(Set esAplicDiretaItemCombs) {
        this.esAplicDiretaItemCombs = esAplicDiretaItemCombs;
    }




}


