package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * EsAplicDiretaItemComb generated by hbm2java
 */
public class EsAplicDiretaItemComb  implements java.io.Serializable {


     private int aplicDiretaItemCombId;
     private EsAplicacaoDiretaItem esAplicacaoDiretaItem;
     private FrMotorista frMotorista;
     private FrVeiculo frVeiculo;
     private Date data;
     private int requisicao;
     private BigDecimal quant;
     private Integer kilometragem;
     private long srRecno;
     private String tipo;

    public EsAplicDiretaItemComb() {
    }

	
    public EsAplicDiretaItemComb(int aplicDiretaItemCombId, EsAplicacaoDiretaItem esAplicacaoDiretaItem, FrVeiculo frVeiculo, Date data, int requisicao, BigDecimal quant, long srRecno) {
        this.aplicDiretaItemCombId = aplicDiretaItemCombId;
        this.esAplicacaoDiretaItem = esAplicacaoDiretaItem;
        this.frVeiculo = frVeiculo;
        this.data = data;
        this.requisicao = requisicao;
        this.quant = quant;
        this.srRecno = srRecno;
    }
    public EsAplicDiretaItemComb(int aplicDiretaItemCombId, EsAplicacaoDiretaItem esAplicacaoDiretaItem, FrMotorista frMotorista, FrVeiculo frVeiculo, Date data, int requisicao, BigDecimal quant, Integer kilometragem, long srRecno, String tipo) {
       this.aplicDiretaItemCombId = aplicDiretaItemCombId;
       this.esAplicacaoDiretaItem = esAplicacaoDiretaItem;
       this.frMotorista = frMotorista;
       this.frVeiculo = frVeiculo;
       this.data = data;
       this.requisicao = requisicao;
       this.quant = quant;
       this.kilometragem = kilometragem;
       this.srRecno = srRecno;
       this.tipo = tipo;
    }
   
    public int getAplicDiretaItemCombId() {
        return this.aplicDiretaItemCombId;
    }
    
    public void setAplicDiretaItemCombId(int aplicDiretaItemCombId) {
        this.aplicDiretaItemCombId = aplicDiretaItemCombId;
    }
    public EsAplicacaoDiretaItem getEsAplicacaoDiretaItem() {
        return this.esAplicacaoDiretaItem;
    }
    
    public void setEsAplicacaoDiretaItem(EsAplicacaoDiretaItem esAplicacaoDiretaItem) {
        this.esAplicacaoDiretaItem = esAplicacaoDiretaItem;
    }
    public FrMotorista getFrMotorista() {
        return this.frMotorista;
    }
    
    public void setFrMotorista(FrMotorista frMotorista) {
        this.frMotorista = frMotorista;
    }
    public FrVeiculo getFrVeiculo() {
        return this.frVeiculo;
    }
    
    public void setFrVeiculo(FrVeiculo frVeiculo) {
        this.frVeiculo = frVeiculo;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public int getRequisicao() {
        return this.requisicao;
    }
    
    public void setRequisicao(int requisicao) {
        this.requisicao = requisicao;
    }
    public BigDecimal getQuant() {
        return this.quant;
    }
    
    public void setQuant(BigDecimal quant) {
        this.quant = quant;
    }
    public Integer getKilometragem() {
        return this.kilometragem;
    }
    
    public void setKilometragem(Integer kilometragem) {
        this.kilometragem = kilometragem;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }




}


