package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * EsAvaliacaoItensVeiculo generated by hbm2java
 */
public class EsAvaliacaoItensVeiculo  implements java.io.Serializable {


     private EsAvaliacaoItensVeiculoId id;
     private CpSecretaria cpSecretaria;
     private EsItensVeiculo esItensVeiculo;
     private FrVeiculo frVeiculo;
     private Date data;
     private String observacao;
     private char avaliacao;
     private long srRecno;

    public EsAvaliacaoItensVeiculo() {
    }

	
    public EsAvaliacaoItensVeiculo(EsAvaliacaoItensVeiculoId id, CpSecretaria cpSecretaria, EsItensVeiculo esItensVeiculo, FrVeiculo frVeiculo, Date data, char avaliacao, long srRecno) {
        this.id = id;
        this.cpSecretaria = cpSecretaria;
        this.esItensVeiculo = esItensVeiculo;
        this.frVeiculo = frVeiculo;
        this.data = data;
        this.avaliacao = avaliacao;
        this.srRecno = srRecno;
    }
    public EsAvaliacaoItensVeiculo(EsAvaliacaoItensVeiculoId id, CpSecretaria cpSecretaria, EsItensVeiculo esItensVeiculo, FrVeiculo frVeiculo, Date data, String observacao, char avaliacao, long srRecno) {
       this.id = id;
       this.cpSecretaria = cpSecretaria;
       this.esItensVeiculo = esItensVeiculo;
       this.frVeiculo = frVeiculo;
       this.data = data;
       this.observacao = observacao;
       this.avaliacao = avaliacao;
       this.srRecno = srRecno;
    }
   
    public EsAvaliacaoItensVeiculoId getId() {
        return this.id;
    }
    
    public void setId(EsAvaliacaoItensVeiculoId id) {
        this.id = id;
    }
    public CpSecretaria getCpSecretaria() {
        return this.cpSecretaria;
    }
    
    public void setCpSecretaria(CpSecretaria cpSecretaria) {
        this.cpSecretaria = cpSecretaria;
    }
    public EsItensVeiculo getEsItensVeiculo() {
        return this.esItensVeiculo;
    }
    
    public void setEsItensVeiculo(EsItensVeiculo esItensVeiculo) {
        this.esItensVeiculo = esItensVeiculo;
    }
    public FrVeiculo getFrVeiculo() {
        return this.frVeiculo;
    }
    
    public void setFrVeiculo(FrVeiculo frVeiculo) {
        this.frVeiculo = frVeiculo;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public String getObservacao() {
        return this.observacao;
    }
    
    public void setObservacao(String observacao) {
        this.observacao = observacao;
    }
    public char getAvaliacao() {
        return this.avaliacao;
    }
    
    public void setAvaliacao(char avaliacao) {
        this.avaliacao = avaliacao;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }




}


