package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * EsConsumoContab generated by hbm2java
 */
public class EsConsumoContab  implements java.io.Serializable {


     private int consumoId;
     private EsAplicacaoDireta esAplicacaoDireta;
     private EsRetirada esRetirada;
     private String natDespId;
     private Date data;
     private BigDecimal vlTotal;
     private long srRecno;

    public EsConsumoContab() {
    }

	
    public EsConsumoContab(int consumoId, String natDespId, Date data, BigDecimal vlTotal, long srRecno) {
        this.consumoId = consumoId;
        this.natDespId = natDespId;
        this.data = data;
        this.vlTotal = vlTotal;
        this.srRecno = srRecno;
    }
    public EsConsumoContab(int consumoId, EsAplicacaoDireta esAplicacaoDireta, EsRetirada esRetirada, String natDespId, Date data, BigDecimal vlTotal, long srRecno) {
       this.consumoId = consumoId;
       this.esAplicacaoDireta = esAplicacaoDireta;
       this.esRetirada = esRetirada;
       this.natDespId = natDespId;
       this.data = data;
       this.vlTotal = vlTotal;
       this.srRecno = srRecno;
    }
   
    public int getConsumoId() {
        return this.consumoId;
    }
    
    public void setConsumoId(int consumoId) {
        this.consumoId = consumoId;
    }
    public EsAplicacaoDireta getEsAplicacaoDireta() {
        return this.esAplicacaoDireta;
    }
    
    public void setEsAplicacaoDireta(EsAplicacaoDireta esAplicacaoDireta) {
        this.esAplicacaoDireta = esAplicacaoDireta;
    }
    public EsRetirada getEsRetirada() {
        return this.esRetirada;
    }
    
    public void setEsRetirada(EsRetirada esRetirada) {
        this.esRetirada = esRetirada;
    }
    public String getNatDespId() {
        return this.natDespId;
    }
    
    public void setNatDespId(String natDespId) {
        this.natDespId = natDespId;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public BigDecimal getVlTotal() {
        return this.vlTotal;
    }
    
    public void setVlTotal(BigDecimal vlTotal) {
        this.vlTotal = vlTotal;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }




}


