package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * EsComInventarioMembro generated by hbm2java
 */
public class EsComInventarioMembro  implements java.io.Serializable {


     private int comMembroId;
     private EsComissaoInventario esComissaoInventario;
     private String matricula;
     private String cpf;
     private String nome;
     private Integer funcao;
     private Integer tipo;
     private long srRecno;
     private Set esProcessoInventarios = new HashSet(0);

    public EsComInventarioMembro() {
    }

	
    public EsComInventarioMembro(int comMembroId, EsComissaoInventario esComissaoInventario, long srRecno) {
        this.comMembroId = comMembroId;
        this.esComissaoInventario = esComissaoInventario;
        this.srRecno = srRecno;
    }
    public EsComInventarioMembro(int comMembroId, EsComissaoInventario esComissaoInventario, String matricula, String cpf, String nome, Integer funcao, Integer tipo, long srRecno, Set esProcessoInventarios) {
       this.comMembroId = comMembroId;
       this.esComissaoInventario = esComissaoInventario;
       this.matricula = matricula;
       this.cpf = cpf;
       this.nome = nome;
       this.funcao = funcao;
       this.tipo = tipo;
       this.srRecno = srRecno;
       this.esProcessoInventarios = esProcessoInventarios;
    }
   
    public int getComMembroId() {
        return this.comMembroId;
    }
    
    public void setComMembroId(int comMembroId) {
        this.comMembroId = comMembroId;
    }
    public EsComissaoInventario getEsComissaoInventario() {
        return this.esComissaoInventario;
    }
    
    public void setEsComissaoInventario(EsComissaoInventario esComissaoInventario) {
        this.esComissaoInventario = esComissaoInventario;
    }
    public String getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Integer getFuncao() {
        return this.funcao;
    }
    
    public void setFuncao(Integer funcao) {
        this.funcao = funcao;
    }
    public Integer getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Integer tipo) {
        this.tipo = tipo;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }
    public Set getEsProcessoInventarios() {
        return this.esProcessoInventarios;
    }
    
    public void setEsProcessoInventarios(Set esProcessoInventarios) {
        this.esProcessoInventarios = esProcessoInventarios;
    }




}


