package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * EsCustoReal generated by hbm2java
 */
public class EsCustoReal  implements java.io.Serializable {


     private int custoRealId;
     private EsRecebimentoItem esRecebimentoItem;
     private EsRetiradaItem esRetiradaItem;
     private BigDecimal quant;
     private long srRecno;

    public EsCustoReal() {
    }

    public EsCustoReal(int custoRealId, EsRecebimentoItem esRecebimentoItem, EsRetiradaItem esRetiradaItem, BigDecimal quant, long srRecno) {
       this.custoRealId = custoRealId;
       this.esRecebimentoItem = esRecebimentoItem;
       this.esRetiradaItem = esRetiradaItem;
       this.quant = quant;
       this.srRecno = srRecno;
    }
   
    public int getCustoRealId() {
        return this.custoRealId;
    }
    
    public void setCustoRealId(int custoRealId) {
        this.custoRealId = custoRealId;
    }
    public EsRecebimentoItem getEsRecebimentoItem() {
        return this.esRecebimentoItem;
    }
    
    public void setEsRecebimentoItem(EsRecebimentoItem esRecebimentoItem) {
        this.esRecebimentoItem = esRecebimentoItem;
    }
    public EsRetiradaItem getEsRetiradaItem() {
        return this.esRetiradaItem;
    }
    
    public void setEsRetiradaItem(EsRetiradaItem esRetiradaItem) {
        this.esRetiradaItem = esRetiradaItem;
    }
    public BigDecimal getQuant() {
        return this.quant;
    }
    
    public void setQuant(BigDecimal quant) {
        this.quant = quant;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }




}


