package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1



/**
 * EsDepositoSecretaria generated by hbm2java
 */
public class EsDepositoSecretaria  implements java.io.Serializable {


     private int depSecId;
     private CpSecretaria cpSecretaria;
     private EsDeposito esDeposito;
     private long srRecno;

    public EsDepositoSecretaria() {
    }

    public EsDepositoSecretaria(int depSecId, CpSecretaria cpSecretaria, EsDeposito esDeposito, long srRecno) {
       this.depSecId = depSecId;
       this.cpSecretaria = cpSecretaria;
       this.esDeposito = esDeposito;
       this.srRecno = srRecno;
    }
   
    public int getDepSecId() {
        return this.depSecId;
    }
    
    public void setDepSecId(int depSecId) {
        this.depSecId = depSecId;
    }
    public CpSecretaria getCpSecretaria() {
        return this.cpSecretaria;
    }
    
    public void setCpSecretaria(CpSecretaria cpSecretaria) {
        this.cpSecretaria = cpSecretaria;
    }
    public EsDeposito getEsDeposito() {
        return this.esDeposito;
    }
    
    public void setEsDeposito(EsDeposito esDeposito) {
        this.esDeposito = esDeposito;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }




}


