package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * EsDeposito generated by hbm2java
 */
public class EsDeposito  implements java.io.Serializable {


     private int depositoId;
     private String deposito;
     private long srRecno;
     private Set esDepositoUsuarios = new HashSet(0);
     private Set esDepositoSecretarias = new HashSet(0);
     private Set esInventarios = new HashSet(0);
     private Set esLanctosForDepositoIddestino = new HashSet(0);
     private Set esMaterialEstocados = new HashSet(0);
     private Set esRetiradas = new HashSet(0);
     private Set esAplicacaoDiretas = new HashSet(0);
     private Set esRecebimentos = new HashSet(0);
     private Set esRequisicaos = new HashSet(0);
     private Set esLanctosForDepositoIdorigem = new HashSet(0);

    public EsDeposito() {
    }

	
    public EsDeposito(int depositoId, String deposito, long srRecno) {
        this.depositoId = depositoId;
        this.deposito = deposito;
        this.srRecno = srRecno;
    }
    public EsDeposito(int depositoId, String deposito, long srRecno, Set esDepositoUsuarios, Set esDepositoSecretarias, Set esInventarios, Set esLanctosForDepositoIddestino, Set esMaterialEstocados, Set esRetiradas, Set esAplicacaoDiretas, Set esRecebimentos, Set esRequisicaos, Set esLanctosForDepositoIdorigem) {
       this.depositoId = depositoId;
       this.deposito = deposito;
       this.srRecno = srRecno;
       this.esDepositoUsuarios = esDepositoUsuarios;
       this.esDepositoSecretarias = esDepositoSecretarias;
       this.esInventarios = esInventarios;
       this.esLanctosForDepositoIddestino = esLanctosForDepositoIddestino;
       this.esMaterialEstocados = esMaterialEstocados;
       this.esRetiradas = esRetiradas;
       this.esAplicacaoDiretas = esAplicacaoDiretas;
       this.esRecebimentos = esRecebimentos;
       this.esRequisicaos = esRequisicaos;
       this.esLanctosForDepositoIdorigem = esLanctosForDepositoIdorigem;
    }
   
    public int getDepositoId() {
        return this.depositoId;
    }
    
    public void setDepositoId(int depositoId) {
        this.depositoId = depositoId;
    }
    public String getDeposito() {
        return this.deposito;
    }
    
    public void setDeposito(String deposito) {
        this.deposito = deposito;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }
    public Set getEsDepositoUsuarios() {
        return this.esDepositoUsuarios;
    }
    
    public void setEsDepositoUsuarios(Set esDepositoUsuarios) {
        this.esDepositoUsuarios = esDepositoUsuarios;
    }
    public Set getEsDepositoSecretarias() {
        return this.esDepositoSecretarias;
    }
    
    public void setEsDepositoSecretarias(Set esDepositoSecretarias) {
        this.esDepositoSecretarias = esDepositoSecretarias;
    }
    public Set getEsInventarios() {
        return this.esInventarios;
    }
    
    public void setEsInventarios(Set esInventarios) {
        this.esInventarios = esInventarios;
    }
    public Set getEsLanctosForDepositoIddestino() {
        return this.esLanctosForDepositoIddestino;
    }
    
    public void setEsLanctosForDepositoIddestino(Set esLanctosForDepositoIddestino) {
        this.esLanctosForDepositoIddestino = esLanctosForDepositoIddestino;
    }
    public Set getEsMaterialEstocados() {
        return this.esMaterialEstocados;
    }
    
    public void setEsMaterialEstocados(Set esMaterialEstocados) {
        this.esMaterialEstocados = esMaterialEstocados;
    }
    public Set getEsRetiradas() {
        return this.esRetiradas;
    }
    
    public void setEsRetiradas(Set esRetiradas) {
        this.esRetiradas = esRetiradas;
    }
    public Set getEsAplicacaoDiretas() {
        return this.esAplicacaoDiretas;
    }
    
    public void setEsAplicacaoDiretas(Set esAplicacaoDiretas) {
        this.esAplicacaoDiretas = esAplicacaoDiretas;
    }
    public Set getEsRecebimentos() {
        return this.esRecebimentos;
    }
    
    public void setEsRecebimentos(Set esRecebimentos) {
        this.esRecebimentos = esRecebimentos;
    }
    public Set getEsRequisicaos() {
        return this.esRequisicaos;
    }
    
    public void setEsRequisicaos(Set esRequisicaos) {
        this.esRequisicaos = esRequisicaos;
    }
    public Set getEsLanctosForDepositoIdorigem() {
        return this.esLanctosForDepositoIdorigem;
    }
    
    public void setEsLanctosForDepositoIdorigem(Set esLanctosForDepositoIdorigem) {
        this.esLanctosForDepositoIdorigem = esLanctosForDepositoIdorigem;
    }




}


