package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1



/**
 * EsDepositoUsuario generated by hbm2java
 */
public class EsDepositoUsuario  implements java.io.Serializable {


     private int depUsuId;
     private EsDeposito esDeposito;
     private Gusuario gusuario;
     private long srRecno;

    public EsDepositoUsuario() {
    }

    public EsDepositoUsuario(int depUsuId, EsDeposito esDeposito, Gusuario gusuario, long srRecno) {
       this.depUsuId = depUsuId;
       this.esDeposito = esDeposito;
       this.gusuario = gusuario;
       this.srRecno = srRecno;
    }
   
    public int getDepUsuId() {
        return this.depUsuId;
    }
    
    public void setDepUsuId(int depUsuId) {
        this.depUsuId = depUsuId;
    }
    public EsDeposito getEsDeposito() {
        return this.esDeposito;
    }
    
    public void setEsDeposito(EsDeposito esDeposito) {
        this.esDeposito = esDeposito;
    }
    public Gusuario getGusuario() {
        return this.gusuario;
    }
    
    public void setGusuario(Gusuario gusuario) {
        this.gusuario = gusuario;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }




}


