package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * EsEstoqueMaterial generated by hbm2java
 */
public class EsEstoqueMaterial  implements java.io.Serializable {


     private EsEstoqueMaterialId id;
     private BigDecimal estoqueMinimo;
     private BigDecimal estoqueMaximo;
     private long srRecno;

    public EsEstoqueMaterial() {
    }

	
    public EsEstoqueMaterial(EsEstoqueMaterialId id, long srRecno) {
        this.id = id;
        this.srRecno = srRecno;
    }
    public EsEstoqueMaterial(EsEstoqueMaterialId id, BigDecimal estoqueMinimo, BigDecimal estoqueMaximo, long srRecno) {
       this.id = id;
       this.estoqueMinimo = estoqueMinimo;
       this.estoqueMaximo = estoqueMaximo;
       this.srRecno = srRecno;
    }
   
    public EsEstoqueMaterialId getId() {
        return this.id;
    }
    
    public void setId(EsEstoqueMaterialId id) {
        this.id = id;
    }
    public BigDecimal getEstoqueMinimo() {
        return this.estoqueMinimo;
    }
    
    public void setEstoqueMinimo(BigDecimal estoqueMinimo) {
        this.estoqueMinimo = estoqueMinimo;
    }
    public BigDecimal getEstoqueMaximo() {
        return this.estoqueMaximo;
    }
    
    public void setEstoqueMaximo(BigDecimal estoqueMaximo) {
        this.estoqueMaximo = estoqueMaximo;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }




}


