package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1



/**
 * EsEstoqueMaterialId generated by hbm2java
 */
public class EsEstoqueMaterialId  implements java.io.Serializable {


     private int materialId;
     private int depositoId;

    public EsEstoqueMaterialId() {
    }

    public EsEstoqueMaterialId(int materialId, int depositoId) {
       this.materialId = materialId;
       this.depositoId = depositoId;
    }
   
    public int getMaterialId() {
        return this.materialId;
    }
    
    public void setMaterialId(int materialId) {
        this.materialId = materialId;
    }
    public int getDepositoId() {
        return this.depositoId;
    }
    
    public void setDepositoId(int depositoId) {
        this.depositoId = depositoId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EsEstoqueMaterialId) ) return false;
		 EsEstoqueMaterialId castOther = ( EsEstoqueMaterialId ) other; 
         
		 return (this.getMaterialId()==castOther.getMaterialId())
 && (this.getDepositoId()==castOther.getDepositoId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getMaterialId();
         result = 37 * result + this.getDepositoId();
         return result;
   }   


}


