package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * EsInventarioTipo generated by hbm2java
 */
public class EsInventarioTipo  implements java.io.Serializable {


     private int inventarioTipoId;
     private String descricao;
     private char desativado;
     private String gusuarioId;
     private Date gacesso;
     private long srRecno;
     private Set esInventarios = new HashSet(0);

    public EsInventarioTipo() {
    }

	
    public EsInventarioTipo(int inventarioTipoId, String descricao, char desativado, String gusuarioId, Date gacesso, long srRecno) {
        this.inventarioTipoId = inventarioTipoId;
        this.descricao = descricao;
        this.desativado = desativado;
        this.gusuarioId = gusuarioId;
        this.gacesso = gacesso;
        this.srRecno = srRecno;
    }
    public EsInventarioTipo(int inventarioTipoId, String descricao, char desativado, String gusuarioId, Date gacesso, long srRecno, Set esInventarios) {
       this.inventarioTipoId = inventarioTipoId;
       this.descricao = descricao;
       this.desativado = desativado;
       this.gusuarioId = gusuarioId;
       this.gacesso = gacesso;
       this.srRecno = srRecno;
       this.esInventarios = esInventarios;
    }
   
    public int getInventarioTipoId() {
        return this.inventarioTipoId;
    }
    
    public void setInventarioTipoId(int inventarioTipoId) {
        this.inventarioTipoId = inventarioTipoId;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public char getDesativado() {
        return this.desativado;
    }
    
    public void setDesativado(char desativado) {
        this.desativado = desativado;
    }
    public String getGusuarioId() {
        return this.gusuarioId;
    }
    
    public void setGusuarioId(String gusuarioId) {
        this.gusuarioId = gusuarioId;
    }
    public Date getGacesso() {
        return this.gacesso;
    }
    
    public void setGacesso(Date gacesso) {
        this.gacesso = gacesso;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }
    public Set getEsInventarios() {
        return this.esInventarios;
    }
    
    public void setEsInventarios(Set esInventarios) {
        this.esInventarios = esInventarios;
    }




}


