package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * EsInventarioItem generated by hbm2java
 */
public class EsInventarioItem  implements java.io.Serializable {


     private int inventarioItemId;
     private CpMaterial cpMaterial;
     private EsInventario esInventario;
     private Gusuario gusuario;
     private int itemId;
     private BigDecimal vlUnit;
     private BigDecimal saldo;
     private BigDecimal inventario;
     private Date gacesso;
     private long srRecno;
     private Set esInventarioItemDets = new HashSet(0);
     private Set esRecebimentoItems = new HashSet(0);
     private Set esRetiradaItems = new HashSet(0);

    public EsInventarioItem() {
    }

	
    public EsInventarioItem(int inventarioItemId, CpMaterial cpMaterial, EsInventario esInventario, int itemId, BigDecimal vlUnit, BigDecimal saldo, Date gacesso, long srRecno) {
        this.inventarioItemId = inventarioItemId;
        this.cpMaterial = cpMaterial;
        this.esInventario = esInventario;
        this.itemId = itemId;
        this.vlUnit = vlUnit;
        this.saldo = saldo;
        this.gacesso = gacesso;
        this.srRecno = srRecno;
    }
    public EsInventarioItem(int inventarioItemId, CpMaterial cpMaterial, EsInventario esInventario, Gusuario gusuario, int itemId, BigDecimal vlUnit, BigDecimal saldo, BigDecimal inventario, Date gacesso, long srRecno, Set esInventarioItemDets, Set esRecebimentoItems, Set esRetiradaItems) {
       this.inventarioItemId = inventarioItemId;
       this.cpMaterial = cpMaterial;
       this.esInventario = esInventario;
       this.gusuario = gusuario;
       this.itemId = itemId;
       this.vlUnit = vlUnit;
       this.saldo = saldo;
       this.inventario = inventario;
       this.gacesso = gacesso;
       this.srRecno = srRecno;
       this.esInventarioItemDets = esInventarioItemDets;
       this.esRecebimentoItems = esRecebimentoItems;
       this.esRetiradaItems = esRetiradaItems;
    }
   
    public int getInventarioItemId() {
        return this.inventarioItemId;
    }
    
    public void setInventarioItemId(int inventarioItemId) {
        this.inventarioItemId = inventarioItemId;
    }
    public CpMaterial getCpMaterial() {
        return this.cpMaterial;
    }
    
    public void setCpMaterial(CpMaterial cpMaterial) {
        this.cpMaterial = cpMaterial;
    }
    public EsInventario getEsInventario() {
        return this.esInventario;
    }
    
    public void setEsInventario(EsInventario esInventario) {
        this.esInventario = esInventario;
    }
    public Gusuario getGusuario() {
        return this.gusuario;
    }
    
    public void setGusuario(Gusuario gusuario) {
        this.gusuario = gusuario;
    }
    public int getItemId() {
        return this.itemId;
    }
    
    public void setItemId(int itemId) {
        this.itemId = itemId;
    }
    public BigDecimal getVlUnit() {
        return this.vlUnit;
    }
    
    public void setVlUnit(BigDecimal vlUnit) {
        this.vlUnit = vlUnit;
    }
    public BigDecimal getSaldo() {
        return this.saldo;
    }
    
    public void setSaldo(BigDecimal saldo) {
        this.saldo = saldo;
    }
    public BigDecimal getInventario() {
        return this.inventario;
    }
    
    public void setInventario(BigDecimal inventario) {
        this.inventario = inventario;
    }
    public Date getGacesso() {
        return this.gacesso;
    }
    
    public void setGacesso(Date gacesso) {
        this.gacesso = gacesso;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }
    public Set getEsInventarioItemDets() {
        return this.esInventarioItemDets;
    }
    
    public void setEsInventarioItemDets(Set esInventarioItemDets) {
        this.esInventarioItemDets = esInventarioItemDets;
    }
    public Set getEsRecebimentoItems() {
        return this.esRecebimentoItems;
    }
    
    public void setEsRecebimentoItems(Set esRecebimentoItems) {
        this.esRecebimentoItems = esRecebimentoItems;
    }
    public Set getEsRetiradaItems() {
        return this.esRetiradaItems;
    }
    
    public void setEsRetiradaItems(Set esRetiradaItems) {
        this.esRetiradaItems = esRetiradaItems;
    }




}


