package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * EsItensVeiculo generated by hbm2java
 */
public class EsItensVeiculo  implements java.io.Serializable {


     private int itemId;
     private String item;
     private long srRecno;
     private int veiculoId;
     private Set esAcessoriosVeiculos = new HashSet(0);
     private Set esAvaliacaoItensVeiculos = new HashSet(0);

    public EsItensVeiculo() {
    }

	
    public EsItensVeiculo(int itemId, String item, long srRecno, int veiculoId) {
        this.itemId = itemId;
        this.item = item;
        this.srRecno = srRecno;
        this.veiculoId = veiculoId;
    }
    public EsItensVeiculo(int itemId, String item, long srRecno, int veiculoId, Set esAcessoriosVeiculos, Set esAvaliacaoItensVeiculos) {
       this.itemId = itemId;
       this.item = item;
       this.srRecno = srRecno;
       this.veiculoId = veiculoId;
       this.esAcessoriosVeiculos = esAcessoriosVeiculos;
       this.esAvaliacaoItensVeiculos = esAvaliacaoItensVeiculos;
    }
   
    public int getItemId() {
        return this.itemId;
    }
    
    public void setItemId(int itemId) {
        this.itemId = itemId;
    }
    public String getItem() {
        return this.item;
    }
    
    public void setItem(String item) {
        this.item = item;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }
    public int getVeiculoId() {
        return this.veiculoId;
    }
    
    public void setVeiculoId(int veiculoId) {
        this.veiculoId = veiculoId;
    }
    public Set getEsAcessoriosVeiculos() {
        return this.esAcessoriosVeiculos;
    }
    
    public void setEsAcessoriosVeiculos(Set esAcessoriosVeiculos) {
        this.esAcessoriosVeiculos = esAcessoriosVeiculos;
    }
    public Set getEsAvaliacaoItensVeiculos() {
        return this.esAvaliacaoItensVeiculos;
    }
    
    public void setEsAvaliacaoItensVeiculos(Set esAvaliacaoItensVeiculos) {
        this.esAvaliacaoItensVeiculos = esAvaliacaoItensVeiculos;
    }




}


