package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * EsLinhasTransp generated by hbm2java
 */
public class EsLinhasTransp  implements java.io.Serializable {


     private int linhasTranspId;
     private EsRotas esRotas;
     private Integer motoristaId;
     private Integer veiculoId;
     private Date data;
     private String descricao;
     private long srRecno;

    public EsLinhasTransp() {
    }

	
    public EsLinhasTransp(int linhasTranspId, long srRecno) {
        this.linhasTranspId = linhasTranspId;
        this.srRecno = srRecno;
    }
    public EsLinhasTransp(int linhasTranspId, EsRotas esRotas, Integer motoristaId, Integer veiculoId, Date data, String descricao, long srRecno) {
       this.linhasTranspId = linhasTranspId;
       this.esRotas = esRotas;
       this.motoristaId = motoristaId;
       this.veiculoId = veiculoId;
       this.data = data;
       this.descricao = descricao;
       this.srRecno = srRecno;
    }
   
    public int getLinhasTranspId() {
        return this.linhasTranspId;
    }
    
    public void setLinhasTranspId(int linhasTranspId) {
        this.linhasTranspId = linhasTranspId;
    }
    public EsRotas getEsRotas() {
        return this.esRotas;
    }
    
    public void setEsRotas(EsRotas esRotas) {
        this.esRotas = esRotas;
    }
    public Integer getMotoristaId() {
        return this.motoristaId;
    }
    
    public void setMotoristaId(Integer motoristaId) {
        this.motoristaId = motoristaId;
    }
    public Integer getVeiculoId() {
        return this.veiculoId;
    }
    
    public void setVeiculoId(Integer veiculoId) {
        this.veiculoId = veiculoId;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }




}


