package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * EsLog generated by hbm2java
 */
public class EsLog  implements java.io.Serializable {


     private int logId;
     private String gusuarioId;
     private String usuario;
     private Date dataHora;
     private int pagina;
     private char acao;
     private String pk1;
     private String pk2;
     private String pk3;
     private String pk4;
     private String pk5;
     private String pk6;
     private String pk7;
     private String pk8;
     private String pk9;
     private String pk10;
     private String pk11;
     private String pk12;
     private String pk13;
     private String pk14;
     private String pk15;
     private String pk16;
     private String pk17;
     private String pk18;
     private String pk19;
     private String pk20;
     private byte[] descricao;
     private byte[] query;
     private String ip;
     private long srRecno;

    public EsLog() {
    }

	
    public EsLog(int logId, String gusuarioId, String usuario, Date dataHora, int pagina, char acao, String pk1, byte[] descricao, byte[] query, long srRecno) {
        this.logId = logId;
        this.gusuarioId = gusuarioId;
        this.usuario = usuario;
        this.dataHora = dataHora;
        this.pagina = pagina;
        this.acao = acao;
        this.pk1 = pk1;
        this.descricao = descricao;
        this.query = query;
        this.srRecno = srRecno;
    }
    public EsLog(int logId, String gusuarioId, String usuario, Date dataHora, int pagina, char acao, String pk1, String pk2, String pk3, String pk4, String pk5, String pk6, String pk7, String pk8, String pk9, String pk10, String pk11, String pk12, String pk13, String pk14, String pk15, String pk16, String pk17, String pk18, String pk19, String pk20, byte[] descricao, byte[] query, String ip, long srRecno) {
       this.logId = logId;
       this.gusuarioId = gusuarioId;
       this.usuario = usuario;
       this.dataHora = dataHora;
       this.pagina = pagina;
       this.acao = acao;
       this.pk1 = pk1;
       this.pk2 = pk2;
       this.pk3 = pk3;
       this.pk4 = pk4;
       this.pk5 = pk5;
       this.pk6 = pk6;
       this.pk7 = pk7;
       this.pk8 = pk8;
       this.pk9 = pk9;
       this.pk10 = pk10;
       this.pk11 = pk11;
       this.pk12 = pk12;
       this.pk13 = pk13;
       this.pk14 = pk14;
       this.pk15 = pk15;
       this.pk16 = pk16;
       this.pk17 = pk17;
       this.pk18 = pk18;
       this.pk19 = pk19;
       this.pk20 = pk20;
       this.descricao = descricao;
       this.query = query;
       this.ip = ip;
       this.srRecno = srRecno;
    }
   
    public int getLogId() {
        return this.logId;
    }
    
    public void setLogId(int logId) {
        this.logId = logId;
    }
    public String getGusuarioId() {
        return this.gusuarioId;
    }
    
    public void setGusuarioId(String gusuarioId) {
        this.gusuarioId = gusuarioId;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public Date getDataHora() {
        return this.dataHora;
    }
    
    public void setDataHora(Date dataHora) {
        this.dataHora = dataHora;
    }
    public int getPagina() {
        return this.pagina;
    }
    
    public void setPagina(int pagina) {
        this.pagina = pagina;
    }
    public char getAcao() {
        return this.acao;
    }
    
    public void setAcao(char acao) {
        this.acao = acao;
    }
    public String getPk1() {
        return this.pk1;
    }
    
    public void setPk1(String pk1) {
        this.pk1 = pk1;
    }
    public String getPk2() {
        return this.pk2;
    }
    
    public void setPk2(String pk2) {
        this.pk2 = pk2;
    }
    public String getPk3() {
        return this.pk3;
    }
    
    public void setPk3(String pk3) {
        this.pk3 = pk3;
    }
    public String getPk4() {
        return this.pk4;
    }
    
    public void setPk4(String pk4) {
        this.pk4 = pk4;
    }
    public String getPk5() {
        return this.pk5;
    }
    
    public void setPk5(String pk5) {
        this.pk5 = pk5;
    }
    public String getPk6() {
        return this.pk6;
    }
    
    public void setPk6(String pk6) {
        this.pk6 = pk6;
    }
    public String getPk7() {
        return this.pk7;
    }
    
    public void setPk7(String pk7) {
        this.pk7 = pk7;
    }
    public String getPk8() {
        return this.pk8;
    }
    
    public void setPk8(String pk8) {
        this.pk8 = pk8;
    }
    public String getPk9() {
        return this.pk9;
    }
    
    public void setPk9(String pk9) {
        this.pk9 = pk9;
    }
    public String getPk10() {
        return this.pk10;
    }
    
    public void setPk10(String pk10) {
        this.pk10 = pk10;
    }
    public String getPk11() {
        return this.pk11;
    }
    
    public void setPk11(String pk11) {
        this.pk11 = pk11;
    }
    public String getPk12() {
        return this.pk12;
    }
    
    public void setPk12(String pk12) {
        this.pk12 = pk12;
    }
    public String getPk13() {
        return this.pk13;
    }
    
    public void setPk13(String pk13) {
        this.pk13 = pk13;
    }
    public String getPk14() {
        return this.pk14;
    }
    
    public void setPk14(String pk14) {
        this.pk14 = pk14;
    }
    public String getPk15() {
        return this.pk15;
    }
    
    public void setPk15(String pk15) {
        this.pk15 = pk15;
    }
    public String getPk16() {
        return this.pk16;
    }
    
    public void setPk16(String pk16) {
        this.pk16 = pk16;
    }
    public String getPk17() {
        return this.pk17;
    }
    
    public void setPk17(String pk17) {
        this.pk17 = pk17;
    }
    public String getPk18() {
        return this.pk18;
    }
    
    public void setPk18(String pk18) {
        this.pk18 = pk18;
    }
    public String getPk19() {
        return this.pk19;
    }
    
    public void setPk19(String pk19) {
        this.pk19 = pk19;
    }
    public String getPk20() {
        return this.pk20;
    }
    
    public void setPk20(String pk20) {
        this.pk20 = pk20;
    }
    public byte[] getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(byte[] descricao) {
        this.descricao = descricao;
    }
    public byte[] getQuery() {
        return this.query;
    }
    
    public void setQuery(byte[] query) {
        this.query = query;
    }
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }




}


