package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * EsLoteRemedioBx generated by hbm2java
 */
public class EsLoteRemedioBx  implements java.io.Serializable {


     private int loteRemedioBxId;
     private CpCcusto cpCcusto;
     private CpMaterial cpMaterial;
     private EsLoteRemedio esLoteRemedio;
     private EsPaciente esPaciente;
     private EsRetiradaItem esRetiradaItem;
     private BigDecimal quant;
     private long srRecno;
     private String medicoId;
     private String atendenteId;

    public EsLoteRemedioBx() {
    }

	
    public EsLoteRemedioBx(int loteRemedioBxId, CpMaterial cpMaterial, EsLoteRemedio esLoteRemedio, EsRetiradaItem esRetiradaItem, BigDecimal quant, long srRecno) {
        this.loteRemedioBxId = loteRemedioBxId;
        this.cpMaterial = cpMaterial;
        this.esLoteRemedio = esLoteRemedio;
        this.esRetiradaItem = esRetiradaItem;
        this.quant = quant;
        this.srRecno = srRecno;
    }
    public EsLoteRemedioBx(int loteRemedioBxId, CpCcusto cpCcusto, CpMaterial cpMaterial, EsLoteRemedio esLoteRemedio, EsPaciente esPaciente, EsRetiradaItem esRetiradaItem, BigDecimal quant, long srRecno, String medicoId, String atendenteId) {
       this.loteRemedioBxId = loteRemedioBxId;
       this.cpCcusto = cpCcusto;
       this.cpMaterial = cpMaterial;
       this.esLoteRemedio = esLoteRemedio;
       this.esPaciente = esPaciente;
       this.esRetiradaItem = esRetiradaItem;
       this.quant = quant;
       this.srRecno = srRecno;
       this.medicoId = medicoId;
       this.atendenteId = atendenteId;
    }
   
    public int getLoteRemedioBxId() {
        return this.loteRemedioBxId;
    }
    
    public void setLoteRemedioBxId(int loteRemedioBxId) {
        this.loteRemedioBxId = loteRemedioBxId;
    }
    public CpCcusto getCpCcusto() {
        return this.cpCcusto;
    }
    
    public void setCpCcusto(CpCcusto cpCcusto) {
        this.cpCcusto = cpCcusto;
    }
    public CpMaterial getCpMaterial() {
        return this.cpMaterial;
    }
    
    public void setCpMaterial(CpMaterial cpMaterial) {
        this.cpMaterial = cpMaterial;
    }
    public EsLoteRemedio getEsLoteRemedio() {
        return this.esLoteRemedio;
    }
    
    public void setEsLoteRemedio(EsLoteRemedio esLoteRemedio) {
        this.esLoteRemedio = esLoteRemedio;
    }
    public EsPaciente getEsPaciente() {
        return this.esPaciente;
    }
    
    public void setEsPaciente(EsPaciente esPaciente) {
        this.esPaciente = esPaciente;
    }
    public EsRetiradaItem getEsRetiradaItem() {
        return this.esRetiradaItem;
    }
    
    public void setEsRetiradaItem(EsRetiradaItem esRetiradaItem) {
        this.esRetiradaItem = esRetiradaItem;
    }
    public BigDecimal getQuant() {
        return this.quant;
    }
    
    public void setQuant(BigDecimal quant) {
        this.quant = quant;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }
    public String getMedicoId() {
        return this.medicoId;
    }
    
    public void setMedicoId(String medicoId) {
        this.medicoId = medicoId;
    }
    public String getAtendenteId() {
        return this.atendenteId;
    }
    
    public void setAtendenteId(String atendenteId) {
        this.atendenteId = atendenteId;
    }




}


