package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * EsLoteRemedio generated by hbm2java
 */
public class EsLoteRemedio  implements java.io.Serializable {


     private int loteRemedioId;
     private CpMaterial cpMaterial;
     private EsRecebimentoItem esRecebimentoItem;
     private String lote;
     private Date fabricacao;
     private Date validade;
     private BigDecimal quant;
     private long srRecno;
     private Set esLoteRemedioBxes = new HashSet(0);
     private Set esInventarioItemLotes = new HashSet(0);

    public EsLoteRemedio() {
    }

	
    public EsLoteRemedio(int loteRemedioId, CpMaterial cpMaterial, EsRecebimentoItem esRecebimentoItem, String lote, Date validade, BigDecimal quant, long srRecno) {
        this.loteRemedioId = loteRemedioId;
        this.cpMaterial = cpMaterial;
        this.esRecebimentoItem = esRecebimentoItem;
        this.lote = lote;
        this.validade = validade;
        this.quant = quant;
        this.srRecno = srRecno;
    }
    public EsLoteRemedio(int loteRemedioId, CpMaterial cpMaterial, EsRecebimentoItem esRecebimentoItem, String lote, Date fabricacao, Date validade, BigDecimal quant, long srRecno, Set esLoteRemedioBxes, Set esInventarioItemLotes) {
       this.loteRemedioId = loteRemedioId;
       this.cpMaterial = cpMaterial;
       this.esRecebimentoItem = esRecebimentoItem;
       this.lote = lote;
       this.fabricacao = fabricacao;
       this.validade = validade;
       this.quant = quant;
       this.srRecno = srRecno;
       this.esLoteRemedioBxes = esLoteRemedioBxes;
       this.esInventarioItemLotes = esInventarioItemLotes;
    }
   
    public int getLoteRemedioId() {
        return this.loteRemedioId;
    }
    
    public void setLoteRemedioId(int loteRemedioId) {
        this.loteRemedioId = loteRemedioId;
    }
    public CpMaterial getCpMaterial() {
        return this.cpMaterial;
    }
    
    public void setCpMaterial(CpMaterial cpMaterial) {
        this.cpMaterial = cpMaterial;
    }
    public EsRecebimentoItem getEsRecebimentoItem() {
        return this.esRecebimentoItem;
    }
    
    public void setEsRecebimentoItem(EsRecebimentoItem esRecebimentoItem) {
        this.esRecebimentoItem = esRecebimentoItem;
    }
    public String getLote() {
        return this.lote;
    }
    
    public void setLote(String lote) {
        this.lote = lote;
    }
    public Date getFabricacao() {
        return this.fabricacao;
    }
    
    public void setFabricacao(Date fabricacao) {
        this.fabricacao = fabricacao;
    }
    public Date getValidade() {
        return this.validade;
    }
    
    public void setValidade(Date validade) {
        this.validade = validade;
    }
    public BigDecimal getQuant() {
        return this.quant;
    }
    
    public void setQuant(BigDecimal quant) {
        this.quant = quant;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }
    public Set getEsLoteRemedioBxes() {
        return this.esLoteRemedioBxes;
    }
    
    public void setEsLoteRemedioBxes(Set esLoteRemedioBxes) {
        this.esLoteRemedioBxes = esLoteRemedioBxes;
    }
    public Set getEsInventarioItemLotes() {
        return this.esInventarioItemLotes;
    }
    
    public void setEsInventarioItemLotes(Set esInventarioItemLotes) {
        this.esInventarioItemLotes = esInventarioItemLotes;
    }




}


