package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * EsLocalizacao generated by hbm2java
 */
public class EsLocalizacao  implements java.io.Serializable {


     private int localizacaoId;
     private String estante;
     private String plateleira;
     private String sala;
     private long srRecno;
     private String secretariaId;
     private Integer depositoId;
     private Integer materialId;
     private Set cpMaterials = new HashSet(0);

    public EsLocalizacao() {
    }

	
    public EsLocalizacao(int localizacaoId, long srRecno) {
        this.localizacaoId = localizacaoId;
        this.srRecno = srRecno;
    }
    public EsLocalizacao(int localizacaoId, String estante, String plateleira, String sala, long srRecno, String secretariaId, Integer depositoId, Integer materialId, Set cpMaterials) {
       this.localizacaoId = localizacaoId;
       this.estante = estante;
       this.plateleira = plateleira;
       this.sala = sala;
       this.srRecno = srRecno;
       this.secretariaId = secretariaId;
       this.depositoId = depositoId;
       this.materialId = materialId;
       this.cpMaterials = cpMaterials;
    }
   
    public int getLocalizacaoId() {
        return this.localizacaoId;
    }
    
    public void setLocalizacaoId(int localizacaoId) {
        this.localizacaoId = localizacaoId;
    }
    public String getEstante() {
        return this.estante;
    }
    
    public void setEstante(String estante) {
        this.estante = estante;
    }
    public String getPlateleira() {
        return this.plateleira;
    }
    
    public void setPlateleira(String plateleira) {
        this.plateleira = plateleira;
    }
    public String getSala() {
        return this.sala;
    }
    
    public void setSala(String sala) {
        this.sala = sala;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }
    public String getSecretariaId() {
        return this.secretariaId;
    }
    
    public void setSecretariaId(String secretariaId) {
        this.secretariaId = secretariaId;
    }
    public Integer getDepositoId() {
        return this.depositoId;
    }
    
    public void setDepositoId(Integer depositoId) {
        this.depositoId = depositoId;
    }
    public Integer getMaterialId() {
        return this.materialId;
    }
    
    public void setMaterialId(Integer materialId) {
        this.materialId = materialId;
    }
    public Set getCpMaterials() {
        return this.cpMaterials;
    }
    
    public void setCpMaterials(Set cpMaterials) {
        this.cpMaterials = cpMaterials;
    }




}


