package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * EsMaterialEstocado generated by hbm2java
 */
public class EsMaterialEstocado  implements java.io.Serializable {


     private int materialEstocadoId;
     private CpDespesa cpDespesa;
     private CpMaterial cpMaterial;
     private CpSecretaria cpSecretaria;
     private EsDeposito esDeposito;
     private String atividade;
     private BigDecimal saldo;
     private long srRecno;
     private int abastecimento;

    public EsMaterialEstocado() {
    }

	
    public EsMaterialEstocado(int materialEstocadoId, CpMaterial cpMaterial, CpSecretaria cpSecretaria, EsDeposito esDeposito, BigDecimal saldo, long srRecno, int abastecimento) {
        this.materialEstocadoId = materialEstocadoId;
        this.cpMaterial = cpMaterial;
        this.cpSecretaria = cpSecretaria;
        this.esDeposito = esDeposito;
        this.saldo = saldo;
        this.srRecno = srRecno;
        this.abastecimento = abastecimento;
    }
    public EsMaterialEstocado(int materialEstocadoId, CpDespesa cpDespesa, CpMaterial cpMaterial, CpSecretaria cpSecretaria, EsDeposito esDeposito, String atividade, BigDecimal saldo, long srRecno, int abastecimento) {
       this.materialEstocadoId = materialEstocadoId;
       this.cpDespesa = cpDespesa;
       this.cpMaterial = cpMaterial;
       this.cpSecretaria = cpSecretaria;
       this.esDeposito = esDeposito;
       this.atividade = atividade;
       this.saldo = saldo;
       this.srRecno = srRecno;
       this.abastecimento = abastecimento;
    }
   
    public int getMaterialEstocadoId() {
        return this.materialEstocadoId;
    }
    
    public void setMaterialEstocadoId(int materialEstocadoId) {
        this.materialEstocadoId = materialEstocadoId;
    }
    public CpDespesa getCpDespesa() {
        return this.cpDespesa;
    }
    
    public void setCpDespesa(CpDespesa cpDespesa) {
        this.cpDespesa = cpDespesa;
    }
    public CpMaterial getCpMaterial() {
        return this.cpMaterial;
    }
    
    public void setCpMaterial(CpMaterial cpMaterial) {
        this.cpMaterial = cpMaterial;
    }
    public CpSecretaria getCpSecretaria() {
        return this.cpSecretaria;
    }
    
    public void setCpSecretaria(CpSecretaria cpSecretaria) {
        this.cpSecretaria = cpSecretaria;
    }
    public EsDeposito getEsDeposito() {
        return this.esDeposito;
    }
    
    public void setEsDeposito(EsDeposito esDeposito) {
        this.esDeposito = esDeposito;
    }
    public String getAtividade() {
        return this.atividade;
    }
    
    public void setAtividade(String atividade) {
        this.atividade = atividade;
    }
    public BigDecimal getSaldo() {
        return this.saldo;
    }
    
    public void setSaldo(BigDecimal saldo) {
        this.saldo = saldo;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }
    public int getAbastecimento() {
        return this.abastecimento;
    }
    
    public void setAbastecimento(int abastecimento) {
        this.abastecimento = abastecimento;
    }




}


