package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1



/**
 * EsMotoristaVeic generated by hbm2java
 */
public class EsMotoristaVeic  implements java.io.Serializable {


     private int motoristaVeicId;
     private FrVeiculo frVeiculo;
     private Integer motoristaId;
     private long srRecno;

    public EsMotoristaVeic() {
    }

	
    public EsMotoristaVeic(int motoristaVeicId, long srRecno) {
        this.motoristaVeicId = motoristaVeicId;
        this.srRecno = srRecno;
    }
    public EsMotoristaVeic(int motoristaVeicId, FrVeiculo frVeiculo, Integer motoristaId, long srRecno) {
       this.motoristaVeicId = motoristaVeicId;
       this.frVeiculo = frVeiculo;
       this.motoristaId = motoristaId;
       this.srRecno = srRecno;
    }
   
    public int getMotoristaVeicId() {
        return this.motoristaVeicId;
    }
    
    public void setMotoristaVeicId(int motoristaVeicId) {
        this.motoristaVeicId = motoristaVeicId;
    }
    public FrVeiculo getFrVeiculo() {
        return this.frVeiculo;
    }
    
    public void setFrVeiculo(FrVeiculo frVeiculo) {
        this.frVeiculo = frVeiculo;
    }
    public Integer getMotoristaId() {
        return this.motoristaId;
    }
    
    public void setMotoristaId(Integer motoristaId) {
        this.motoristaId = motoristaId;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }




}


