package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * EsMulta generated by hbm2java
 */
public class EsMulta  implements java.io.Serializable {


     private int multaId;
     private FrMotorista frMotorista;
     private FrVeiculo frVeiculo;
     private int tipoMulta;
     private Date data;
     private Date hora;
     private String orgaoId;
     private String unidadeId;
     private Integer orgaoUnidadeId;
     private String descricao;
     private BigDecimal valor;
     private long srRecno;

    public EsMulta() {
    }

	
    public EsMulta(int multaId, int tipoMulta, Date data, Date hora, long srRecno) {
        this.multaId = multaId;
        this.tipoMulta = tipoMulta;
        this.data = data;
        this.hora = hora;
        this.srRecno = srRecno;
    }
    public EsMulta(int multaId, FrMotorista frMotorista, FrVeiculo frVeiculo, int tipoMulta, Date data, Date hora, String orgaoId, String unidadeId, Integer orgaoUnidadeId, String descricao, BigDecimal valor, long srRecno) {
       this.multaId = multaId;
       this.frMotorista = frMotorista;
       this.frVeiculo = frVeiculo;
       this.tipoMulta = tipoMulta;
       this.data = data;
       this.hora = hora;
       this.orgaoId = orgaoId;
       this.unidadeId = unidadeId;
       this.orgaoUnidadeId = orgaoUnidadeId;
       this.descricao = descricao;
       this.valor = valor;
       this.srRecno = srRecno;
    }
   
    public int getMultaId() {
        return this.multaId;
    }
    
    public void setMultaId(int multaId) {
        this.multaId = multaId;
    }
    public FrMotorista getFrMotorista() {
        return this.frMotorista;
    }
    
    public void setFrMotorista(FrMotorista frMotorista) {
        this.frMotorista = frMotorista;
    }
    public FrVeiculo getFrVeiculo() {
        return this.frVeiculo;
    }
    
    public void setFrVeiculo(FrVeiculo frVeiculo) {
        this.frVeiculo = frVeiculo;
    }
    public int getTipoMulta() {
        return this.tipoMulta;
    }
    
    public void setTipoMulta(int tipoMulta) {
        this.tipoMulta = tipoMulta;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public Date getHora() {
        return this.hora;
    }
    
    public void setHora(Date hora) {
        this.hora = hora;
    }
    public String getOrgaoId() {
        return this.orgaoId;
    }
    
    public void setOrgaoId(String orgaoId) {
        this.orgaoId = orgaoId;
    }
    public String getUnidadeId() {
        return this.unidadeId;
    }
    
    public void setUnidadeId(String unidadeId) {
        this.unidadeId = unidadeId;
    }
    public Integer getOrgaoUnidadeId() {
        return this.orgaoUnidadeId;
    }
    
    public void setOrgaoUnidadeId(Integer orgaoUnidadeId) {
        this.orgaoUnidadeId = orgaoUnidadeId;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }




}


