package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * EsPlanilhaBordo generated by hbm2java
 */
public class EsPlanilhaBordo  implements java.io.Serializable {


     private int planilhaId;
     private CpSecretaria cpSecretaria;
     private int veiculoId;
     private Date gacesso;
     private long srRecno;
     private Set esPlanilhaBordoItems = new HashSet(0);

    public EsPlanilhaBordo() {
    }

	
    public EsPlanilhaBordo(int planilhaId, CpSecretaria cpSecretaria, int veiculoId, Date gacesso, long srRecno) {
        this.planilhaId = planilhaId;
        this.cpSecretaria = cpSecretaria;
        this.veiculoId = veiculoId;
        this.gacesso = gacesso;
        this.srRecno = srRecno;
    }
    public EsPlanilhaBordo(int planilhaId, CpSecretaria cpSecretaria, int veiculoId, Date gacesso, long srRecno, Set esPlanilhaBordoItems) {
       this.planilhaId = planilhaId;
       this.cpSecretaria = cpSecretaria;
       this.veiculoId = veiculoId;
       this.gacesso = gacesso;
       this.srRecno = srRecno;
       this.esPlanilhaBordoItems = esPlanilhaBordoItems;
    }
   
    public int getPlanilhaId() {
        return this.planilhaId;
    }
    
    public void setPlanilhaId(int planilhaId) {
        this.planilhaId = planilhaId;
    }
    public CpSecretaria getCpSecretaria() {
        return this.cpSecretaria;
    }
    
    public void setCpSecretaria(CpSecretaria cpSecretaria) {
        this.cpSecretaria = cpSecretaria;
    }
    public int getVeiculoId() {
        return this.veiculoId;
    }
    
    public void setVeiculoId(int veiculoId) {
        this.veiculoId = veiculoId;
    }
    public Date getGacesso() {
        return this.gacesso;
    }
    
    public void setGacesso(Date gacesso) {
        this.gacesso = gacesso;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }
    public Set getEsPlanilhaBordoItems() {
        return this.esPlanilhaBordoItems;
    }
    
    public void setEsPlanilhaBordoItems(Set esPlanilhaBordoItems) {
        this.esPlanilhaBordoItems = esPlanilhaBordoItems;
    }




}


