package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1



/**
 * EsPlanilhaBordoItemId generated by hbm2java
 */
public class EsPlanilhaBordoItemId  implements java.io.Serializable {


     private int planilhaItemId;
     private int planilhaId;

    public EsPlanilhaBordoItemId() {
    }

    public EsPlanilhaBordoItemId(int planilhaItemId, int planilhaId) {
       this.planilhaItemId = planilhaItemId;
       this.planilhaId = planilhaId;
    }
   
    public int getPlanilhaItemId() {
        return this.planilhaItemId;
    }
    
    public void setPlanilhaItemId(int planilhaItemId) {
        this.planilhaItemId = planilhaItemId;
    }
    public int getPlanilhaId() {
        return this.planilhaId;
    }
    
    public void setPlanilhaId(int planilhaId) {
        this.planilhaId = planilhaId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EsPlanilhaBordoItemId) ) return false;
		 EsPlanilhaBordoItemId castOther = ( EsPlanilhaBordoItemId ) other; 
         
		 return (this.getPlanilhaItemId()==castOther.getPlanilhaItemId())
 && (this.getPlanilhaId()==castOther.getPlanilhaId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPlanilhaItemId();
         result = 37 * result + this.getPlanilhaId();
         return result;
   }   


}


