package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * EsPlanilhaBordoItem generated by hbm2java
 */
public class EsPlanilhaBordoItem  implements java.io.Serializable {


     private EsPlanilhaBordoItemId id;
     private EsPlanilhaBordo esPlanilhaBordo;
     private FrMotorista frMotorista;
     private Date dataSaida;
     private String horaSaida;
     private int quilometroInicial;
     private String localSaida;
     private String destino;
     private Date dataChegada;
     private String horaChegada;
     private int quilometroFinal;
     private Date gacesso;
     private long srRecno;
     private String quantCombustivel;

    public EsPlanilhaBordoItem() {
    }

	
    public EsPlanilhaBordoItem(EsPlanilhaBordoItemId id, EsPlanilhaBordo esPlanilhaBordo, FrMotorista frMotorista, Date dataSaida, String horaSaida, int quilometroInicial, String localSaida, String destino, Date dataChegada, String horaChegada, int quilometroFinal, Date gacesso, long srRecno) {
        this.id = id;
        this.esPlanilhaBordo = esPlanilhaBordo;
        this.frMotorista = frMotorista;
        this.dataSaida = dataSaida;
        this.horaSaida = horaSaida;
        this.quilometroInicial = quilometroInicial;
        this.localSaida = localSaida;
        this.destino = destino;
        this.dataChegada = dataChegada;
        this.horaChegada = horaChegada;
        this.quilometroFinal = quilometroFinal;
        this.gacesso = gacesso;
        this.srRecno = srRecno;
    }
    public EsPlanilhaBordoItem(EsPlanilhaBordoItemId id, EsPlanilhaBordo esPlanilhaBordo, FrMotorista frMotorista, Date dataSaida, String horaSaida, int quilometroInicial, String localSaida, String destino, Date dataChegada, String horaChegada, int quilometroFinal, Date gacesso, long srRecno, String quantCombustivel) {
       this.id = id;
       this.esPlanilhaBordo = esPlanilhaBordo;
       this.frMotorista = frMotorista;
       this.dataSaida = dataSaida;
       this.horaSaida = horaSaida;
       this.quilometroInicial = quilometroInicial;
       this.localSaida = localSaida;
       this.destino = destino;
       this.dataChegada = dataChegada;
       this.horaChegada = horaChegada;
       this.quilometroFinal = quilometroFinal;
       this.gacesso = gacesso;
       this.srRecno = srRecno;
       this.quantCombustivel = quantCombustivel;
    }
   
    public EsPlanilhaBordoItemId getId() {
        return this.id;
    }
    
    public void setId(EsPlanilhaBordoItemId id) {
        this.id = id;
    }
    public EsPlanilhaBordo getEsPlanilhaBordo() {
        return this.esPlanilhaBordo;
    }
    
    public void setEsPlanilhaBordo(EsPlanilhaBordo esPlanilhaBordo) {
        this.esPlanilhaBordo = esPlanilhaBordo;
    }
    public FrMotorista getFrMotorista() {
        return this.frMotorista;
    }
    
    public void setFrMotorista(FrMotorista frMotorista) {
        this.frMotorista = frMotorista;
    }
    public Date getDataSaida() {
        return this.dataSaida;
    }
    
    public void setDataSaida(Date dataSaida) {
        this.dataSaida = dataSaida;
    }
    public String getHoraSaida() {
        return this.horaSaida;
    }
    
    public void setHoraSaida(String horaSaida) {
        this.horaSaida = horaSaida;
    }
    public int getQuilometroInicial() {
        return this.quilometroInicial;
    }
    
    public void setQuilometroInicial(int quilometroInicial) {
        this.quilometroInicial = quilometroInicial;
    }
    public String getLocalSaida() {
        return this.localSaida;
    }
    
    public void setLocalSaida(String localSaida) {
        this.localSaida = localSaida;
    }
    public String getDestino() {
        return this.destino;
    }
    
    public void setDestino(String destino) {
        this.destino = destino;
    }
    public Date getDataChegada() {
        return this.dataChegada;
    }
    
    public void setDataChegada(Date dataChegada) {
        this.dataChegada = dataChegada;
    }
    public String getHoraChegada() {
        return this.horaChegada;
    }
    
    public void setHoraChegada(String horaChegada) {
        this.horaChegada = horaChegada;
    }
    public int getQuilometroFinal() {
        return this.quilometroFinal;
    }
    
    public void setQuilometroFinal(int quilometroFinal) {
        this.quilometroFinal = quilometroFinal;
    }
    public Date getGacesso() {
        return this.gacesso;
    }
    
    public void setGacesso(Date gacesso) {
        this.gacesso = gacesso;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }
    public String getQuantCombustivel() {
        return this.quantCombustivel;
    }
    
    public void setQuantCombustivel(String quantCombustivel) {
        this.quantCombustivel = quantCombustivel;
    }




}


