package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * EsProcessoInventario generated by hbm2java
 */
public class EsProcessoInventario  implements java.io.Serializable {


     private int processoInventarioId;
     private EsComissaoInventario esComissaoInventario;
     private EsComInventarioMembro esComInventarioMembro;
     private Date data;
     private String gusuarioId;
     private String motivo;
     private String status;
     private long srRecno;
     private Set esRetiradas = new HashSet(0);
     private Set esProcessoInventarioItems = new HashSet(0);
     private Set esRecebimentos = new HashSet(0);

    public EsProcessoInventario() {
    }

	
    public EsProcessoInventario(int processoInventarioId, EsComissaoInventario esComissaoInventario, EsComInventarioMembro esComInventarioMembro, Date data, String gusuarioId, String motivo, String status, long srRecno) {
        this.processoInventarioId = processoInventarioId;
        this.esComissaoInventario = esComissaoInventario;
        this.esComInventarioMembro = esComInventarioMembro;
        this.data = data;
        this.gusuarioId = gusuarioId;
        this.motivo = motivo;
        this.status = status;
        this.srRecno = srRecno;
    }
    public EsProcessoInventario(int processoInventarioId, EsComissaoInventario esComissaoInventario, EsComInventarioMembro esComInventarioMembro, Date data, String gusuarioId, String motivo, String status, long srRecno, Set esRetiradas, Set esProcessoInventarioItems, Set esRecebimentos) {
       this.processoInventarioId = processoInventarioId;
       this.esComissaoInventario = esComissaoInventario;
       this.esComInventarioMembro = esComInventarioMembro;
       this.data = data;
       this.gusuarioId = gusuarioId;
       this.motivo = motivo;
       this.status = status;
       this.srRecno = srRecno;
       this.esRetiradas = esRetiradas;
       this.esProcessoInventarioItems = esProcessoInventarioItems;
       this.esRecebimentos = esRecebimentos;
    }
   
    public int getProcessoInventarioId() {
        return this.processoInventarioId;
    }
    
    public void setProcessoInventarioId(int processoInventarioId) {
        this.processoInventarioId = processoInventarioId;
    }
    public EsComissaoInventario getEsComissaoInventario() {
        return this.esComissaoInventario;
    }
    
    public void setEsComissaoInventario(EsComissaoInventario esComissaoInventario) {
        this.esComissaoInventario = esComissaoInventario;
    }
    public EsComInventarioMembro getEsComInventarioMembro() {
        return this.esComInventarioMembro;
    }
    
    public void setEsComInventarioMembro(EsComInventarioMembro esComInventarioMembro) {
        this.esComInventarioMembro = esComInventarioMembro;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public String getGusuarioId() {
        return this.gusuarioId;
    }
    
    public void setGusuarioId(String gusuarioId) {
        this.gusuarioId = gusuarioId;
    }
    public String getMotivo() {
        return this.motivo;
    }
    
    public void setMotivo(String motivo) {
        this.motivo = motivo;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }
    public Set getEsRetiradas() {
        return this.esRetiradas;
    }
    
    public void setEsRetiradas(Set esRetiradas) {
        this.esRetiradas = esRetiradas;
    }
    public Set getEsProcessoInventarioItems() {
        return this.esProcessoInventarioItems;
    }
    
    public void setEsProcessoInventarioItems(Set esProcessoInventarioItems) {
        this.esProcessoInventarioItems = esProcessoInventarioItems;
    }
    public Set getEsRecebimentos() {
        return this.esRecebimentos;
    }
    
    public void setEsRecebimentos(Set esRecebimentos) {
        this.esRecebimentos = esRecebimentos;
    }




}


