package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * EsProcessoInventarioItem generated by hbm2java
 */
public class EsProcessoInventarioItem  implements java.io.Serializable {


     private int processoInventarioItemId;
     private EsProcessoInventario esProcessoInventario;
     private int depositoId;
     private String secretariaId;
     private String atividade;
     private int materialId;
     private BigDecimal quant;
     private BigDecimal quantFisica;
     private long srRecno;
     private Set esRecebimentoItems = new HashSet(0);
     private Set esRetiradaItems = new HashSet(0);

    public EsProcessoInventarioItem() {
    }

	
    public EsProcessoInventarioItem(int processoInventarioItemId, EsProcessoInventario esProcessoInventario, int depositoId, String secretariaId, String atividade, int materialId, BigDecimal quant, long srRecno) {
        this.processoInventarioItemId = processoInventarioItemId;
        this.esProcessoInventario = esProcessoInventario;
        this.depositoId = depositoId;
        this.secretariaId = secretariaId;
        this.atividade = atividade;
        this.materialId = materialId;
        this.quant = quant;
        this.srRecno = srRecno;
    }
    public EsProcessoInventarioItem(int processoInventarioItemId, EsProcessoInventario esProcessoInventario, int depositoId, String secretariaId, String atividade, int materialId, BigDecimal quant, BigDecimal quantFisica, long srRecno, Set esRecebimentoItems, Set esRetiradaItems) {
       this.processoInventarioItemId = processoInventarioItemId;
       this.esProcessoInventario = esProcessoInventario;
       this.depositoId = depositoId;
       this.secretariaId = secretariaId;
       this.atividade = atividade;
       this.materialId = materialId;
       this.quant = quant;
       this.quantFisica = quantFisica;
       this.srRecno = srRecno;
       this.esRecebimentoItems = esRecebimentoItems;
       this.esRetiradaItems = esRetiradaItems;
    }
   
    public int getProcessoInventarioItemId() {
        return this.processoInventarioItemId;
    }
    
    public void setProcessoInventarioItemId(int processoInventarioItemId) {
        this.processoInventarioItemId = processoInventarioItemId;
    }
    public EsProcessoInventario getEsProcessoInventario() {
        return this.esProcessoInventario;
    }
    
    public void setEsProcessoInventario(EsProcessoInventario esProcessoInventario) {
        this.esProcessoInventario = esProcessoInventario;
    }
    public int getDepositoId() {
        return this.depositoId;
    }
    
    public void setDepositoId(int depositoId) {
        this.depositoId = depositoId;
    }
    public String getSecretariaId() {
        return this.secretariaId;
    }
    
    public void setSecretariaId(String secretariaId) {
        this.secretariaId = secretariaId;
    }
    public String getAtividade() {
        return this.atividade;
    }
    
    public void setAtividade(String atividade) {
        this.atividade = atividade;
    }
    public int getMaterialId() {
        return this.materialId;
    }
    
    public void setMaterialId(int materialId) {
        this.materialId = materialId;
    }
    public BigDecimal getQuant() {
        return this.quant;
    }
    
    public void setQuant(BigDecimal quant) {
        this.quant = quant;
    }
    public BigDecimal getQuantFisica() {
        return this.quantFisica;
    }
    
    public void setQuantFisica(BigDecimal quantFisica) {
        this.quantFisica = quantFisica;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }
    public Set getEsRecebimentoItems() {
        return this.esRecebimentoItems;
    }
    
    public void setEsRecebimentoItems(Set esRecebimentoItems) {
        this.esRecebimentoItems = esRecebimentoItems;
    }
    public Set getEsRetiradaItems() {
        return this.esRetiradaItems;
    }
    
    public void setEsRetiradaItems(Set esRetiradaItems) {
        this.esRetiradaItems = esRetiradaItems;
    }




}


