package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * EsRetirada generated by hbm2java
 */
public class EsRetirada  implements java.io.Serializable {


     private int retiradaId;
     private CpCcusto cpCcusto;
     private CpSecretaria cpSecretaria;
     private EsDeposito esDeposito;
     private EsProcessoInventario esProcessoInventario;
     private EsRequisicao esRequisicao;
     private Gusuario gusuario;
     private LcCombDispBx lcCombDispBx;
     private Date data;
     private int tipo;
     private String atividade;
     private String gusuarioId;
     private long srRecno;
     private Date gacesso;
     private String cancelada;
     private Date datCancela;
     private String motCancela;
     private String obs;
     private String solicitanteId;
     private Date gacessoInclusao;
     private Integer lcBloqueio;
     private int abastecimento;
     private Set esRetiradaItems = new HashSet(0);
     private Set esConsumoContabs = new HashSet(0);

    public EsRetirada() {
    }

	
    public EsRetirada(int retiradaId, CpSecretaria cpSecretaria, EsDeposito esDeposito, Date data, int tipo, long srRecno, String cancelada, int abastecimento) {
        this.retiradaId = retiradaId;
        this.cpSecretaria = cpSecretaria;
        this.esDeposito = esDeposito;
        this.data = data;
        this.tipo = tipo;
        this.srRecno = srRecno;
        this.cancelada = cancelada;
        this.abastecimento = abastecimento;
    }
    public EsRetirada(int retiradaId, CpCcusto cpCcusto, CpSecretaria cpSecretaria, EsDeposito esDeposito, EsProcessoInventario esProcessoInventario, EsRequisicao esRequisicao, Gusuario gusuario, LcCombDispBx lcCombDispBx, Date data, int tipo, String atividade, String gusuarioId, long srRecno, Date gacesso, String cancelada, Date datCancela, String motCancela, String obs, String solicitanteId, Date gacessoInclusao, Integer lcBloqueio, int abastecimento, Set esRetiradaItems, Set esConsumoContabs) {
       this.retiradaId = retiradaId;
       this.cpCcusto = cpCcusto;
       this.cpSecretaria = cpSecretaria;
       this.esDeposito = esDeposito;
       this.esProcessoInventario = esProcessoInventario;
       this.esRequisicao = esRequisicao;
       this.gusuario = gusuario;
       this.lcCombDispBx = lcCombDispBx;
       this.data = data;
       this.tipo = tipo;
       this.atividade = atividade;
       this.gusuarioId = gusuarioId;
       this.srRecno = srRecno;
       this.gacesso = gacesso;
       this.cancelada = cancelada;
       this.datCancela = datCancela;
       this.motCancela = motCancela;
       this.obs = obs;
       this.solicitanteId = solicitanteId;
       this.gacessoInclusao = gacessoInclusao;
       this.lcBloqueio = lcBloqueio;
       this.abastecimento = abastecimento;
       this.esRetiradaItems = esRetiradaItems;
       this.esConsumoContabs = esConsumoContabs;
    }
   
    public int getRetiradaId() {
        return this.retiradaId;
    }
    
    public void setRetiradaId(int retiradaId) {
        this.retiradaId = retiradaId;
    }
    public CpCcusto getCpCcusto() {
        return this.cpCcusto;
    }
    
    public void setCpCcusto(CpCcusto cpCcusto) {
        this.cpCcusto = cpCcusto;
    }
    public CpSecretaria getCpSecretaria() {
        return this.cpSecretaria;
    }
    
    public void setCpSecretaria(CpSecretaria cpSecretaria) {
        this.cpSecretaria = cpSecretaria;
    }
    public EsDeposito getEsDeposito() {
        return this.esDeposito;
    }
    
    public void setEsDeposito(EsDeposito esDeposito) {
        this.esDeposito = esDeposito;
    }
    public EsProcessoInventario getEsProcessoInventario() {
        return this.esProcessoInventario;
    }
    
    public void setEsProcessoInventario(EsProcessoInventario esProcessoInventario) {
        this.esProcessoInventario = esProcessoInventario;
    }
    public EsRequisicao getEsRequisicao() {
        return this.esRequisicao;
    }
    
    public void setEsRequisicao(EsRequisicao esRequisicao) {
        this.esRequisicao = esRequisicao;
    }
    public Gusuario getGusuario() {
        return this.gusuario;
    }
    
    public void setGusuario(Gusuario gusuario) {
        this.gusuario = gusuario;
    }
    public LcCombDispBx getLcCombDispBx() {
        return this.lcCombDispBx;
    }
    
    public void setLcCombDispBx(LcCombDispBx lcCombDispBx) {
        this.lcCombDispBx = lcCombDispBx;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public int getTipo() {
        return this.tipo;
    }
    
    public void setTipo(int tipo) {
        this.tipo = tipo;
    }
    public String getAtividade() {
        return this.atividade;
    }
    
    public void setAtividade(String atividade) {
        this.atividade = atividade;
    }
    public String getGusuarioId() {
        return this.gusuarioId;
    }
    
    public void setGusuarioId(String gusuarioId) {
        this.gusuarioId = gusuarioId;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }
    public Date getGacesso() {
        return this.gacesso;
    }
    
    public void setGacesso(Date gacesso) {
        this.gacesso = gacesso;
    }
    public String getCancelada() {
        return this.cancelada;
    }
    
    public void setCancelada(String cancelada) {
        this.cancelada = cancelada;
    }
    public Date getDatCancela() {
        return this.datCancela;
    }
    
    public void setDatCancela(Date datCancela) {
        this.datCancela = datCancela;
    }
    public String getMotCancela() {
        return this.motCancela;
    }
    
    public void setMotCancela(String motCancela) {
        this.motCancela = motCancela;
    }
    public String getObs() {
        return this.obs;
    }
    
    public void setObs(String obs) {
        this.obs = obs;
    }
    public String getSolicitanteId() {
        return this.solicitanteId;
    }
    
    public void setSolicitanteId(String solicitanteId) {
        this.solicitanteId = solicitanteId;
    }
    public Date getGacessoInclusao() {
        return this.gacessoInclusao;
    }
    
    public void setGacessoInclusao(Date gacessoInclusao) {
        this.gacessoInclusao = gacessoInclusao;
    }
    public Integer getLcBloqueio() {
        return this.lcBloqueio;
    }
    
    public void setLcBloqueio(Integer lcBloqueio) {
        this.lcBloqueio = lcBloqueio;
    }
    public int getAbastecimento() {
        return this.abastecimento;
    }
    
    public void setAbastecimento(int abastecimento) {
        this.abastecimento = abastecimento;
    }
    public Set getEsRetiradaItems() {
        return this.esRetiradaItems;
    }
    
    public void setEsRetiradaItems(Set esRetiradaItems) {
        this.esRetiradaItems = esRetiradaItems;
    }
    public Set getEsConsumoContabs() {
        return this.esConsumoContabs;
    }
    
    public void setEsConsumoContabs(Set esConsumoContabs) {
        this.esConsumoContabs = esConsumoContabs;
    }




}


