package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * EsRetiradaItem generated by hbm2java
 */
public class EsRetiradaItem  implements java.io.Serializable {


     private int retItemId;
     private CpMaterial cpMaterial;
     private CpMedida cpMedida;
     private EsInventarioItem esInventarioItem;
     private EsProcessoInventarioItem esProcessoInventarioItem;
     private EsRecebimentoItem esRecebimentoItem;
     private EsRequisicaoItem esRequisicaoItem;
     private EsRetirada esRetirada;
     private int itemId;
     private String unid;
     private BigDecimal quant;
     private long srRecno;
     private Date gacessoInclusao;
     private Set esCustoReals = new HashSet(0);
     private Set esLoteRemedioBxes = new HashSet(0);
     private Set esRetiradaItemCombs = new HashSet(0);

    public EsRetiradaItem() {
    }

	
    public EsRetiradaItem(int retItemId, CpMaterial cpMaterial, EsRetirada esRetirada, int itemId, BigDecimal quant, long srRecno) {
        this.retItemId = retItemId;
        this.cpMaterial = cpMaterial;
        this.esRetirada = esRetirada;
        this.itemId = itemId;
        this.quant = quant;
        this.srRecno = srRecno;
    }
    public EsRetiradaItem(int retItemId, CpMaterial cpMaterial, CpMedida cpMedida, EsInventarioItem esInventarioItem, EsProcessoInventarioItem esProcessoInventarioItem, EsRecebimentoItem esRecebimentoItem, EsRequisicaoItem esRequisicaoItem, EsRetirada esRetirada, int itemId, String unid, BigDecimal quant, long srRecno, Date gacessoInclusao, Set esCustoReals, Set esLoteRemedioBxes, Set esRetiradaItemCombs) {
       this.retItemId = retItemId;
       this.cpMaterial = cpMaterial;
       this.cpMedida = cpMedida;
       this.esInventarioItem = esInventarioItem;
       this.esProcessoInventarioItem = esProcessoInventarioItem;
       this.esRecebimentoItem = esRecebimentoItem;
       this.esRequisicaoItem = esRequisicaoItem;
       this.esRetirada = esRetirada;
       this.itemId = itemId;
       this.unid = unid;
       this.quant = quant;
       this.srRecno = srRecno;
       this.gacessoInclusao = gacessoInclusao;
       this.esCustoReals = esCustoReals;
       this.esLoteRemedioBxes = esLoteRemedioBxes;
       this.esRetiradaItemCombs = esRetiradaItemCombs;
    }
   
    public int getRetItemId() {
        return this.retItemId;
    }
    
    public void setRetItemId(int retItemId) {
        this.retItemId = retItemId;
    }
    public CpMaterial getCpMaterial() {
        return this.cpMaterial;
    }
    
    public void setCpMaterial(CpMaterial cpMaterial) {
        this.cpMaterial = cpMaterial;
    }
    public CpMedida getCpMedida() {
        return this.cpMedida;
    }
    
    public void setCpMedida(CpMedida cpMedida) {
        this.cpMedida = cpMedida;
    }
    public EsInventarioItem getEsInventarioItem() {
        return this.esInventarioItem;
    }
    
    public void setEsInventarioItem(EsInventarioItem esInventarioItem) {
        this.esInventarioItem = esInventarioItem;
    }
    public EsProcessoInventarioItem getEsProcessoInventarioItem() {
        return this.esProcessoInventarioItem;
    }
    
    public void setEsProcessoInventarioItem(EsProcessoInventarioItem esProcessoInventarioItem) {
        this.esProcessoInventarioItem = esProcessoInventarioItem;
    }
    public EsRecebimentoItem getEsRecebimentoItem() {
        return this.esRecebimentoItem;
    }
    
    public void setEsRecebimentoItem(EsRecebimentoItem esRecebimentoItem) {
        this.esRecebimentoItem = esRecebimentoItem;
    }
    public EsRequisicaoItem getEsRequisicaoItem() {
        return this.esRequisicaoItem;
    }
    
    public void setEsRequisicaoItem(EsRequisicaoItem esRequisicaoItem) {
        this.esRequisicaoItem = esRequisicaoItem;
    }
    public EsRetirada getEsRetirada() {
        return this.esRetirada;
    }
    
    public void setEsRetirada(EsRetirada esRetirada) {
        this.esRetirada = esRetirada;
    }
    public int getItemId() {
        return this.itemId;
    }
    
    public void setItemId(int itemId) {
        this.itemId = itemId;
    }
    public String getUnid() {
        return this.unid;
    }
    
    public void setUnid(String unid) {
        this.unid = unid;
    }
    public BigDecimal getQuant() {
        return this.quant;
    }
    
    public void setQuant(BigDecimal quant) {
        this.quant = quant;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }
    public Date getGacessoInclusao() {
        return this.gacessoInclusao;
    }
    
    public void setGacessoInclusao(Date gacessoInclusao) {
        this.gacessoInclusao = gacessoInclusao;
    }
    public Set getEsCustoReals() {
        return this.esCustoReals;
    }
    
    public void setEsCustoReals(Set esCustoReals) {
        this.esCustoReals = esCustoReals;
    }
    public Set getEsLoteRemedioBxes() {
        return this.esLoteRemedioBxes;
    }
    
    public void setEsLoteRemedioBxes(Set esLoteRemedioBxes) {
        this.esLoteRemedioBxes = esLoteRemedioBxes;
    }
    public Set getEsRetiradaItemCombs() {
        return this.esRetiradaItemCombs;
    }
    
    public void setEsRetiradaItemCombs(Set esRetiradaItemCombs) {
        this.esRetiradaItemCombs = esRetiradaItemCombs;
    }




}


