package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * EsRequisicaoDevolucao generated by hbm2java
 */
public class EsRequisicaoDevolucao  implements java.io.Serializable {


     private int requisicaoDevolucaoId;
     private EsRequisicao esRequisicao;
     private Date data;
     private Date hora;
     private String motivo;
     private String gusuarioId;
     private long srRecno;
     private Date gacesso;

    public EsRequisicaoDevolucao() {
    }

    public EsRequisicaoDevolucao(int requisicaoDevolucaoId, EsRequisicao esRequisicao, Date data, Date hora, String motivo, String gusuarioId, long srRecno, Date gacesso) {
       this.requisicaoDevolucaoId = requisicaoDevolucaoId;
       this.esRequisicao = esRequisicao;
       this.data = data;
       this.hora = hora;
       this.motivo = motivo;
       this.gusuarioId = gusuarioId;
       this.srRecno = srRecno;
       this.gacesso = gacesso;
    }
   
    public int getRequisicaoDevolucaoId() {
        return this.requisicaoDevolucaoId;
    }
    
    public void setRequisicaoDevolucaoId(int requisicaoDevolucaoId) {
        this.requisicaoDevolucaoId = requisicaoDevolucaoId;
    }
    public EsRequisicao getEsRequisicao() {
        return this.esRequisicao;
    }
    
    public void setEsRequisicao(EsRequisicao esRequisicao) {
        this.esRequisicao = esRequisicao;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public Date getHora() {
        return this.hora;
    }
    
    public void setHora(Date hora) {
        this.hora = hora;
    }
    public String getMotivo() {
        return this.motivo;
    }
    
    public void setMotivo(String motivo) {
        this.motivo = motivo;
    }
    public String getGusuarioId() {
        return this.gusuarioId;
    }
    
    public void setGusuarioId(String gusuarioId) {
        this.gusuarioId = gusuarioId;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }
    public Date getGacesso() {
        return this.gacesso;
    }
    
    public void setGacesso(Date gacesso) {
        this.gacesso = gacesso;
    }




}


