package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * EsRequisicao generated by hbm2java
 */
public class EsRequisicao  implements java.io.Serializable {


     private int requisicaoId;
     private CpCcusto cpCcusto;
     private CpSecretaria cpSecretaria;
     private EsDeposito esDeposito;
     private Date data;
     private String atividade;
     private int status;
     private String gusuarioId;
     private long srRecno;
     private Date datCancel;
     private String motCancel;
     private String usuCancel;
     private Integer retiradaId;
     private String solicitanteId;
     private Set esRetiradas = new HashSet(0);
     private Set esRequisicaoDevolucaos = new HashSet(0);
     private Set esRequisicaoItems = new HashSet(0);

    public EsRequisicao() {
    }

	
    public EsRequisicao(int requisicaoId, CpSecretaria cpSecretaria, EsDeposito esDeposito, Date data, int status, long srRecno) {
        this.requisicaoId = requisicaoId;
        this.cpSecretaria = cpSecretaria;
        this.esDeposito = esDeposito;
        this.data = data;
        this.status = status;
        this.srRecno = srRecno;
    }
    public EsRequisicao(int requisicaoId, CpCcusto cpCcusto, CpSecretaria cpSecretaria, EsDeposito esDeposito, Date data, String atividade, int status, String gusuarioId, long srRecno, Date datCancel, String motCancel, String usuCancel, Integer retiradaId, String solicitanteId, Set esRetiradas, Set esRequisicaoDevolucaos, Set esRequisicaoItems) {
       this.requisicaoId = requisicaoId;
       this.cpCcusto = cpCcusto;
       this.cpSecretaria = cpSecretaria;
       this.esDeposito = esDeposito;
       this.data = data;
       this.atividade = atividade;
       this.status = status;
       this.gusuarioId = gusuarioId;
       this.srRecno = srRecno;
       this.datCancel = datCancel;
       this.motCancel = motCancel;
       this.usuCancel = usuCancel;
       this.retiradaId = retiradaId;
       this.solicitanteId = solicitanteId;
       this.esRetiradas = esRetiradas;
       this.esRequisicaoDevolucaos = esRequisicaoDevolucaos;
       this.esRequisicaoItems = esRequisicaoItems;
    }
   
    public int getRequisicaoId() {
        return this.requisicaoId;
    }
    
    public void setRequisicaoId(int requisicaoId) {
        this.requisicaoId = requisicaoId;
    }
    public CpCcusto getCpCcusto() {
        return this.cpCcusto;
    }
    
    public void setCpCcusto(CpCcusto cpCcusto) {
        this.cpCcusto = cpCcusto;
    }
    public CpSecretaria getCpSecretaria() {
        return this.cpSecretaria;
    }
    
    public void setCpSecretaria(CpSecretaria cpSecretaria) {
        this.cpSecretaria = cpSecretaria;
    }
    public EsDeposito getEsDeposito() {
        return this.esDeposito;
    }
    
    public void setEsDeposito(EsDeposito esDeposito) {
        this.esDeposito = esDeposito;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public String getAtividade() {
        return this.atividade;
    }
    
    public void setAtividade(String atividade) {
        this.atividade = atividade;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }
    public String getGusuarioId() {
        return this.gusuarioId;
    }
    
    public void setGusuarioId(String gusuarioId) {
        this.gusuarioId = gusuarioId;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }
    public Date getDatCancel() {
        return this.datCancel;
    }
    
    public void setDatCancel(Date datCancel) {
        this.datCancel = datCancel;
    }
    public String getMotCancel() {
        return this.motCancel;
    }
    
    public void setMotCancel(String motCancel) {
        this.motCancel = motCancel;
    }
    public String getUsuCancel() {
        return this.usuCancel;
    }
    
    public void setUsuCancel(String usuCancel) {
        this.usuCancel = usuCancel;
    }
    public Integer getRetiradaId() {
        return this.retiradaId;
    }
    
    public void setRetiradaId(Integer retiradaId) {
        this.retiradaId = retiradaId;
    }
    public String getSolicitanteId() {
        return this.solicitanteId;
    }
    
    public void setSolicitanteId(String solicitanteId) {
        this.solicitanteId = solicitanteId;
    }
    public Set getEsRetiradas() {
        return this.esRetiradas;
    }
    
    public void setEsRetiradas(Set esRetiradas) {
        this.esRetiradas = esRetiradas;
    }
    public Set getEsRequisicaoDevolucaos() {
        return this.esRequisicaoDevolucaos;
    }
    
    public void setEsRequisicaoDevolucaos(Set esRequisicaoDevolucaos) {
        this.esRequisicaoDevolucaos = esRequisicaoDevolucaos;
    }
    public Set getEsRequisicaoItems() {
        return this.esRequisicaoItems;
    }
    
    public void setEsRequisicaoItems(Set esRequisicaoItems) {
        this.esRequisicaoItems = esRequisicaoItems;
    }




}


