package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * EsRetiradaItemTmp generated by hbm2java
 */
public class EsRetiradaItemTmp  implements java.io.Serializable {


     private int retItemId;
     private int retiradaId;
     private int itemId;
     private String unid;
     private int materialId;
     private BigDecimal quant;
     private long srRecno;
     private Integer recItemId;
     private Integer reqItemId;
     private Integer medidaId;
     private String certo;

    public EsRetiradaItemTmp() {
    }

	
    public EsRetiradaItemTmp(int retItemId, int retiradaId, int itemId, int materialId, BigDecimal quant, long srRecno, String certo) {
        this.retItemId = retItemId;
        this.retiradaId = retiradaId;
        this.itemId = itemId;
        this.materialId = materialId;
        this.quant = quant;
        this.srRecno = srRecno;
        this.certo = certo;
    }
    public EsRetiradaItemTmp(int retItemId, int retiradaId, int itemId, String unid, int materialId, BigDecimal quant, long srRecno, Integer recItemId, Integer reqItemId, Integer medidaId, String certo) {
       this.retItemId = retItemId;
       this.retiradaId = retiradaId;
       this.itemId = itemId;
       this.unid = unid;
       this.materialId = materialId;
       this.quant = quant;
       this.srRecno = srRecno;
       this.recItemId = recItemId;
       this.reqItemId = reqItemId;
       this.medidaId = medidaId;
       this.certo = certo;
    }
   
    public int getRetItemId() {
        return this.retItemId;
    }
    
    public void setRetItemId(int retItemId) {
        this.retItemId = retItemId;
    }
    public int getRetiradaId() {
        return this.retiradaId;
    }
    
    public void setRetiradaId(int retiradaId) {
        this.retiradaId = retiradaId;
    }
    public int getItemId() {
        return this.itemId;
    }
    
    public void setItemId(int itemId) {
        this.itemId = itemId;
    }
    public String getUnid() {
        return this.unid;
    }
    
    public void setUnid(String unid) {
        this.unid = unid;
    }
    public int getMaterialId() {
        return this.materialId;
    }
    
    public void setMaterialId(int materialId) {
        this.materialId = materialId;
    }
    public BigDecimal getQuant() {
        return this.quant;
    }
    
    public void setQuant(BigDecimal quant) {
        this.quant = quant;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }
    public Integer getRecItemId() {
        return this.recItemId;
    }
    
    public void setRecItemId(Integer recItemId) {
        this.recItemId = recItemId;
    }
    public Integer getReqItemId() {
        return this.reqItemId;
    }
    
    public void setReqItemId(Integer reqItemId) {
        this.reqItemId = reqItemId;
    }
    public Integer getMedidaId() {
        return this.medidaId;
    }
    
    public void setMedidaId(Integer medidaId) {
        this.medidaId = medidaId;
    }
    public String getCerto() {
        return this.certo;
    }
    
    public void setCerto(String certo) {
        this.certo = certo;
    }




}


