package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * EsRetiradaItemComb generated by hbm2java
 */
public class EsRetiradaItemComb  implements java.io.Serializable {


     private int retItemCombId;
     private EsRetiradaItem esRetiradaItem;
     private Date data;
     private int requisicao;
     private BigDecimal quant;
     private int veiculoId;
     private Integer motoristaId;
     private Integer kilometragem;
     private long srRecno;
     private String tipo;
     private int hodometro;

    public EsRetiradaItemComb() {
    }

	
    public EsRetiradaItemComb(int retItemCombId, EsRetiradaItem esRetiradaItem, Date data, int requisicao, BigDecimal quant, int veiculoId, long srRecno, int hodometro) {
        this.retItemCombId = retItemCombId;
        this.esRetiradaItem = esRetiradaItem;
        this.data = data;
        this.requisicao = requisicao;
        this.quant = quant;
        this.veiculoId = veiculoId;
        this.srRecno = srRecno;
        this.hodometro = hodometro;
    }
    public EsRetiradaItemComb(int retItemCombId, EsRetiradaItem esRetiradaItem, Date data, int requisicao, BigDecimal quant, int veiculoId, Integer motoristaId, Integer kilometragem, long srRecno, String tipo, int hodometro) {
       this.retItemCombId = retItemCombId;
       this.esRetiradaItem = esRetiradaItem;
       this.data = data;
       this.requisicao = requisicao;
       this.quant = quant;
       this.veiculoId = veiculoId;
       this.motoristaId = motoristaId;
       this.kilometragem = kilometragem;
       this.srRecno = srRecno;
       this.tipo = tipo;
       this.hodometro = hodometro;
    }
   
    public int getRetItemCombId() {
        return this.retItemCombId;
    }
    
    public void setRetItemCombId(int retItemCombId) {
        this.retItemCombId = retItemCombId;
    }
    public EsRetiradaItem getEsRetiradaItem() {
        return this.esRetiradaItem;
    }
    
    public void setEsRetiradaItem(EsRetiradaItem esRetiradaItem) {
        this.esRetiradaItem = esRetiradaItem;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public int getRequisicao() {
        return this.requisicao;
    }
    
    public void setRequisicao(int requisicao) {
        this.requisicao = requisicao;
    }
    public BigDecimal getQuant() {
        return this.quant;
    }
    
    public void setQuant(BigDecimal quant) {
        this.quant = quant;
    }
    public int getVeiculoId() {
        return this.veiculoId;
    }
    
    public void setVeiculoId(int veiculoId) {
        this.veiculoId = veiculoId;
    }
    public Integer getMotoristaId() {
        return this.motoristaId;
    }
    
    public void setMotoristaId(Integer motoristaId) {
        this.motoristaId = motoristaId;
    }
    public Integer getKilometragem() {
        return this.kilometragem;
    }
    
    public void setKilometragem(Integer kilometragem) {
        this.kilometragem = kilometragem;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public int getHodometro() {
        return this.hodometro;
    }
    
    public void setHodometro(int hodometro) {
        this.hodometro = hodometro;
    }




}


