package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * EsRotas generated by hbm2java
 */
public class EsRotas  implements java.io.Serializable {


     private int rotasId;
     private String endInicial;
     private String endFinal;
     private long srRecno;
     private Set esLinhasTransps = new HashSet(0);

    public EsRotas() {
    }

	
    public EsRotas(int rotasId, long srRecno) {
        this.rotasId = rotasId;
        this.srRecno = srRecno;
    }
    public EsRotas(int rotasId, String endInicial, String endFinal, long srRecno, Set esLinhasTransps) {
       this.rotasId = rotasId;
       this.endInicial = endInicial;
       this.endFinal = endFinal;
       this.srRecno = srRecno;
       this.esLinhasTransps = esLinhasTransps;
    }
   
    public int getRotasId() {
        return this.rotasId;
    }
    
    public void setRotasId(int rotasId) {
        this.rotasId = rotasId;
    }
    public String getEndInicial() {
        return this.endInicial;
    }
    
    public void setEndInicial(String endInicial) {
        this.endInicial = endInicial;
    }
    public String getEndFinal() {
        return this.endFinal;
    }
    
    public void setEndFinal(String endFinal) {
        this.endFinal = endFinal;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }
    public Set getEsLinhasTransps() {
        return this.esLinhasTransps;
    }
    
    public void setEsLinhasTransps(Set esLinhasTransps) {
        this.esLinhasTransps = esLinhasTransps;
    }




}


