package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * EsSolVei generated by hbm2java
 */
public class EsSolVei  implements java.io.Serializable {


     private int esSolVeiId;
     private Character tipo;
     private Date data;
     private Integer veiculoId;
     private String orgaoId;
     private String unidadeId;
     private String destino;
     private String tipoServico;
     private String objetivoServ;
     private Date hora;
     private Integer motoristaId;
     private Integer orgaoUnidadeId;
     private long srRecno;

    public EsSolVei() {
    }

	
    public EsSolVei(int esSolVeiId, long srRecno) {
        this.esSolVeiId = esSolVeiId;
        this.srRecno = srRecno;
    }
    public EsSolVei(int esSolVeiId, Character tipo, Date data, Integer veiculoId, String orgaoId, String unidadeId, String destino, String tipoServico, String objetivoServ, Date hora, Integer motoristaId, Integer orgaoUnidadeId, long srRecno) {
       this.esSolVeiId = esSolVeiId;
       this.tipo = tipo;
       this.data = data;
       this.veiculoId = veiculoId;
       this.orgaoId = orgaoId;
       this.unidadeId = unidadeId;
       this.destino = destino;
       this.tipoServico = tipoServico;
       this.objetivoServ = objetivoServ;
       this.hora = hora;
       this.motoristaId = motoristaId;
       this.orgaoUnidadeId = orgaoUnidadeId;
       this.srRecno = srRecno;
    }
   
    public int getEsSolVeiId() {
        return this.esSolVeiId;
    }
    
    public void setEsSolVeiId(int esSolVeiId) {
        this.esSolVeiId = esSolVeiId;
    }
    public Character getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Character tipo) {
        this.tipo = tipo;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public Integer getVeiculoId() {
        return this.veiculoId;
    }
    
    public void setVeiculoId(Integer veiculoId) {
        this.veiculoId = veiculoId;
    }
    public String getOrgaoId() {
        return this.orgaoId;
    }
    
    public void setOrgaoId(String orgaoId) {
        this.orgaoId = orgaoId;
    }
    public String getUnidadeId() {
        return this.unidadeId;
    }
    
    public void setUnidadeId(String unidadeId) {
        this.unidadeId = unidadeId;
    }
    public String getDestino() {
        return this.destino;
    }
    
    public void setDestino(String destino) {
        this.destino = destino;
    }
    public String getTipoServico() {
        return this.tipoServico;
    }
    
    public void setTipoServico(String tipoServico) {
        this.tipoServico = tipoServico;
    }
    public String getObjetivoServ() {
        return this.objetivoServ;
    }
    
    public void setObjetivoServ(String objetivoServ) {
        this.objetivoServ = objetivoServ;
    }
    public Date getHora() {
        return this.hora;
    }
    
    public void setHora(Date hora) {
        this.hora = hora;
    }
    public Integer getMotoristaId() {
        return this.motoristaId;
    }
    
    public void setMotoristaId(Integer motoristaId) {
        this.motoristaId = motoristaId;
    }
    public Integer getOrgaoUnidadeId() {
        return this.orgaoUnidadeId;
    }
    
    public void setOrgaoUnidadeId(Integer orgaoUnidadeId) {
        this.orgaoUnidadeId = orgaoUnidadeId;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }




}


