package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * EsTipoAplicacao generated by hbm2java
 */
public class EsTipoAplicacao  implements java.io.Serializable {


     private int tipo;
     private TceMtTipoMovimentoMaterial tceMtTipoMovimentoMaterial;
     private String descricao;
     private long srRecno;
     private int categoria;
     private Set esRecebimentos = new HashSet(0);

    public EsTipoAplicacao() {
    }

	
    public EsTipoAplicacao(int tipo, String descricao, long srRecno, int categoria) {
        this.tipo = tipo;
        this.descricao = descricao;
        this.srRecno = srRecno;
        this.categoria = categoria;
    }
    public EsTipoAplicacao(int tipo, TceMtTipoMovimentoMaterial tceMtTipoMovimentoMaterial, String descricao, long srRecno, int categoria, Set esRecebimentos) {
       this.tipo = tipo;
       this.tceMtTipoMovimentoMaterial = tceMtTipoMovimentoMaterial;
       this.descricao = descricao;
       this.srRecno = srRecno;
       this.categoria = categoria;
       this.esRecebimentos = esRecebimentos;
    }
   
    public int getTipo() {
        return this.tipo;
    }
    
    public void setTipo(int tipo) {
        this.tipo = tipo;
    }
    public TceMtTipoMovimentoMaterial getTceMtTipoMovimentoMaterial() {
        return this.tceMtTipoMovimentoMaterial;
    }
    
    public void setTceMtTipoMovimentoMaterial(TceMtTipoMovimentoMaterial tceMtTipoMovimentoMaterial) {
        this.tceMtTipoMovimentoMaterial = tceMtTipoMovimentoMaterial;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }
    public int getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(int categoria) {
        this.categoria = categoria;
    }
    public Set getEsRecebimentos() {
        return this.esRecebimentos;
    }
    
    public void setEsRecebimentos(Set esRecebimentos) {
        this.esRecebimentos = esRecebimentos;
    }




}


