package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1



/**
 * EsTipoRetirada generated by hbm2java
 */
public class EsTipoRetirada  implements java.io.Serializable {


     private int tipo;
     private TceMtTipoMovimentoMaterial tceMtTipoMovimentoMaterial;
     private String descricao;
     private long srRecno;

    public EsTipoRetirada() {
    }

	
    public EsTipoRetirada(int tipo, String descricao, long srRecno) {
        this.tipo = tipo;
        this.descricao = descricao;
        this.srRecno = srRecno;
    }
    public EsTipoRetirada(int tipo, TceMtTipoMovimentoMaterial tceMtTipoMovimentoMaterial, String descricao, long srRecno) {
       this.tipo = tipo;
       this.tceMtTipoMovimentoMaterial = tceMtTipoMovimentoMaterial;
       this.descricao = descricao;
       this.srRecno = srRecno;
    }
   
    public int getTipo() {
        return this.tipo;
    }
    
    public void setTipo(int tipo) {
        this.tipo = tipo;
    }
    public TceMtTipoMovimentoMaterial getTceMtTipoMovimentoMaterial() {
        return this.tceMtTipoMovimentoMaterial;
    }
    
    public void setTceMtTipoMovimentoMaterial(TceMtTipoMovimentoMaterial tceMtTipoMovimentoMaterial) {
        this.tceMtTipoMovimentoMaterial = tceMtTipoMovimentoMaterial;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }




}


