package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * FrCarroceria generated by hbm2java
 */
public class FrCarroceria  implements java.io.Serializable {


     private int carroceriaId;
     private String carroceria;
     private long srRecno;
     private Set frVeiculos = new HashSet(0);

    public FrCarroceria() {
    }

	
    public FrCarroceria(int carroceriaId, String carroceria, long srRecno) {
        this.carroceriaId = carroceriaId;
        this.carroceria = carroceria;
        this.srRecno = srRecno;
    }
    public FrCarroceria(int carroceriaId, String carroceria, long srRecno, Set frVeiculos) {
       this.carroceriaId = carroceriaId;
       this.carroceria = carroceria;
       this.srRecno = srRecno;
       this.frVeiculos = frVeiculos;
    }
   
    public int getCarroceriaId() {
        return this.carroceriaId;
    }
    
    public void setCarroceriaId(int carroceriaId) {
        this.carroceriaId = carroceriaId;
    }
    public String getCarroceria() {
        return this.carroceria;
    }
    
    public void setCarroceria(String carroceria) {
        this.carroceria = carroceria;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }
    public Set getFrVeiculos() {
        return this.frVeiculos;
    }
    
    public void setFrVeiculos(Set frVeiculos) {
        this.frVeiculos = frVeiculos;
    }




}


