package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * FrCombustivel generated by hbm2java
 */
public class FrCombustivel  implements java.io.Serializable {


     private int combustivelId;
     private String combustivel;
     private long srRecno;
     private Integer lcCodTerminal;
     private Set frVeiculos = new HashSet(0);

    public FrCombustivel() {
    }

	
    public FrCombustivel(int combustivelId, String combustivel, long srRecno) {
        this.combustivelId = combustivelId;
        this.combustivel = combustivel;
        this.srRecno = srRecno;
    }
    public FrCombustivel(int combustivelId, String combustivel, long srRecno, Integer lcCodTerminal, Set frVeiculos) {
       this.combustivelId = combustivelId;
       this.combustivel = combustivel;
       this.srRecno = srRecno;
       this.lcCodTerminal = lcCodTerminal;
       this.frVeiculos = frVeiculos;
    }
   
    public int getCombustivelId() {
        return this.combustivelId;
    }
    
    public void setCombustivelId(int combustivelId) {
        this.combustivelId = combustivelId;
    }
    public String getCombustivel() {
        return this.combustivel;
    }
    
    public void setCombustivel(String combustivel) {
        this.combustivel = combustivel;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }
    public Integer getLcCodTerminal() {
        return this.lcCodTerminal;
    }
    
    public void setLcCodTerminal(Integer lcCodTerminal) {
        this.lcCodTerminal = lcCodTerminal;
    }
    public Set getFrVeiculos() {
        return this.frVeiculos;
    }
    
    public void setFrVeiculos(Set frVeiculos) {
        this.frVeiculos = frVeiculos;
    }




}


