package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * FrMotorista generated by hbm2java
 */
public class FrMotorista  implements java.io.Serializable {


     private int motoristaId;
     private CpSecretaria cpSecretaria;
     private Gbairro gbairro;
     private Gmunicipio gmunicipio;
     private String motorista;
     private String endereco;
     private String cep;
     private String cpf;
     private String rg;
     private String fone;
     private String celular;
     private String cnhNumero;
     private String cnhCategoria;
     private Date cnhValidade;
     private String desativado;
     private String fpempresaId;
     private String fpfuncionarioId;
     private long srRecno;
     private Integer lcBloqueio;
     private Set esPlanilhaBordoItems = new HashSet(0);
     private Set esAplicDiretaItemCombs = new HashSet(0);
     private Set lcCombDispBxes = new HashSet(0);
     private Set esMultas = new HashSet(0);

    public FrMotorista() {
    }

	
    public FrMotorista(int motoristaId, String motorista, String desativado, long srRecno) {
        this.motoristaId = motoristaId;
        this.motorista = motorista;
        this.desativado = desativado;
        this.srRecno = srRecno;
    }
    public FrMotorista(int motoristaId, CpSecretaria cpSecretaria, Gbairro gbairro, Gmunicipio gmunicipio, String motorista, String endereco, String cep, String cpf, String rg, String fone, String celular, String cnhNumero, String cnhCategoria, Date cnhValidade, String desativado, String fpempresaId, String fpfuncionarioId, long srRecno, Integer lcBloqueio, Set esPlanilhaBordoItems, Set esAplicDiretaItemCombs, Set lcCombDispBxes, Set esMultas) {
       this.motoristaId = motoristaId;
       this.cpSecretaria = cpSecretaria;
       this.gbairro = gbairro;
       this.gmunicipio = gmunicipio;
       this.motorista = motorista;
       this.endereco = endereco;
       this.cep = cep;
       this.cpf = cpf;
       this.rg = rg;
       this.fone = fone;
       this.celular = celular;
       this.cnhNumero = cnhNumero;
       this.cnhCategoria = cnhCategoria;
       this.cnhValidade = cnhValidade;
       this.desativado = desativado;
       this.fpempresaId = fpempresaId;
       this.fpfuncionarioId = fpfuncionarioId;
       this.srRecno = srRecno;
       this.lcBloqueio = lcBloqueio;
       this.esPlanilhaBordoItems = esPlanilhaBordoItems;
       this.esAplicDiretaItemCombs = esAplicDiretaItemCombs;
       this.lcCombDispBxes = lcCombDispBxes;
       this.esMultas = esMultas;
    }
   
    public int getMotoristaId() {
        return this.motoristaId;
    }
    
    public void setMotoristaId(int motoristaId) {
        this.motoristaId = motoristaId;
    }
    public CpSecretaria getCpSecretaria() {
        return this.cpSecretaria;
    }
    
    public void setCpSecretaria(CpSecretaria cpSecretaria) {
        this.cpSecretaria = cpSecretaria;
    }
    public Gbairro getGbairro() {
        return this.gbairro;
    }
    
    public void setGbairro(Gbairro gbairro) {
        this.gbairro = gbairro;
    }
    public Gmunicipio getGmunicipio() {
        return this.gmunicipio;
    }
    
    public void setGmunicipio(Gmunicipio gmunicipio) {
        this.gmunicipio = gmunicipio;
    }
    public String getMotorista() {
        return this.motorista;
    }
    
    public void setMotorista(String motorista) {
        this.motorista = motorista;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    public String getRg() {
        return this.rg;
    }
    
    public void setRg(String rg) {
        this.rg = rg;
    }
    public String getFone() {
        return this.fone;
    }
    
    public void setFone(String fone) {
        this.fone = fone;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public String getCnhNumero() {
        return this.cnhNumero;
    }
    
    public void setCnhNumero(String cnhNumero) {
        this.cnhNumero = cnhNumero;
    }
    public String getCnhCategoria() {
        return this.cnhCategoria;
    }
    
    public void setCnhCategoria(String cnhCategoria) {
        this.cnhCategoria = cnhCategoria;
    }
    public Date getCnhValidade() {
        return this.cnhValidade;
    }
    
    public void setCnhValidade(Date cnhValidade) {
        this.cnhValidade = cnhValidade;
    }
    public String getDesativado() {
        return this.desativado;
    }
    
    public void setDesativado(String desativado) {
        this.desativado = desativado;
    }
    public String getFpempresaId() {
        return this.fpempresaId;
    }
    
    public void setFpempresaId(String fpempresaId) {
        this.fpempresaId = fpempresaId;
    }
    public String getFpfuncionarioId() {
        return this.fpfuncionarioId;
    }
    
    public void setFpfuncionarioId(String fpfuncionarioId) {
        this.fpfuncionarioId = fpfuncionarioId;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }
    public Integer getLcBloqueio() {
        return this.lcBloqueio;
    }
    
    public void setLcBloqueio(Integer lcBloqueio) {
        this.lcBloqueio = lcBloqueio;
    }
    public Set getEsPlanilhaBordoItems() {
        return this.esPlanilhaBordoItems;
    }
    
    public void setEsPlanilhaBordoItems(Set esPlanilhaBordoItems) {
        this.esPlanilhaBordoItems = esPlanilhaBordoItems;
    }
    public Set getEsAplicDiretaItemCombs() {
        return this.esAplicDiretaItemCombs;
    }
    
    public void setEsAplicDiretaItemCombs(Set esAplicDiretaItemCombs) {
        this.esAplicDiretaItemCombs = esAplicDiretaItemCombs;
    }
    public Set getLcCombDispBxes() {
        return this.lcCombDispBxes;
    }
    
    public void setLcCombDispBxes(Set lcCombDispBxes) {
        this.lcCombDispBxes = lcCombDispBxes;
    }
    public Set getEsMultas() {
        return this.esMultas;
    }
    
    public void setEsMultas(Set esMultas) {
        this.esMultas = esMultas;
    }




}


