package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Gano generated by hbm2java
 */
public class Gano  implements java.io.Serializable {


     private int ganoId;
     private long srRecno;
     private Date gacesso;
     private Set orNatDesps = new HashSet(0);
     private Set cpCompras = new HashSet(0);
     private Set cpDespesas = new HashSet(0);
     private Set orCredors = new HashSet(0);

    public Gano() {
    }

	
    public Gano(int ganoId, long srRecno) {
        this.ganoId = ganoId;
        this.srRecno = srRecno;
    }
    public Gano(int ganoId, long srRecno, Date gacesso, Set orNatDesps, Set cpCompras, Set cpDespesas, Set orCredors) {
       this.ganoId = ganoId;
       this.srRecno = srRecno;
       this.gacesso = gacesso;
       this.orNatDesps = orNatDesps;
       this.cpCompras = cpCompras;
       this.cpDespesas = cpDespesas;
       this.orCredors = orCredors;
    }
   
    public int getGanoId() {
        return this.ganoId;
    }
    
    public void setGanoId(int ganoId) {
        this.ganoId = ganoId;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }
    public Date getGacesso() {
        return this.gacesso;
    }
    
    public void setGacesso(Date gacesso) {
        this.gacesso = gacesso;
    }
    public Set getOrNatDesps() {
        return this.orNatDesps;
    }
    
    public void setOrNatDesps(Set orNatDesps) {
        this.orNatDesps = orNatDesps;
    }
    public Set getCpCompras() {
        return this.cpCompras;
    }
    
    public void setCpCompras(Set cpCompras) {
        this.cpCompras = cpCompras;
    }
    public Set getCpDespesas() {
        return this.cpDespesas;
    }
    
    public void setCpDespesas(Set cpDespesas) {
        this.cpDespesas = cpDespesas;
    }
    public Set getOrCredors() {
        return this.orCredors;
    }
    
    public void setOrCredors(Set orCredors) {
        this.orCredors = orCredors;
    }




}


