package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Ggrupo generated by hbm2java
 */
public class Ggrupo  implements java.io.Serializable {


     private String ggrupoId;
     private String grupo;
     private long srRecno;
     private Date gacesso;
     private Set gusuarios = new HashSet(0);

    public Ggrupo() {
    }

	
    public Ggrupo(String ggrupoId, String grupo, long srRecno) {
        this.ggrupoId = ggrupoId;
        this.grupo = grupo;
        this.srRecno = srRecno;
    }
    public Ggrupo(String ggrupoId, String grupo, long srRecno, Date gacesso, Set gusuarios) {
       this.ggrupoId = ggrupoId;
       this.grupo = grupo;
       this.srRecno = srRecno;
       this.gacesso = gacesso;
       this.gusuarios = gusuarios;
    }
   
    public String getGgrupoId() {
        return this.ggrupoId;
    }
    
    public void setGgrupoId(String ggrupoId) {
        this.ggrupoId = ggrupoId;
    }
    public String getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(String grupo) {
        this.grupo = grupo;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }
    public Date getGacesso() {
        return this.gacesso;
    }
    
    public void setGacesso(Date gacesso) {
        this.gacesso = gacesso;
    }
    public Set getGusuarios() {
        return this.gusuarios;
    }
    
    public void setGusuarios(Set gusuarios) {
        this.gusuarios = gusuarios;
    }




}


