package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Glograd generated by hbm2java
 */
public class Glograd  implements java.io.Serializable {


     private String glogradId;
     private String lograd;
     private long srRecno;
     private String tipo;
     private Date gacesso;
     private Set esPacientes = new HashSet(0);

    public Glograd() {
    }

	
    public Glograd(String glogradId, String lograd, long srRecno, String tipo) {
        this.glogradId = glogradId;
        this.lograd = lograd;
        this.srRecno = srRecno;
        this.tipo = tipo;
    }
    public Glograd(String glogradId, String lograd, long srRecno, String tipo, Date gacesso, Set esPacientes) {
       this.glogradId = glogradId;
       this.lograd = lograd;
       this.srRecno = srRecno;
       this.tipo = tipo;
       this.gacesso = gacesso;
       this.esPacientes = esPacientes;
    }
   
    public String getGlogradId() {
        return this.glogradId;
    }
    
    public void setGlogradId(String glogradId) {
        this.glogradId = glogradId;
    }
    public String getLograd() {
        return this.lograd;
    }
    
    public void setLograd(String lograd) {
        this.lograd = lograd;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Date getGacesso() {
        return this.gacesso;
    }
    
    public void setGacesso(Date gacesso) {
        this.gacesso = gacesso;
    }
    public Set getEsPacientes() {
        return this.esPacientes;
    }
    
    public void setEsPacientes(Set esPacientes) {
        this.esPacientes = esPacientes;
    }




}


