package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Gsinpas generated by hbm2java
 */
public class Gsinpas  implements java.io.Serializable {


     private String sinpasId;
     private String sinpasMuncipio;
     private String sinpasTpLoc;
     private String sinpasUf;
     private long srRecno;
     private Set gmunicipios = new HashSet(0);

    public Gsinpas() {
    }

	
    public Gsinpas(String sinpasId, String sinpasMuncipio, String sinpasTpLoc, String sinpasUf, long srRecno) {
        this.sinpasId = sinpasId;
        this.sinpasMuncipio = sinpasMuncipio;
        this.sinpasTpLoc = sinpasTpLoc;
        this.sinpasUf = sinpasUf;
        this.srRecno = srRecno;
    }
    public Gsinpas(String sinpasId, String sinpasMuncipio, String sinpasTpLoc, String sinpasUf, long srRecno, Set gmunicipios) {
       this.sinpasId = sinpasId;
       this.sinpasMuncipio = sinpasMuncipio;
       this.sinpasTpLoc = sinpasTpLoc;
       this.sinpasUf = sinpasUf;
       this.srRecno = srRecno;
       this.gmunicipios = gmunicipios;
    }
   
    public String getSinpasId() {
        return this.sinpasId;
    }
    
    public void setSinpasId(String sinpasId) {
        this.sinpasId = sinpasId;
    }
    public String getSinpasMuncipio() {
        return this.sinpasMuncipio;
    }
    
    public void setSinpasMuncipio(String sinpasMuncipio) {
        this.sinpasMuncipio = sinpasMuncipio;
    }
    public String getSinpasTpLoc() {
        return this.sinpasTpLoc;
    }
    
    public void setSinpasTpLoc(String sinpasTpLoc) {
        this.sinpasTpLoc = sinpasTpLoc;
    }
    public String getSinpasUf() {
        return this.sinpasUf;
    }
    
    public void setSinpasUf(String sinpasUf) {
        this.sinpasUf = sinpasUf;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }
    public Set getGmunicipios() {
        return this.gmunicipios;
    }
    
    public void setGmunicipios(Set gmunicipios) {
        this.gmunicipios = gmunicipios;
    }




}


