package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Guf generated by hbm2java
 */
public class Guf  implements java.io.Serializable {


     private String gufId;
     private String descricao;
     private long srRecno;
     private Date gacesso;
     private Set esPacientes = new HashSet(0);
     private Set gmunicipios = new HashSet(0);

    public Guf() {
    }

	
    public Guf(String gufId, String descricao, long srRecno) {
        this.gufId = gufId;
        this.descricao = descricao;
        this.srRecno = srRecno;
    }
    public Guf(String gufId, String descricao, long srRecno, Date gacesso, Set esPacientes, Set gmunicipios) {
       this.gufId = gufId;
       this.descricao = descricao;
       this.srRecno = srRecno;
       this.gacesso = gacesso;
       this.esPacientes = esPacientes;
       this.gmunicipios = gmunicipios;
    }
   
    public String getGufId() {
        return this.gufId;
    }
    
    public void setGufId(String gufId) {
        this.gufId = gufId;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }
    public Date getGacesso() {
        return this.gacesso;
    }
    
    public void setGacesso(Date gacesso) {
        this.gacesso = gacesso;
    }
    public Set getEsPacientes() {
        return this.esPacientes;
    }
    
    public void setEsPacientes(Set esPacientes) {
        this.esPacientes = esPacientes;
    }
    public Set getGmunicipios() {
        return this.gmunicipios;
    }
    
    public void setGmunicipios(Set gmunicipios) {
        this.gmunicipios = gmunicipios;
    }




}


