package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Gusuario generated by hbm2java
 */
public class Gusuario  implements java.io.Serializable {


     private String gusuarioId;
     private Ggrupo ggrupo;
     private String nome;
     private String nomeLogin;
     private String cpfUsuario;
     private String senha;
     private String palavraSenha;
     private Character alterarSenha;
     private char gusuarioAtivo;
     private long srRecno;
     private Date gacesso;
     private int tentativa;
     private Set esInventarioItems = new HashSet(0);
     private Set esRetiradas = new HashSet(0);
     private Set cpRequisis = new HashSet(0);
     private Set esInventarioItemLotes = new HashSet(0);
     private Set esDepositoUsuarios = new HashSet(0);
     private Set esInventarioItemDets = new HashSet(0);
     private Set esInventarios = new HashSet(0);
     private Set esAplicacaoDiretas = new HashSet(0);

    public Gusuario() {
    }

	
    public Gusuario(String gusuarioId, Ggrupo ggrupo, String nome, String nomeLogin, String cpfUsuario, String senha, char gusuarioAtivo, long srRecno, int tentativa) {
        this.gusuarioId = gusuarioId;
        this.ggrupo = ggrupo;
        this.nome = nome;
        this.nomeLogin = nomeLogin;
        this.cpfUsuario = cpfUsuario;
        this.senha = senha;
        this.gusuarioAtivo = gusuarioAtivo;
        this.srRecno = srRecno;
        this.tentativa = tentativa;
    }
    public Gusuario(String gusuarioId, Ggrupo ggrupo, String nome, String nomeLogin, String cpfUsuario, String senha, String palavraSenha, Character alterarSenha, char gusuarioAtivo, long srRecno, Date gacesso, int tentativa, Set esInventarioItems, Set esRetiradas, Set cpRequisis, Set esInventarioItemLotes, Set esDepositoUsuarios, Set esInventarioItemDets, Set esInventarios, Set esAplicacaoDiretas) {
       this.gusuarioId = gusuarioId;
       this.ggrupo = ggrupo;
       this.nome = nome;
       this.nomeLogin = nomeLogin;
       this.cpfUsuario = cpfUsuario;
       this.senha = senha;
       this.palavraSenha = palavraSenha;
       this.alterarSenha = alterarSenha;
       this.gusuarioAtivo = gusuarioAtivo;
       this.srRecno = srRecno;
       this.gacesso = gacesso;
       this.tentativa = tentativa;
       this.esInventarioItems = esInventarioItems;
       this.esRetiradas = esRetiradas;
       this.cpRequisis = cpRequisis;
       this.esInventarioItemLotes = esInventarioItemLotes;
       this.esDepositoUsuarios = esDepositoUsuarios;
       this.esInventarioItemDets = esInventarioItemDets;
       this.esInventarios = esInventarios;
       this.esAplicacaoDiretas = esAplicacaoDiretas;
    }
   
    public String getGusuarioId() {
        return this.gusuarioId;
    }
    
    public void setGusuarioId(String gusuarioId) {
        this.gusuarioId = gusuarioId;
    }
    public Ggrupo getGgrupo() {
        return this.ggrupo;
    }
    
    public void setGgrupo(Ggrupo ggrupo) {
        this.ggrupo = ggrupo;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getNomeLogin() {
        return this.nomeLogin;
    }
    
    public void setNomeLogin(String nomeLogin) {
        this.nomeLogin = nomeLogin;
    }
    public String getCpfUsuario() {
        return this.cpfUsuario;
    }
    
    public void setCpfUsuario(String cpfUsuario) {
        this.cpfUsuario = cpfUsuario;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public String getPalavraSenha() {
        return this.palavraSenha;
    }
    
    public void setPalavraSenha(String palavraSenha) {
        this.palavraSenha = palavraSenha;
    }
    public Character getAlterarSenha() {
        return this.alterarSenha;
    }
    
    public void setAlterarSenha(Character alterarSenha) {
        this.alterarSenha = alterarSenha;
    }
    public char getGusuarioAtivo() {
        return this.gusuarioAtivo;
    }
    
    public void setGusuarioAtivo(char gusuarioAtivo) {
        this.gusuarioAtivo = gusuarioAtivo;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }
    public Date getGacesso() {
        return this.gacesso;
    }
    
    public void setGacesso(Date gacesso) {
        this.gacesso = gacesso;
    }
    public int getTentativa() {
        return this.tentativa;
    }
    
    public void setTentativa(int tentativa) {
        this.tentativa = tentativa;
    }
    public Set getEsInventarioItems() {
        return this.esInventarioItems;
    }
    
    public void setEsInventarioItems(Set esInventarioItems) {
        this.esInventarioItems = esInventarioItems;
    }
    public Set getEsRetiradas() {
        return this.esRetiradas;
    }
    
    public void setEsRetiradas(Set esRetiradas) {
        this.esRetiradas = esRetiradas;
    }
    public Set getCpRequisis() {
        return this.cpRequisis;
    }
    
    public void setCpRequisis(Set cpRequisis) {
        this.cpRequisis = cpRequisis;
    }
    public Set getEsInventarioItemLotes() {
        return this.esInventarioItemLotes;
    }
    
    public void setEsInventarioItemLotes(Set esInventarioItemLotes) {
        this.esInventarioItemLotes = esInventarioItemLotes;
    }
    public Set getEsDepositoUsuarios() {
        return this.esDepositoUsuarios;
    }
    
    public void setEsDepositoUsuarios(Set esDepositoUsuarios) {
        this.esDepositoUsuarios = esDepositoUsuarios;
    }
    public Set getEsInventarioItemDets() {
        return this.esInventarioItemDets;
    }
    
    public void setEsInventarioItemDets(Set esInventarioItemDets) {
        this.esInventarioItemDets = esInventarioItemDets;
    }
    public Set getEsInventarios() {
        return this.esInventarios;
    }
    
    public void setEsInventarios(Set esInventarios) {
        this.esInventarios = esInventarios;
    }
    public Set getEsAplicacaoDiretas() {
        return this.esAplicacaoDiretas;
    }
    
    public void setEsAplicacaoDiretas(Set esAplicacaoDiretas) {
        this.esAplicacaoDiretas = esAplicacaoDiretas;
    }




}


