package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * LcCombDisp generated by hbm2java
 */
public class LcCombDisp  implements java.io.Serializable {


     private int combDispId;
     private CpConcorrencia cpConcorrencia;
     private CpMaterial cpMaterial;
     private CpRequisi cpRequisi;
     private FrVeiculo frVeiculo;
     private BigDecimal quant;
     private BigDecimal quantSld;
     private long srRecno;
     private Date data;
     private String origem;
     private Integer numRecebimento;
     private String lcUsuario;
     private String secretaria;
     private Integer tipoDocumento;
     private Integer lexCardId;
     private Set lcCombDispBxes = new HashSet(0);

    public LcCombDisp() {
    }

	
    public LcCombDisp(int combDispId, BigDecimal quant, long srRecno) {
        this.combDispId = combDispId;
        this.quant = quant;
        this.srRecno = srRecno;
    }
    public LcCombDisp(int combDispId, CpConcorrencia cpConcorrencia, CpMaterial cpMaterial, CpRequisi cpRequisi, FrVeiculo frVeiculo, BigDecimal quant, BigDecimal quantSld, long srRecno, Date data, String origem, Integer numRecebimento, String lcUsuario, String secretaria, Integer tipoDocumento, Integer lexCardId, Set lcCombDispBxes) {
       this.combDispId = combDispId;
       this.cpConcorrencia = cpConcorrencia;
       this.cpMaterial = cpMaterial;
       this.cpRequisi = cpRequisi;
       this.frVeiculo = frVeiculo;
       this.quant = quant;
       this.quantSld = quantSld;
       this.srRecno = srRecno;
       this.data = data;
       this.origem = origem;
       this.numRecebimento = numRecebimento;
       this.lcUsuario = lcUsuario;
       this.secretaria = secretaria;
       this.tipoDocumento = tipoDocumento;
       this.lexCardId = lexCardId;
       this.lcCombDispBxes = lcCombDispBxes;
    }
   
    public int getCombDispId() {
        return this.combDispId;
    }
    
    public void setCombDispId(int combDispId) {
        this.combDispId = combDispId;
    }
    public CpConcorrencia getCpConcorrencia() {
        return this.cpConcorrencia;
    }
    
    public void setCpConcorrencia(CpConcorrencia cpConcorrencia) {
        this.cpConcorrencia = cpConcorrencia;
    }
    public CpMaterial getCpMaterial() {
        return this.cpMaterial;
    }
    
    public void setCpMaterial(CpMaterial cpMaterial) {
        this.cpMaterial = cpMaterial;
    }
    public CpRequisi getCpRequisi() {
        return this.cpRequisi;
    }
    
    public void setCpRequisi(CpRequisi cpRequisi) {
        this.cpRequisi = cpRequisi;
    }
    public FrVeiculo getFrVeiculo() {
        return this.frVeiculo;
    }
    
    public void setFrVeiculo(FrVeiculo frVeiculo) {
        this.frVeiculo = frVeiculo;
    }
    public BigDecimal getQuant() {
        return this.quant;
    }
    
    public void setQuant(BigDecimal quant) {
        this.quant = quant;
    }
    public BigDecimal getQuantSld() {
        return this.quantSld;
    }
    
    public void setQuantSld(BigDecimal quantSld) {
        this.quantSld = quantSld;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public String getOrigem() {
        return this.origem;
    }
    
    public void setOrigem(String origem) {
        this.origem = origem;
    }
    public Integer getNumRecebimento() {
        return this.numRecebimento;
    }
    
    public void setNumRecebimento(Integer numRecebimento) {
        this.numRecebimento = numRecebimento;
    }
    public String getLcUsuario() {
        return this.lcUsuario;
    }
    
    public void setLcUsuario(String lcUsuario) {
        this.lcUsuario = lcUsuario;
    }
    public String getSecretaria() {
        return this.secretaria;
    }
    
    public void setSecretaria(String secretaria) {
        this.secretaria = secretaria;
    }
    public Integer getTipoDocumento() {
        return this.tipoDocumento;
    }
    
    public void setTipoDocumento(Integer tipoDocumento) {
        this.tipoDocumento = tipoDocumento;
    }
    public Integer getLexCardId() {
        return this.lexCardId;
    }
    
    public void setLexCardId(Integer lexCardId) {
        this.lexCardId = lexCardId;
    }
    public Set getLcCombDispBxes() {
        return this.lcCombDispBxes;
    }
    
    public void setLcCombDispBxes(Set lcCombDispBxes) {
        this.lcCombDispBxes = lcCombDispBxes;
    }




}


