package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * OrCredor generated by hbm2java
 */
public class OrCredor  implements java.io.Serializable {


     private String codigo;
     private Gano gano;
     private Gempresa gempresa;
     private int credorId;
     private String grupo;
     private String endereco;
     private String codcidade;
     private String cidade;
     private String fone;
     private String cae;
     private String fax;
     private String contato;
     private String bairro;
     private String uf;
     private String cep;
     private String inscMu;
     private String inscEs;
     private String inscMf;
     private String banco;
     private String agencia;
     private String CCorrente;
     private String bco;
     private String age;
     private Character dage;
     private String CC;
     private Character dcC;
     private String tipoDoc1;
     private String documento1;
     private String tipoDoc2;
     private String documento2;
     private Character tipo;
     private Character simples;
     private Character debitos;
     private Date dtDebitos;
     private Date dtCertCd;
     private String usCertCd;
     private String infAdic;
     private char desativa;
     private Character nacionalid;
     private String fantasia;
     private long srRecno;
     private String nome;
     private String EMail;
     private Short tipoEmp;
     private String cgIdentificacao;
     private Date dataCad;
     private Date gacesso;
     private Integer ctaBancariaId;
     private BigDecimal capSocial;
     private Date certCrea;
     private Date certEstad;
     private Date certFalen;
     private Date certFeder;
     private Date certFgts;
     private Date certInss;
     private Date certMunic;
     private Date certUniao;
     private Integer certificado;
     private String certificadoAux;
     private String cmaeId;
     private String cnaeId;
     private Date dtCadastro;
     private String email;
     private Integer gmunicipioId;
     private String nacionalidade;
     private String objSocial;
     private String site;
     private String municipio;
     private String inss;
     private Date atoConstit;
     private Date cadMunic;
     private Date cadEstad;
     private Date cadCnpj;
     private Date procGerEst;
     private Character vcd;
     private Character vce;
     private Character vac;
     private Character vpg;
     private Character vci;
     private Character vcm;
     private Character vcam;
     private Character vdc;
     private Character vcf;
     private Character vcfa;
     private Character vcae;
     private Character vcfe;
     private Character vcre;
     private Character vcn;
     private Date cadData;
     private Character avisoCredorCnab240;
     private String nomeMae;
     private String nomePai;
     private Date nascPai;
     private Date nascMae;
     private String ccObs;
     private char ccIndiConj;
     private char ccCorrPoup;
     private String pis;
     private String cbo;
     private String nomeVendedor;
     private Date dtNasc;
     private Integer cgMicroPeqEmp;
     private Date certTrab;
     private Character vctr;
     private Character suspenso;
     private String motivo;
     private Integer op;
     private Integer tpFor;
     private String celfone;
     private Set cpRepresentantes = new HashSet(0);

    public OrCredor() {
    }

	
    public OrCredor(String codigo, Gano gano, Gempresa gempresa, int credorId, char desativa, long srRecno, BigDecimal capSocial, char ccIndiConj, char ccCorrPoup) {
        this.codigo = codigo;
        this.gano = gano;
        this.gempresa = gempresa;
        this.credorId = credorId;
        this.desativa = desativa;
        this.srRecno = srRecno;
        this.capSocial = capSocial;
        this.ccIndiConj = ccIndiConj;
        this.ccCorrPoup = ccCorrPoup;
    }
    public OrCredor(String codigo, Gano gano, Gempresa gempresa, int credorId, String grupo, String endereco, String codcidade, String cidade, String fone, String cae, String fax, String contato, String bairro, String uf, String cep, String inscMu, String inscEs, String inscMf, String banco, String agencia, String CCorrente, String bco, String age, Character dage, String CC, Character dcC, String tipoDoc1, String documento1, String tipoDoc2, String documento2, Character tipo, Character simples, Character debitos, Date dtDebitos, Date dtCertCd, String usCertCd, String infAdic, char desativa, Character nacionalid, String fantasia, long srRecno, String nome, String EMail, Short tipoEmp, String cgIdentificacao, Date dataCad, Date gacesso, Integer ctaBancariaId, BigDecimal capSocial, Date certCrea, Date certEstad, Date certFalen, Date certFeder, Date certFgts, Date certInss, Date certMunic, Date certUniao, Integer certificado, String certificadoAux, String cmaeId, String cnaeId, Date dtCadastro, String email, Integer gmunicipioId, String nacionalidade, String objSocial, String site, String municipio, String inss, Date atoConstit, Date cadMunic, Date cadEstad, Date cadCnpj, Date procGerEst, Character vcd, Character vce, Character vac, Character vpg, Character vci, Character vcm, Character vcam, Character vdc, Character vcf, Character vcfa, Character vcae, Character vcfe, Character vcre, Character vcn, Date cadData, Character avisoCredorCnab240, String nomeMae, String nomePai, Date nascPai, Date nascMae, String ccObs, char ccIndiConj, char ccCorrPoup, String pis, String cbo, String nomeVendedor, Date dtNasc, Integer cgMicroPeqEmp, Date certTrab, Character vctr, Character suspenso, String motivo, Integer op, Integer tpFor, String celfone, Set cpRepresentantes) {
       this.codigo = codigo;
       this.gano = gano;
       this.gempresa = gempresa;
       this.credorId = credorId;
       this.grupo = grupo;
       this.endereco = endereco;
       this.codcidade = codcidade;
       this.cidade = cidade;
       this.fone = fone;
       this.cae = cae;
       this.fax = fax;
       this.contato = contato;
       this.bairro = bairro;
       this.uf = uf;
       this.cep = cep;
       this.inscMu = inscMu;
       this.inscEs = inscEs;
       this.inscMf = inscMf;
       this.banco = banco;
       this.agencia = agencia;
       this.CCorrente = CCorrente;
       this.bco = bco;
       this.age = age;
       this.dage = dage;
       this.CC = CC;
       this.dcC = dcC;
       this.tipoDoc1 = tipoDoc1;
       this.documento1 = documento1;
       this.tipoDoc2 = tipoDoc2;
       this.documento2 = documento2;
       this.tipo = tipo;
       this.simples = simples;
       this.debitos = debitos;
       this.dtDebitos = dtDebitos;
       this.dtCertCd = dtCertCd;
       this.usCertCd = usCertCd;
       this.infAdic = infAdic;
       this.desativa = desativa;
       this.nacionalid = nacionalid;
       this.fantasia = fantasia;
       this.srRecno = srRecno;
       this.nome = nome;
       this.EMail = EMail;
       this.tipoEmp = tipoEmp;
       this.cgIdentificacao = cgIdentificacao;
       this.dataCad = dataCad;
       this.gacesso = gacesso;
       this.ctaBancariaId = ctaBancariaId;
       this.capSocial = capSocial;
       this.certCrea = certCrea;
       this.certEstad = certEstad;
       this.certFalen = certFalen;
       this.certFeder = certFeder;
       this.certFgts = certFgts;
       this.certInss = certInss;
       this.certMunic = certMunic;
       this.certUniao = certUniao;
       this.certificado = certificado;
       this.certificadoAux = certificadoAux;
       this.cmaeId = cmaeId;
       this.cnaeId = cnaeId;
       this.dtCadastro = dtCadastro;
       this.email = email;
       this.gmunicipioId = gmunicipioId;
       this.nacionalidade = nacionalidade;
       this.objSocial = objSocial;
       this.site = site;
       this.municipio = municipio;
       this.inss = inss;
       this.atoConstit = atoConstit;
       this.cadMunic = cadMunic;
       this.cadEstad = cadEstad;
       this.cadCnpj = cadCnpj;
       this.procGerEst = procGerEst;
       this.vcd = vcd;
       this.vce = vce;
       this.vac = vac;
       this.vpg = vpg;
       this.vci = vci;
       this.vcm = vcm;
       this.vcam = vcam;
       this.vdc = vdc;
       this.vcf = vcf;
       this.vcfa = vcfa;
       this.vcae = vcae;
       this.vcfe = vcfe;
       this.vcre = vcre;
       this.vcn = vcn;
       this.cadData = cadData;
       this.avisoCredorCnab240 = avisoCredorCnab240;
       this.nomeMae = nomeMae;
       this.nomePai = nomePai;
       this.nascPai = nascPai;
       this.nascMae = nascMae;
       this.ccObs = ccObs;
       this.ccIndiConj = ccIndiConj;
       this.ccCorrPoup = ccCorrPoup;
       this.pis = pis;
       this.cbo = cbo;
       this.nomeVendedor = nomeVendedor;
       this.dtNasc = dtNasc;
       this.cgMicroPeqEmp = cgMicroPeqEmp;
       this.certTrab = certTrab;
       this.vctr = vctr;
       this.suspenso = suspenso;
       this.motivo = motivo;
       this.op = op;
       this.tpFor = tpFor;
       this.celfone = celfone;
       this.cpRepresentantes = cpRepresentantes;
    }
   
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public Gano getGano() {
        return this.gano;
    }
    
    public void setGano(Gano gano) {
        this.gano = gano;
    }
    public Gempresa getGempresa() {
        return this.gempresa;
    }
    
    public void setGempresa(Gempresa gempresa) {
        this.gempresa = gempresa;
    }
    public int getCredorId() {
        return this.credorId;
    }
    
    public void setCredorId(int credorId) {
        this.credorId = credorId;
    }
    public String getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(String grupo) {
        this.grupo = grupo;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    public String getCodcidade() {
        return this.codcidade;
    }
    
    public void setCodcidade(String codcidade) {
        this.codcidade = codcidade;
    }
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }
    public String getFone() {
        return this.fone;
    }
    
    public void setFone(String fone) {
        this.fone = fone;
    }
    public String getCae() {
        return this.cae;
    }
    
    public void setCae(String cae) {
        this.cae = cae;
    }
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }
    public String getContato() {
        return this.contato;
    }
    
    public void setContato(String contato) {
        this.contato = contato;
    }
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }
    public String getUf() {
        return this.uf;
    }
    
    public void setUf(String uf) {
        this.uf = uf;
    }
    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }
    public String getInscMu() {
        return this.inscMu;
    }
    
    public void setInscMu(String inscMu) {
        this.inscMu = inscMu;
    }
    public String getInscEs() {
        return this.inscEs;
    }
    
    public void setInscEs(String inscEs) {
        this.inscEs = inscEs;
    }
    public String getInscMf() {
        return this.inscMf;
    }
    
    public void setInscMf(String inscMf) {
        this.inscMf = inscMf;
    }
    public String getBanco() {
        return this.banco;
    }
    
    public void setBanco(String banco) {
        this.banco = banco;
    }
    public String getAgencia() {
        return this.agencia;
    }
    
    public void setAgencia(String agencia) {
        this.agencia = agencia;
    }
    public String getCCorrente() {
        return this.CCorrente;
    }
    
    public void setCCorrente(String CCorrente) {
        this.CCorrente = CCorrente;
    }
    public String getBco() {
        return this.bco;
    }
    
    public void setBco(String bco) {
        this.bco = bco;
    }
    public String getAge() {
        return this.age;
    }
    
    public void setAge(String age) {
        this.age = age;
    }
    public Character getDage() {
        return this.dage;
    }
    
    public void setDage(Character dage) {
        this.dage = dage;
    }
    public String getCC() {
        return this.CC;
    }
    
    public void setCC(String CC) {
        this.CC = CC;
    }
    public Character getDcC() {
        return this.dcC;
    }
    
    public void setDcC(Character dcC) {
        this.dcC = dcC;
    }
    public String getTipoDoc1() {
        return this.tipoDoc1;
    }
    
    public void setTipoDoc1(String tipoDoc1) {
        this.tipoDoc1 = tipoDoc1;
    }
    public String getDocumento1() {
        return this.documento1;
    }
    
    public void setDocumento1(String documento1) {
        this.documento1 = documento1;
    }
    public String getTipoDoc2() {
        return this.tipoDoc2;
    }
    
    public void setTipoDoc2(String tipoDoc2) {
        this.tipoDoc2 = tipoDoc2;
    }
    public String getDocumento2() {
        return this.documento2;
    }
    
    public void setDocumento2(String documento2) {
        this.documento2 = documento2;
    }
    public Character getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Character tipo) {
        this.tipo = tipo;
    }
    public Character getSimples() {
        return this.simples;
    }
    
    public void setSimples(Character simples) {
        this.simples = simples;
    }
    public Character getDebitos() {
        return this.debitos;
    }
    
    public void setDebitos(Character debitos) {
        this.debitos = debitos;
    }
    public Date getDtDebitos() {
        return this.dtDebitos;
    }
    
    public void setDtDebitos(Date dtDebitos) {
        this.dtDebitos = dtDebitos;
    }
    public Date getDtCertCd() {
        return this.dtCertCd;
    }
    
    public void setDtCertCd(Date dtCertCd) {
        this.dtCertCd = dtCertCd;
    }
    public String getUsCertCd() {
        return this.usCertCd;
    }
    
    public void setUsCertCd(String usCertCd) {
        this.usCertCd = usCertCd;
    }
    public String getInfAdic() {
        return this.infAdic;
    }
    
    public void setInfAdic(String infAdic) {
        this.infAdic = infAdic;
    }
    public char getDesativa() {
        return this.desativa;
    }
    
    public void setDesativa(char desativa) {
        this.desativa = desativa;
    }
    public Character getNacionalid() {
        return this.nacionalid;
    }
    
    public void setNacionalid(Character nacionalid) {
        this.nacionalid = nacionalid;
    }
    public String getFantasia() {
        return this.fantasia;
    }
    
    public void setFantasia(String fantasia) {
        this.fantasia = fantasia;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getEMail() {
        return this.EMail;
    }
    
    public void setEMail(String EMail) {
        this.EMail = EMail;
    }
    public Short getTipoEmp() {
        return this.tipoEmp;
    }
    
    public void setTipoEmp(Short tipoEmp) {
        this.tipoEmp = tipoEmp;
    }
    public String getCgIdentificacao() {
        return this.cgIdentificacao;
    }
    
    public void setCgIdentificacao(String cgIdentificacao) {
        this.cgIdentificacao = cgIdentificacao;
    }
    public Date getDataCad() {
        return this.dataCad;
    }
    
    public void setDataCad(Date dataCad) {
        this.dataCad = dataCad;
    }
    public Date getGacesso() {
        return this.gacesso;
    }
    
    public void setGacesso(Date gacesso) {
        this.gacesso = gacesso;
    }
    public Integer getCtaBancariaId() {
        return this.ctaBancariaId;
    }
    
    public void setCtaBancariaId(Integer ctaBancariaId) {
        this.ctaBancariaId = ctaBancariaId;
    }
    public BigDecimal getCapSocial() {
        return this.capSocial;
    }
    
    public void setCapSocial(BigDecimal capSocial) {
        this.capSocial = capSocial;
    }
    public Date getCertCrea() {
        return this.certCrea;
    }
    
    public void setCertCrea(Date certCrea) {
        this.certCrea = certCrea;
    }
    public Date getCertEstad() {
        return this.certEstad;
    }
    
    public void setCertEstad(Date certEstad) {
        this.certEstad = certEstad;
    }
    public Date getCertFalen() {
        return this.certFalen;
    }
    
    public void setCertFalen(Date certFalen) {
        this.certFalen = certFalen;
    }
    public Date getCertFeder() {
        return this.certFeder;
    }
    
    public void setCertFeder(Date certFeder) {
        this.certFeder = certFeder;
    }
    public Date getCertFgts() {
        return this.certFgts;
    }
    
    public void setCertFgts(Date certFgts) {
        this.certFgts = certFgts;
    }
    public Date getCertInss() {
        return this.certInss;
    }
    
    public void setCertInss(Date certInss) {
        this.certInss = certInss;
    }
    public Date getCertMunic() {
        return this.certMunic;
    }
    
    public void setCertMunic(Date certMunic) {
        this.certMunic = certMunic;
    }
    public Date getCertUniao() {
        return this.certUniao;
    }
    
    public void setCertUniao(Date certUniao) {
        this.certUniao = certUniao;
    }
    public Integer getCertificado() {
        return this.certificado;
    }
    
    public void setCertificado(Integer certificado) {
        this.certificado = certificado;
    }
    public String getCertificadoAux() {
        return this.certificadoAux;
    }
    
    public void setCertificadoAux(String certificadoAux) {
        this.certificadoAux = certificadoAux;
    }
    public String getCmaeId() {
        return this.cmaeId;
    }
    
    public void setCmaeId(String cmaeId) {
        this.cmaeId = cmaeId;
    }
    public String getCnaeId() {
        return this.cnaeId;
    }
    
    public void setCnaeId(String cnaeId) {
        this.cnaeId = cnaeId;
    }
    public Date getDtCadastro() {
        return this.dtCadastro;
    }
    
    public void setDtCadastro(Date dtCadastro) {
        this.dtCadastro = dtCadastro;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Integer getGmunicipioId() {
        return this.gmunicipioId;
    }
    
    public void setGmunicipioId(Integer gmunicipioId) {
        this.gmunicipioId = gmunicipioId;
    }
    public String getNacionalidade() {
        return this.nacionalidade;
    }
    
    public void setNacionalidade(String nacionalidade) {
        this.nacionalidade = nacionalidade;
    }
    public String getObjSocial() {
        return this.objSocial;
    }
    
    public void setObjSocial(String objSocial) {
        this.objSocial = objSocial;
    }
    public String getSite() {
        return this.site;
    }
    
    public void setSite(String site) {
        this.site = site;
    }
    public String getMunicipio() {
        return this.municipio;
    }
    
    public void setMunicipio(String municipio) {
        this.municipio = municipio;
    }
    public String getInss() {
        return this.inss;
    }
    
    public void setInss(String inss) {
        this.inss = inss;
    }
    public Date getAtoConstit() {
        return this.atoConstit;
    }
    
    public void setAtoConstit(Date atoConstit) {
        this.atoConstit = atoConstit;
    }
    public Date getCadMunic() {
        return this.cadMunic;
    }
    
    public void setCadMunic(Date cadMunic) {
        this.cadMunic = cadMunic;
    }
    public Date getCadEstad() {
        return this.cadEstad;
    }
    
    public void setCadEstad(Date cadEstad) {
        this.cadEstad = cadEstad;
    }
    public Date getCadCnpj() {
        return this.cadCnpj;
    }
    
    public void setCadCnpj(Date cadCnpj) {
        this.cadCnpj = cadCnpj;
    }
    public Date getProcGerEst() {
        return this.procGerEst;
    }
    
    public void setProcGerEst(Date procGerEst) {
        this.procGerEst = procGerEst;
    }
    public Character getVcd() {
        return this.vcd;
    }
    
    public void setVcd(Character vcd) {
        this.vcd = vcd;
    }
    public Character getVce() {
        return this.vce;
    }
    
    public void setVce(Character vce) {
        this.vce = vce;
    }
    public Character getVac() {
        return this.vac;
    }
    
    public void setVac(Character vac) {
        this.vac = vac;
    }
    public Character getVpg() {
        return this.vpg;
    }
    
    public void setVpg(Character vpg) {
        this.vpg = vpg;
    }
    public Character getVci() {
        return this.vci;
    }
    
    public void setVci(Character vci) {
        this.vci = vci;
    }
    public Character getVcm() {
        return this.vcm;
    }
    
    public void setVcm(Character vcm) {
        this.vcm = vcm;
    }
    public Character getVcam() {
        return this.vcam;
    }
    
    public void setVcam(Character vcam) {
        this.vcam = vcam;
    }
    public Character getVdc() {
        return this.vdc;
    }
    
    public void setVdc(Character vdc) {
        this.vdc = vdc;
    }
    public Character getVcf() {
        return this.vcf;
    }
    
    public void setVcf(Character vcf) {
        this.vcf = vcf;
    }
    public Character getVcfa() {
        return this.vcfa;
    }
    
    public void setVcfa(Character vcfa) {
        this.vcfa = vcfa;
    }
    public Character getVcae() {
        return this.vcae;
    }
    
    public void setVcae(Character vcae) {
        this.vcae = vcae;
    }
    public Character getVcfe() {
        return this.vcfe;
    }
    
    public void setVcfe(Character vcfe) {
        this.vcfe = vcfe;
    }
    public Character getVcre() {
        return this.vcre;
    }
    
    public void setVcre(Character vcre) {
        this.vcre = vcre;
    }
    public Character getVcn() {
        return this.vcn;
    }
    
    public void setVcn(Character vcn) {
        this.vcn = vcn;
    }
    public Date getCadData() {
        return this.cadData;
    }
    
    public void setCadData(Date cadData) {
        this.cadData = cadData;
    }
    public Character getAvisoCredorCnab240() {
        return this.avisoCredorCnab240;
    }
    
    public void setAvisoCredorCnab240(Character avisoCredorCnab240) {
        this.avisoCredorCnab240 = avisoCredorCnab240;
    }
    public String getNomeMae() {
        return this.nomeMae;
    }
    
    public void setNomeMae(String nomeMae) {
        this.nomeMae = nomeMae;
    }
    public String getNomePai() {
        return this.nomePai;
    }
    
    public void setNomePai(String nomePai) {
        this.nomePai = nomePai;
    }
    public Date getNascPai() {
        return this.nascPai;
    }
    
    public void setNascPai(Date nascPai) {
        this.nascPai = nascPai;
    }
    public Date getNascMae() {
        return this.nascMae;
    }
    
    public void setNascMae(Date nascMae) {
        this.nascMae = nascMae;
    }
    public String getCcObs() {
        return this.ccObs;
    }
    
    public void setCcObs(String ccObs) {
        this.ccObs = ccObs;
    }
    public char getCcIndiConj() {
        return this.ccIndiConj;
    }
    
    public void setCcIndiConj(char ccIndiConj) {
        this.ccIndiConj = ccIndiConj;
    }
    public char getCcCorrPoup() {
        return this.ccCorrPoup;
    }
    
    public void setCcCorrPoup(char ccCorrPoup) {
        this.ccCorrPoup = ccCorrPoup;
    }
    public String getPis() {
        return this.pis;
    }
    
    public void setPis(String pis) {
        this.pis = pis;
    }
    public String getCbo() {
        return this.cbo;
    }
    
    public void setCbo(String cbo) {
        this.cbo = cbo;
    }
    public String getNomeVendedor() {
        return this.nomeVendedor;
    }
    
    public void setNomeVendedor(String nomeVendedor) {
        this.nomeVendedor = nomeVendedor;
    }
    public Date getDtNasc() {
        return this.dtNasc;
    }
    
    public void setDtNasc(Date dtNasc) {
        this.dtNasc = dtNasc;
    }
    public Integer getCgMicroPeqEmp() {
        return this.cgMicroPeqEmp;
    }
    
    public void setCgMicroPeqEmp(Integer cgMicroPeqEmp) {
        this.cgMicroPeqEmp = cgMicroPeqEmp;
    }
    public Date getCertTrab() {
        return this.certTrab;
    }
    
    public void setCertTrab(Date certTrab) {
        this.certTrab = certTrab;
    }
    public Character getVctr() {
        return this.vctr;
    }
    
    public void setVctr(Character vctr) {
        this.vctr = vctr;
    }
    public Character getSuspenso() {
        return this.suspenso;
    }
    
    public void setSuspenso(Character suspenso) {
        this.suspenso = suspenso;
    }
    public String getMotivo() {
        return this.motivo;
    }
    
    public void setMotivo(String motivo) {
        this.motivo = motivo;
    }
    public Integer getOp() {
        return this.op;
    }
    
    public void setOp(Integer op) {
        this.op = op;
    }
    public Integer getTpFor() {
        return this.tpFor;
    }
    
    public void setTpFor(Integer tpFor) {
        this.tpFor = tpFor;
    }
    public String getCelfone() {
        return this.celfone;
    }
    
    public void setCelfone(String celfone) {
        this.celfone = celfone;
    }
    public Set getCpRepresentantes() {
        return this.cpRepresentantes;
    }
    
    public void setCpRepresentantes(Set cpRepresentantes) {
        this.cpRepresentantes = cpRepresentantes;
    }




}


