package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * OrNatDesp generated by hbm2java
 */
public class OrNatDesp  implements java.io.Serializable {


     private String natDespId;
     private Gano gano;
     private Gempresa gempresa;
     private int reduzido;
     private String ligacaoTce;
     private String naturezaDespesa;
     private Character lancar;
     private Character lancar2;
     private Character ctecId;
     private Character ndespId;
     private String mdapId;
     private String eldeId;
     private String seldeId;
     private String deldeId;
     private String conta;
     private String tce;
     private String tce2;
     private String tcesaude;
     private String nome;
     private Date gacesso;
     private long srRecno;
     private int claDesp;
     private Character desdobrar;
     private Date sysDataC;
     private String sysUsuCa;
     private Date sysDataA;
     private String sysUsuAl;
     private Date sysDataE;
     private String sysUsuEx;
     private Integer nivel;
     private String elde;
     private String selde;
     private String delde;
     private Character despPessoal;
     private Character incorporaPatr;
     private Set cpMaterialNatDesps = new HashSet(0);
     private Set cpItems = new HashSet(0);
     private Set cpMaterials = new HashSet(0);

    public OrNatDesp() {
    }

	
    public OrNatDesp(String natDespId, Gano gano, Gempresa gempresa, int reduzido, long srRecno, int claDesp) {
        this.natDespId = natDespId;
        this.gano = gano;
        this.gempresa = gempresa;
        this.reduzido = reduzido;
        this.srRecno = srRecno;
        this.claDesp = claDesp;
    }
    public OrNatDesp(String natDespId, Gano gano, Gempresa gempresa, int reduzido, String ligacaoTce, String naturezaDespesa, Character lancar, Character lancar2, Character ctecId, Character ndespId, String mdapId, String eldeId, String seldeId, String deldeId, String conta, String tce, String tce2, String tcesaude, String nome, Date gacesso, long srRecno, int claDesp, Character desdobrar, Date sysDataC, String sysUsuCa, Date sysDataA, String sysUsuAl, Date sysDataE, String sysUsuEx, Integer nivel, String elde, String selde, String delde, Character despPessoal, Character incorporaPatr, Set cpMaterialNatDesps, Set cpItems, Set cpMaterials) {
       this.natDespId = natDespId;
       this.gano = gano;
       this.gempresa = gempresa;
       this.reduzido = reduzido;
       this.ligacaoTce = ligacaoTce;
       this.naturezaDespesa = naturezaDespesa;
       this.lancar = lancar;
       this.lancar2 = lancar2;
       this.ctecId = ctecId;
       this.ndespId = ndespId;
       this.mdapId = mdapId;
       this.eldeId = eldeId;
       this.seldeId = seldeId;
       this.deldeId = deldeId;
       this.conta = conta;
       this.tce = tce;
       this.tce2 = tce2;
       this.tcesaude = tcesaude;
       this.nome = nome;
       this.gacesso = gacesso;
       this.srRecno = srRecno;
       this.claDesp = claDesp;
       this.desdobrar = desdobrar;
       this.sysDataC = sysDataC;
       this.sysUsuCa = sysUsuCa;
       this.sysDataA = sysDataA;
       this.sysUsuAl = sysUsuAl;
       this.sysDataE = sysDataE;
       this.sysUsuEx = sysUsuEx;
       this.nivel = nivel;
       this.elde = elde;
       this.selde = selde;
       this.delde = delde;
       this.despPessoal = despPessoal;
       this.incorporaPatr = incorporaPatr;
       this.cpMaterialNatDesps = cpMaterialNatDesps;
       this.cpItems = cpItems;
       this.cpMaterials = cpMaterials;
    }
   
    public String getNatDespId() {
        return this.natDespId;
    }
    
    public void setNatDespId(String natDespId) {
        this.natDespId = natDespId;
    }
    public Gano getGano() {
        return this.gano;
    }
    
    public void setGano(Gano gano) {
        this.gano = gano;
    }
    public Gempresa getGempresa() {
        return this.gempresa;
    }
    
    public void setGempresa(Gempresa gempresa) {
        this.gempresa = gempresa;
    }
    public int getReduzido() {
        return this.reduzido;
    }
    
    public void setReduzido(int reduzido) {
        this.reduzido = reduzido;
    }
    public String getLigacaoTce() {
        return this.ligacaoTce;
    }
    
    public void setLigacaoTce(String ligacaoTce) {
        this.ligacaoTce = ligacaoTce;
    }
    public String getNaturezaDespesa() {
        return this.naturezaDespesa;
    }
    
    public void setNaturezaDespesa(String naturezaDespesa) {
        this.naturezaDespesa = naturezaDespesa;
    }
    public Character getLancar() {
        return this.lancar;
    }
    
    public void setLancar(Character lancar) {
        this.lancar = lancar;
    }
    public Character getLancar2() {
        return this.lancar2;
    }
    
    public void setLancar2(Character lancar2) {
        this.lancar2 = lancar2;
    }
    public Character getCtecId() {
        return this.ctecId;
    }
    
    public void setCtecId(Character ctecId) {
        this.ctecId = ctecId;
    }
    public Character getNdespId() {
        return this.ndespId;
    }
    
    public void setNdespId(Character ndespId) {
        this.ndespId = ndespId;
    }
    public String getMdapId() {
        return this.mdapId;
    }
    
    public void setMdapId(String mdapId) {
        this.mdapId = mdapId;
    }
    public String getEldeId() {
        return this.eldeId;
    }
    
    public void setEldeId(String eldeId) {
        this.eldeId = eldeId;
    }
    public String getSeldeId() {
        return this.seldeId;
    }
    
    public void setSeldeId(String seldeId) {
        this.seldeId = seldeId;
    }
    public String getDeldeId() {
        return this.deldeId;
    }
    
    public void setDeldeId(String deldeId) {
        this.deldeId = deldeId;
    }
    public String getConta() {
        return this.conta;
    }
    
    public void setConta(String conta) {
        this.conta = conta;
    }
    public String getTce() {
        return this.tce;
    }
    
    public void setTce(String tce) {
        this.tce = tce;
    }
    public String getTce2() {
        return this.tce2;
    }
    
    public void setTce2(String tce2) {
        this.tce2 = tce2;
    }
    public String getTcesaude() {
        return this.tcesaude;
    }
    
    public void setTcesaude(String tcesaude) {
        this.tcesaude = tcesaude;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Date getGacesso() {
        return this.gacesso;
    }
    
    public void setGacesso(Date gacesso) {
        this.gacesso = gacesso;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }
    public int getClaDesp() {
        return this.claDesp;
    }
    
    public void setClaDesp(int claDesp) {
        this.claDesp = claDesp;
    }
    public Character getDesdobrar() {
        return this.desdobrar;
    }
    
    public void setDesdobrar(Character desdobrar) {
        this.desdobrar = desdobrar;
    }
    public Date getSysDataC() {
        return this.sysDataC;
    }
    
    public void setSysDataC(Date sysDataC) {
        this.sysDataC = sysDataC;
    }
    public String getSysUsuCa() {
        return this.sysUsuCa;
    }
    
    public void setSysUsuCa(String sysUsuCa) {
        this.sysUsuCa = sysUsuCa;
    }
    public Date getSysDataA() {
        return this.sysDataA;
    }
    
    public void setSysDataA(Date sysDataA) {
        this.sysDataA = sysDataA;
    }
    public String getSysUsuAl() {
        return this.sysUsuAl;
    }
    
    public void setSysUsuAl(String sysUsuAl) {
        this.sysUsuAl = sysUsuAl;
    }
    public Date getSysDataE() {
        return this.sysDataE;
    }
    
    public void setSysDataE(Date sysDataE) {
        this.sysDataE = sysDataE;
    }
    public String getSysUsuEx() {
        return this.sysUsuEx;
    }
    
    public void setSysUsuEx(String sysUsuEx) {
        this.sysUsuEx = sysUsuEx;
    }
    public Integer getNivel() {
        return this.nivel;
    }
    
    public void setNivel(Integer nivel) {
        this.nivel = nivel;
    }
    public String getElde() {
        return this.elde;
    }
    
    public void setElde(String elde) {
        this.elde = elde;
    }
    public String getSelde() {
        return this.selde;
    }
    
    public void setSelde(String selde) {
        this.selde = selde;
    }
    public String getDelde() {
        return this.delde;
    }
    
    public void setDelde(String delde) {
        this.delde = delde;
    }
    public Character getDespPessoal() {
        return this.despPessoal;
    }
    
    public void setDespPessoal(Character despPessoal) {
        this.despPessoal = despPessoal;
    }
    public Character getIncorporaPatr() {
        return this.incorporaPatr;
    }
    
    public void setIncorporaPatr(Character incorporaPatr) {
        this.incorporaPatr = incorporaPatr;
    }
    public Set getCpMaterialNatDesps() {
        return this.cpMaterialNatDesps;
    }
    
    public void setCpMaterialNatDesps(Set cpMaterialNatDesps) {
        this.cpMaterialNatDesps = cpMaterialNatDesps;
    }
    public Set getCpItems() {
        return this.cpItems;
    }
    
    public void setCpItems(Set cpItems) {
        this.cpItems = cpItems;
    }
    public Set getCpMaterials() {
        return this.cpMaterials;
    }
    
    public void setCpMaterials(Set cpMaterials) {
        this.cpMaterials = cpMaterials;
    }




}


