package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1



/**
 * TceMtSubelementoId generated by hbm2java
 */
public class TceMtSubelementoId  implements java.io.Serializable {


     private String elementoId;
     private String subelementoId;

    public TceMtSubelementoId() {
    }

    public TceMtSubelementoId(String elementoId, String subelementoId) {
       this.elementoId = elementoId;
       this.subelementoId = subelementoId;
    }
   
    public String getElementoId() {
        return this.elementoId;
    }
    
    public void setElementoId(String elementoId) {
        this.elementoId = elementoId;
    }
    public String getSubelementoId() {
        return this.subelementoId;
    }
    
    public void setSubelementoId(String subelementoId) {
        this.subelementoId = subelementoId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TceMtSubelementoId) ) return false;
		 TceMtSubelementoId castOther = ( TceMtSubelementoId ) other; 
         
		 return ( (this.getElementoId()==castOther.getElementoId()) || ( this.getElementoId()!=null && castOther.getElementoId()!=null && this.getElementoId().equals(castOther.getElementoId()) ) )
 && ( (this.getSubelementoId()==castOther.getSubelementoId()) || ( this.getSubelementoId()!=null && castOther.getSubelementoId()!=null && this.getSubelementoId().equals(castOther.getSubelementoId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getElementoId() == null ? 0 : this.getElementoId().hashCode() );
         result = 37 * result + ( getSubelementoId() == null ? 0 : this.getSubelementoId().hashCode() );
         return result;
   }   


}


