package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TceMtMedida generated by hbm2java
 */
public class TceMtMedida  implements java.io.Serializable {


     private int tceMtMedidaId;
     private String tceMtMedida;
     private long srRecno;
     private String tceMtAbreviacao;
     private Set cpMedidas = new HashSet(0);

    public TceMtMedida() {
    }

	
    public TceMtMedida(int tceMtMedidaId, String tceMtMedida, long srRecno) {
        this.tceMtMedidaId = tceMtMedidaId;
        this.tceMtMedida = tceMtMedida;
        this.srRecno = srRecno;
    }
    public TceMtMedida(int tceMtMedidaId, String tceMtMedida, long srRecno, String tceMtAbreviacao, Set cpMedidas) {
       this.tceMtMedidaId = tceMtMedidaId;
       this.tceMtMedida = tceMtMedida;
       this.srRecno = srRecno;
       this.tceMtAbreviacao = tceMtAbreviacao;
       this.cpMedidas = cpMedidas;
    }
   
    public int getTceMtMedidaId() {
        return this.tceMtMedidaId;
    }
    
    public void setTceMtMedidaId(int tceMtMedidaId) {
        this.tceMtMedidaId = tceMtMedidaId;
    }
    public String getTceMtMedida() {
        return this.tceMtMedida;
    }
    
    public void setTceMtMedida(String tceMtMedida) {
        this.tceMtMedida = tceMtMedida;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }
    public String getTceMtAbreviacao() {
        return this.tceMtAbreviacao;
    }
    
    public void setTceMtAbreviacao(String tceMtAbreviacao) {
        this.tceMtAbreviacao = tceMtAbreviacao;
    }
    public Set getCpMedidas() {
        return this.cpMedidas;
    }
    
    public void setCpMedidas(Set cpMedidas) {
        this.cpMedidas = cpMedidas;
    }




}


