package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TceMtDesdobramento generated by hbm2java
 */
public class TceMtDesdobramento  implements java.io.Serializable {


     private TceMtDesdobramentoId id;
     private TceMtElemento tceMtElemento;
     private TceMtSubelemento tceMtSubelemento;
     private String desdobramento;
     private long srRecno;
     private Date gacesso;
     private Set cpMaterialNatDesps = new HashSet(0);
     private Set cpMaterials = new HashSet(0);

    public TceMtDesdobramento() {
    }

	
    public TceMtDesdobramento(TceMtDesdobramentoId id, TceMtElemento tceMtElemento, TceMtSubelemento tceMtSubelemento, String desdobramento, long srRecno) {
        this.id = id;
        this.tceMtElemento = tceMtElemento;
        this.tceMtSubelemento = tceMtSubelemento;
        this.desdobramento = desdobramento;
        this.srRecno = srRecno;
    }
    public TceMtDesdobramento(TceMtDesdobramentoId id, TceMtElemento tceMtElemento, TceMtSubelemento tceMtSubelemento, String desdobramento, long srRecno, Date gacesso, Set cpMaterialNatDesps, Set cpMaterials) {
       this.id = id;
       this.tceMtElemento = tceMtElemento;
       this.tceMtSubelemento = tceMtSubelemento;
       this.desdobramento = desdobramento;
       this.srRecno = srRecno;
       this.gacesso = gacesso;
       this.cpMaterialNatDesps = cpMaterialNatDesps;
       this.cpMaterials = cpMaterials;
    }
   
    public TceMtDesdobramentoId getId() {
        return this.id;
    }
    
    public void setId(TceMtDesdobramentoId id) {
        this.id = id;
    }
    public TceMtElemento getTceMtElemento() {
        return this.tceMtElemento;
    }
    
    public void setTceMtElemento(TceMtElemento tceMtElemento) {
        this.tceMtElemento = tceMtElemento;
    }
    public TceMtSubelemento getTceMtSubelemento() {
        return this.tceMtSubelemento;
    }
    
    public void setTceMtSubelemento(TceMtSubelemento tceMtSubelemento) {
        this.tceMtSubelemento = tceMtSubelemento;
    }
    public String getDesdobramento() {
        return this.desdobramento;
    }
    
    public void setDesdobramento(String desdobramento) {
        this.desdobramento = desdobramento;
    }
    public long getSrRecno() {
        return this.srRecno;
    }
    
    public void setSrRecno(long srRecno) {
        this.srRecno = srRecno;
    }
    public Date getGacesso() {
        return this.gacesso;
    }
    
    public void setGacesso(Date gacesso) {
        this.gacesso = gacesso;
    }
    public Set getCpMaterialNatDesps() {
        return this.cpMaterialNatDesps;
    }
    
    public void setCpMaterialNatDesps(Set cpMaterialNatDesps) {
        this.cpMaterialNatDesps = cpMaterialNatDesps;
    }
    public Set getCpMaterials() {
        return this.cpMaterials;
    }
    
    public void setCpMaterials(Set cpMaterials) {
        this.cpMaterials = cpMaterials;
    }




}


