package entidades;
// Generated 25/08/2016 16:42:18 by Hibernate Tools 4.3.1



/**
 * TceMtDesdobramentoId generated by hbm2java
 */
public class TceMtDesdobramentoId  implements java.io.Serializable {


     private String elementoId;
     private String subelementoId;
     private String desdobramentoId;

    public TceMtDesdobramentoId() {
    }

    public TceMtDesdobramentoId(String elementoId, String subelementoId, String desdobramentoId) {
       this.elementoId = elementoId;
       this.subelementoId = subelementoId;
       this.desdobramentoId = desdobramentoId;
    }
   
    public String getElementoId() {
        return this.elementoId;
    }
    
    public void setElementoId(String elementoId) {
        this.elementoId = elementoId;
    }
    public String getSubelementoId() {
        return this.subelementoId;
    }
    
    public void setSubelementoId(String subelementoId) {
        this.subelementoId = subelementoId;
    }
    public String getDesdobramentoId() {
        return this.desdobramentoId;
    }
    
    public void setDesdobramentoId(String desdobramentoId) {
        this.desdobramentoId = desdobramentoId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TceMtDesdobramentoId) ) return false;
		 TceMtDesdobramentoId castOther = ( TceMtDesdobramentoId ) other; 
         
		 return ( (this.getElementoId()==castOther.getElementoId()) || ( this.getElementoId()!=null && castOther.getElementoId()!=null && this.getElementoId().equals(castOther.getElementoId()) ) )
 && ( (this.getSubelementoId()==castOther.getSubelementoId()) || ( this.getSubelementoId()!=null && castOther.getSubelementoId()!=null && this.getSubelementoId().equals(castOther.getSubelementoId()) ) )
 && ( (this.getDesdobramentoId()==castOther.getDesdobramentoId()) || ( this.getDesdobramentoId()!=null && castOther.getDesdobramentoId()!=null && this.getDesdobramentoId().equals(castOther.getDesdobramentoId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getElementoId() == null ? 0 : this.getElementoId().hashCode() );
         result = 37 * result + ( getSubelementoId() == null ? 0 : this.getSubelementoId().hashCode() );
         result = 37 * result + ( getDesdobramentoId() == null ? 0 : this.getDesdobramentoId().hashCode() );
         return result;
   }   


}


